- packages/components/package.json
- packages/design-tokens/package.json
- packages/icons/package.json
- packages/test-utils/package.json
Also made package.jsons slightly more consistent
> publishConfig for scoped package publishing

- pull_request_template.md
Revision to make it clear that "intro" should be removed and replaced with changes. Moved Github issues to check list section.
- [-] Includes test coverage for all changes
> PR template revision

- CHANGELOG.md
- packages/www/src/MDX/Pre/CodeSandbox.tsx
- packages/www/src/documentation/components/overlays/tooltip.mdx
- Update layout for code sandbox actions, so as not to unintentionally obscure any of the code samples
- Updates Tooltip documentation to demonstrate placement options.
> Code Sandbox action button layout updates

- jest.config.js
- package.json
- packages/components/package.json
- packages/components/src/Card/__snapshots__/Card.test.tsx.snap
- packages/components/src/Form/Fields/FieldRadio/__snapshots__/FieldRadio.test.tsx.snap
- packages/components/src/Form/Fields/FieldSelect/__snapshots__/FieldSelect.test.tsx.snap
- packages/components/src/Form/Inputs/Radio/__snapshots__/Radio.test.tsx.snap
- packages/components/src/Form/Inputs/Select/__snapshots__/Select.test.tsx.snap
- packages/components/src/Modal/Layout/__snapshots__/ModalContent.test.tsx.snap
- packages/components/src/Tabs/Tabs.test.tsx
- packages/design-tokens/package.json
- packages/icons/package.json
- packages/test-utils/package.json
- tsconfig.json
- tsconfig.test.json
- yarn.lock
Add ttsc to offer better formatted styled components snapshots
Use ts-jest for tests to better replicate consumers
> Add ttsc to offer better formatted styled components snapshots

- packages/components/src/Form/Fields/FieldColor/ColorWheel/ColorWheel.tsx
ColorWheel: Fix issue with TS build on private get field
> ColorWheel: Fix issue with TS build on private get field

- CHANGELOG.md
- To ensure a successful review, please double check our checklist of requirements below. 
> Update CHANGELOG for 0.7.6

- CHANGELOG.md
- packages/www/src/MDX/Headings.tsx
- packages/www/src/MDX/Pre/allComponents.ts
- packages/www/src/documentation/getting-started/extending.mdx
- packages/www/src/documentation/getting-started/index.mdx
- packages/www/src/documentation/getting-started/navigation.ts
- packages/www/src/documentation/getting-started/theme.mdx
- packages/www/src/pages/index.tsx
- Update documentation to reflect installation requirements
- Also add note re: `.yarnclean` workaround for @types/styled-components gotcha
- [-] Includes test coverage for all changes
- [-] Build and tests are passing
> Update documentation to reflect installation requirements

- CHANGELOG.md
- packages/components/README.md
- adds a brief statement to components/README about how to render new components in gatsby
> New component documentation instructions

- CHANGELOG.md
- jest.setup.js
- packages/components/src/Button/IconButton.test.tsx
- packages/components/src/Form/Fields/FieldColor/LuminositySlider/LuminositySlider.tsx
- packages/components/src/Form/Fields/FieldColor/LuminositySlider/__snapshots__/LuminositySlider.test.tsx.snap
- packages/components/src/Form/Inputs/Slider/Slider.test.tsx
- packages/components/src/Form/Inputs/Slider/Slider.tsx
- packages/components/src/Form/Inputs/Slider/__snapshots__/Slider.test.tsx.snap
- packages/components/src/Form/Inputs/Slider/slider_sizes.ts
- packages/components/src/Layout/Box/Box.test.tsx
- packages/components/src/List/ListItem.test.tsx
- packages/playground/src/Slider/SliderDemo.tsx
- packages/playground/src/index.tsx
- Styles <Slider /> component to provide a rich branded experience
> [LENS-415] Styled slider input

- CHANGELOG.md
- packages/www/src/documentation/components/forms/slider.mdx
- Updates slider.mdx to document new layout and feature options
> Slider documentation

- packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
- packages/components/src/Button/ButtonBase.tsx
- packages/components/src/Button/__snapshots__/Button.test.tsx.snap
- packages/components/src/Button/__snapshots__/ButtonOutline.test.tsx.snap
- packages/components/src/Button/__snapshots__/ButtonTransparent.test.tsx.snap
- packages/components/src/Button/__snapshots__/IconButton.test.tsx.snap
- packages/components/src/Modal/Layout/__snapshots__/ModalHeader.test.tsx.snap
✨ Changes
- update line-height for baseButton
- update snapshot tests
✅ Requirements
📷 Screenshots
> Lara/xsmall button line height/lens 453

- CHANGELOG.md
- packages/icons/src/svg/Api.svg
> Add Api icon

- CHANGELOG.md
- packages/www/src/documentation/components/text/headings.mdx
✨ Changes
- update documentation for textTransform
✅ Requirements
- [  ] Build and tests are passing
📷 Screenshots
> updated documentation to show use of textTransform

- CHANGELOG.md
Update CHANGELOG for 0.7.8 release
> Update CHANGELOG for 0.7.8 release

- CHANGELOG.md
- packages/www/src/documentation/components/modals/confirm.mdx
✨ Changes
- update documentation and chagelog on useConfirm for better user experience
✅ Requirements
📷 Screenshots
> updated documentation for better user experience

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldSelect/__snapshots__/FieldSelect.test.tsx.snap
- packages/components/src/Form/Inputs/Select/Select.tsx
- packages/components/src/Form/Inputs/Select/__snapshots__/Select.test.tsx.snap
- Fix broken `Select` custom down arrow bg image
Before:
After:
> Fix select arrow

- CHANGELOG.md
- lerna.json
- packages/components/package.json
- packages/design-tokens/package.json
- packages/icons/package.json
- packages/playground/package.json
- packages/server/package.json
- packages/test-utils/package.json
- packages/www/package.json
> Module should output ES6

- CHANGELOG.md
- I neglected to update the changelog in the already-merged Select PR.
> Add select to the changelog

- CHANGELOG.md
- packages/components/src/Menu/MenuItem/MenuItem.tsx
- packages/components/src/Menu/MenuItem/MenuItemButton.tsx
- packages/components/src/Menu/MenuItem/MenuItemListItem.tsx
- packages/components/src/Menu/MenuItem/__snapshots__/MenuItem.test.tsx.snap
- packages/components/src/Menu/__snapshots__/MenuGroup.test.tsx.snap
✨ Changes
- update ManuItem to not show focus on mouse click
- update test to respond to the change
✅ Requirements
📷 Screenshots
> MenuItem mouse and keyboard focus

- packages/components/src/Form/Fields/FieldCheckbox/__snapshots__/FieldCheckbox.test.tsx.snap
- packages/components/src/Form/Fields/FieldColor/FieldColor.tsx
- packages/components/src/Form/Fields/FieldColor/Swatch/Swatch.tsx
- packages/components/src/Form/Fields/FieldColor/Swatch/__snapshots__/Swatch.test.tsx.snap
- packages/components/src/Form/Fields/FieldRadio/__snapshots__/FieldRadio.test.tsx.snap
- packages/components/src/Form/Fields/FieldSelect/__snapshots__/FieldSelect.test.tsx.snap
- packages/components/src/Form/Fields/FieldText/__snapshots__/FieldText.test.tsx.snap
- packages/components/src/Form/Fields/FieldToggleSwitch/__snapshots__/FieldToggleSwitch.test.tsx.snap
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Form/Inputs/InputSearch/InputSearch.tsx
- packages/components/src/Form/Inputs/InputSearch/InputSearchControls.tsx
- packages/components/src/Form/Inputs/InputSearch/__snapshots__/InputSearch.test.tsx.snap
- packages/components/src/Form/Inputs/InputText/InputText.tsx
- packages/components/src/Form/Inputs/InputText/__snapshots__/InputText.test.tsx.snap
- packages/components/src/Form/Label/Label.tsx
- packages/components/src/Form/Label/__snapshots__/Label.test.tsx.snap
- packages/components/src/Form/ValidationMessage/ValidationMessage.tsx
- packages/components/src/Form/ValidationMessage/__snapshots__/ValidationMessage.test.tsx.snap
- packages/components/src/Form/__snapshots__/Form.test.tsx.snap
- packages/playground/src/Select/SelectDemo.tsx
This PR is a first pass at some improvements to some input components. It updates the focus, hover, and disabled states as well a few changes to its dimensions.
> Update text input styling

- packages/components/src/Popover/Popover.tsx
c.f. https://looker.atlassian.net/browse/LENS-526
> LENS-526 popover contents: {overflow-y: auto;}

- packages/icons/bin/build.js
- packages/icons/bin/icon_template.js
- packages/icons/package.json
- yarn.lock
- @svgr added a feature where it auto-generates the index file duplicating the task we were already doing in the build process.
- This PR removes our index-build step and properly renames the index file so builds succeed.
- Also updated Icon template to have req'd titleId prop
- [-] Includes test coverage for all changes
- [-] PR is ideally < 400LOC
> Upgrade @svgr/cli and adjust build accordingly

- packages/components/src/Banner/Banner.tsx
- packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
c.f. https://looker.atlassian.net/browse/LENS-525
> LENS-525 allow banner contents to flex into available horizontal space

- packages/www/src/documentation/components/content/tabs.mdx
- packages/www/src/documentation/components/overlays/popover.mdx
Replace existing image usage with text / emoji
> Remove images with unknown ownership

- packages/icons/src/svg/Download.svg
> Add download icon

- CHANGELOG.md
- packages/icons/README.md
This PR adds a small bit of documentation around recommended icons naming conventions
- [x ] PR is ideally < 400LOC
> Add small documentation blurb about naming icons

- CHANGELOG.md
> Changelog updates for 0.7.19

- CHANGELOG.md
- packages/components/src/Form/Inputs/Slider/Slider.tsx
- packages/components/src/Form/Inputs/Slider/__snapshots__/Slider.test.tsx.snap
- packages/components/src/Form/Inputs/Slider/slider_sizes.ts
- packages/playground/src/Slider/SliderDemo.tsx
- packages/playground/src/index.tsx
- packages/www/src/documentation/components/forms/slider.mdx
- Updates slider component to match designs in figma
> [LENS-568] Update Single-Value Slider Styles

- CHANGELOG.md
- packages/components/src/Form/Inputs/InputDate/InputDate.test.tsx
- packages/components/src/Form/Inputs/InputDate/InputDate.tsx
- packages/components/src/Form/Inputs/InputDateRange/InputDateRange.tsx
- packages/playground/src/InputDate/InputDateDemo.tsx
- packages/playground/src/index.tsx
- Fixes test mocks for InputDate and InputDateRange
- Adds controlled component behavior to InputDate
> Controlled InputDate component

- CHANGELOG.md
> 0.7.4 Changelog tweaks

- package.json
- packages/components/src/Button/ButtonSet.tsx
- packages/components/src/Calendar/CalendarNav.test.tsx
- packages/components/src/Form/Fields/FieldColor/utils/color_format_utils.ts
- packages/components/src/Form/Inputs/Combobox/ComboboxMultiInput.tsx
- packages/components/src/Form/Inputs/Combobox/ComboboxOption.tsx
- packages/components/src/Form/Inputs/Combobox/utils/state.ts
- packages/components/src/Form/Inputs/InputChips/InputChips.tsx
- packages/components/src/Form/Inputs/InputDate/InputDate.test.tsx
- packages/components/src/Form/Inputs/InputDateRange/InputDateRange.test.tsx
- packages/components/src/Form/Inputs/InputText/InputText.test.tsx
- packages/components/src/Modal/ModalManager.tsx
- packages/components/src/Popover/Popover.tsx
- packages/playground/src/Select/SelectDemo.tsx
- packages/www/package.json
- packages/www/tsconfig.json
- yarn.lock
- Upgrade @looker/eslint-config dependency
- Deal with related lint tweaks and fixes
- Add `tsconfig.json` for eslint in www package (Gatsby's ESLint)
> Upgrade @looker/eslint-config dependency

- packages/www/src/documentation/components/modals/index.mdx
- packages/www/src/documentation/components/overlays/popover.mdx
A pass at some updated documentation for dialog and popover taxonomy
> First pass at modal and popover taxonomy updates

- package.json
- packages/test-utils/package.json
- packages/www/package.json
- yarn.lock
- Downgrade acorn
- Fix a few other minor warnings in Yarn install process
> Downgrade acorn

- CHANGELOG.md
- packages/components/src/ActionList/ActionList.test.tsx
- packages/components/src/ActionList/ActionList.tsx
- packages/components/src/ActionList/ActionListHeader/generate.tsx
- packages/components/src/ActionList/ActionListItem.tsx
- packages/components/src/ActionList/ActionListItemAction.tsx
- packages/components/src/ActionList/utils/__snapshots__/sort_utils.test.ts.snap
- packages/components/src/ActionList/utils/sort_utils.test.ts
- packages/playground/src/ActionList/ActionListDemo.tsx
- packages/playground/src/ActionList/SortableActionListDemo.tsx
- Updated `ActionListItemAction` to close Action menu on `MenuItem` click
- Changed "children" property in `ActionListColumn` to "title"
> Action List: Close Actions Menu on Action click

- packages/components/src/ActionList/ActionListItemColumn.tsx
- packages/playground/src/ActionList/ActionListDemo.tsx
- packages/playground/src/index.tsx
- Added `xsmall` margin-right to indicator container on `ActionListItemColumn`
> Added xsmall margin-right to indicator on ActionListItemColumn

- package.json
- yarn.lock
- Fix issue with Gatsby start-up due to package conflict
> Fix Gatsby conflict with sharp version

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldTextArea/__snapshots__/FieldTextArea.test.tsx.snap
- packages/components/src/Form/Inputs/InputText/InputText.tsx
- packages/components/src/Form/Inputs/TextArea/TextArea.test.tsx
- packages/components/src/Form/Inputs/TextArea/TextArea.tsx
- packages/components/src/Form/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
- packages/playground/src/Form/TextAreaDemo.tsx
- packages/playground/src/index.tsx
- packages/www/src/documentation/components/forms/text-area.mdx
- To ensure a successful review, please double check our checklist of requirements below. 
> update TextArea to respond to resize

- CHANGELOG.md
- packages/components/src/ActionList/ActionListItemAction.tsx
- packages/components/src/Menu/MenuItem/MenuItem.tsx
- packages/playground/src/ActionList/ActionListDemo.tsx
- packages/playground/src/index.tsx
> ActionList: Actions accept "danger" as color

- CHANGELOG.md
- packages/components/src/ActionList/ActionListManager.test.tsx
- packages/components/src/ActionList/ActionListManager.tsx
- packages/components/src/ActionList/NoResults/NoResults.tsx
- packages/components/src/ActionList/NoResults/index.ts
- packages/components/src/ActionList/index.ts
- packages/playground/src/ActionList/ActionListDemo.tsx
- packages/playground/src/index.tsx
- Added ActionListManager Component to handle when an `ActionList` has no results / `ActionListItem`s and when an `ActionList` is in a loading state
> ActionList: ActionListManager Component

- CHANGELOG.md
- packages/components/package.json
- packages/components/src/Button/Button.test.tsx
- packages/components/src/Button/ButtonOutline.test.tsx
- packages/components/src/Button/ButtonTransparent.test.tsx
- packages/components/src/Form/Fields/FieldColor/FieldColor.test.tsx
- packages/components/src/Form/Fields/FieldSelect/FieldSelect.test.tsx
- packages/components/src/Form/Fieldset/Fieldset.test.tsx
- packages/components/src/Form/Form.test.tsx
- packages/components/src/Form/Inputs/InputSearch/InputSearch.test.tsx
- packages/components/src/Menu/MenuList.test.tsx
- packages/components/src/Modal/Modal.test.tsx
- packages/components/src/Tabs/Tabs.test.tsx
- packages/components/src/index.ts
- packages/design-tokens/README.md
- packages/playground/src/index.tsx
- packages/providers/package.json
- packages/providers/src/ComponentsProvider.tsx
- packages/providers/src/ThemeProvider.tsx
- packages/providers/src/index.ts
- packages/providers/tsconfig.build.json
- packages/test-utils/src/create_with_theme.tsx
- packages/www/src/Layout/Page.tsx
- packages/www/src/MDX/Pre/allComponents.ts
- packages/www/src/documentation/components/actions/demos/Button.tsx
- packages/www/src/documentation/getting-started/index.mdx
- packages/www/src/documentation/getting-started/theme.mdx
- Establish and utilize Components provider
- Added as a new package so that test-utils doesn't depend on components (creates circular dependency problems)
> Establish and utilize ComponentsProvider

- packages/components/src/Form/Fields/FieldToggleSwitch/__snapshots__/FieldToggleSwitch.test.tsx.snap
- packages/components/src/Form/Inputs/ToggleSwitch/ToggleSwitch.tsx
- packages/components/src/Form/Inputs/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
- packages/playground/src/index.tsx
- update color of ToggleSwitch from purple300 to purple400
- [ x ] Includes test coverage for all changes
- [ x ] Build and tests are passing
- [ x ] PR is ideally < 400LOC
> update color of ToggleSwitch

- packages/components/src/ActionList/ActionList.test.tsx
- packages/components/src/ActionList/ActionList.tsx
- packages/components/src/ActionList/ActionListContext.tsx
- packages/components/src/ActionList/ActionListHeader/ActionListHeaderColumn.tsx
- packages/components/src/ActionList/utils/useActionListSortManager.tsx
- Changed doSort prop for `ActionList`-related components to onSort
> ActionList: doSort to onSort

- packages/components/src/ActionList/ActionList.test.tsx
- packages/components/src/ActionList/ActionList.tsx
- packages/components/src/ActionList/ActionListCheckbox.test.tsx
- packages/components/src/ActionList/ActionListCheckbox.tsx
- packages/components/src/ActionList/ActionListContext.tsx
- packages/components/src/ActionList/ActionListItem.tsx
- packages/components/src/ActionList/ActionListItemColumn.tsx
- packages/components/src/ActionList/ActionListRow.tsx
- packages/components/src/ActionList/utils/useActionListSortManager.tsx
- packages/components/src/Form/Fields/FieldCheckbox/__snapshots__/FieldCheckbox.test.tsx.snap
- packages/components/src/Form/Inputs/Checkbox/Checkbox.tsx
- packages/components/src/Form/Inputs/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/playground/src/ActionList/ActionListDemo.tsx
> ActionList Select implemented

- packages/components/src/Form/Fields/Field.tsx
- packages/components/src/Form/Fields/FieldSelect/__snapshots__/FieldSelect.test.tsx.snap
- packages/components/src/Form/Fields/FieldText/FieldText.tsx
- packages/components/src/Form/Fields/FieldText/__snapshots__/FieldText.test.tsx.snap
- packages/components/src/Form/Fields/FieldTextArea/FieldTextArea.tsx
- packages/components/src/Form/Fields/FieldTextArea/__snapshots__/FieldTextArea.test.tsx.snap
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Form/Inputs/InputSearch/__snapshots__/InputSearch.test.tsx.snap
- packages/components/src/Form/Inputs/InputText/InputText.tsx
- packages/components/src/Form/Inputs/InputText/__snapshots__/InputText.test.tsx.snap
- packages/components/src/Form/Inputs/Select/Select.tsx
- packages/components/src/Form/Inputs/TextArea/TextArea.tsx
- packages/components/src/Form/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
- packages/components/src/Form/__snapshots__/Form.test.tsx.snap
- packages/playground/src/Form/FieldsDemo.tsx
> update width from InputText

- pull_request_template.md
> Update PR template a smidge

- CHANGELOG.md
> Update CHANGELOG for 0.7.28

- packages/www/src/Layout/Documentation.tsx
- packages/www/src/pages/index.tsx
Update how we import helmet to fix documentation
> Update how we import helmet in documentation

- packages/components/src/PageSize/PageSize.test.tsx
- packages/components/src/PageSize/PageSize.tsx
- Fix PageSize fontSize
- Simplify DOM a smidge
> Fix PageSize fontSize, simplify DOM a smidge

- CHANGELOG.md
> CHANGELOG for 0.7.29

- package.json
- packages/components/src/utils/useScrollLock.ts
- yarn.lock
- Fix `useScrollLock` SSR issue
- Also remove resolution for `sharp` as it no longer appears to be needed
> Fix `useScrollLock` SSR issue

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldCheckboxGroup/FieldCheckboxGroup.tsx
- packages/components/src/Form/Fields/FieldRadioGroup/FieldRadioGroup.tsx
> Update CHANGELOG for 0.7.30

- CHANGELOG.md
> Update CHANGELOG for 0.7.31

- CHANGELOG.md
- packages/components/src/Modal/Confirm/ConfirmLayout.tsx
- packages/components/src/Modal/Layout/ModalHeader.tsx
- packages/components/src/Modal/Layout/__snapshots__/ModalHeader.test.tsx.snap
- packages/components/src/Text/Paragraph.tsx
- packages/playground/src/index.tsx
> confirm update word-wrap

- packages/components/src/Text/text_variant.ts
- packages/components/src/Tooltip/Tooltip.tsx
- packages/design-tokens/src/system/color/specifiable.ts
- packages/design-tokens/src/tokens/color/index.ts
- packages/www/src/MDX/Pre/CodeSandbox.tsx
- packages/www/src/documentation/components/content/avatar.mdx
- packages/www/src/documentation/components/layout/box.mdx
- packages/www/src/documentation/components/layout/flex.mdx
- packages/www/src/documentation/system/color.mdx
- packages/www/src/documentation/system/demos/BorderRender.tsx
- packages/www/src/documentation/system/demos/index.ts
- Remove color docs, switch inverseOn for onInverse
> Remove color docs, switch inverseOn for onInverse

- babel.config.js
- package.json
- Remove unused babel feature / package
> Remove unused babel feature / package

- tsconfig.build.json
- Don't build typings for test files
> Don't build typings for test files

- packages/components/src/Modal/Dialog/Dialog.test.tsx
> Fixed noisy tests on Dialog

- .eslintrc.js
- .stylelintrc.js
- package.json
- packages/eslint-config/README.md
- packages/eslint-config/index.js
- packages/eslint-config/license-header.js
- packages/eslint-config/package.json
- packages/eslint-config/ts-workspaces.js
- packages/eslint-config/tsconfig.build.json
- packages/prettier/README.md
- packages/prettier/index.js
- packages/prettier/index.json
- packages/prettier/package.json
- packages/prettier/tsconfig.build.json
- packages/stylelint-config/README.md
- packages/stylelint-config/index.js
- packages/stylelint-config/package.json
- packages/stylelint-config/tsconfig.build.json
- yarn.lock
Improve ESLint config
- Split header into seperate extendable configuration
- Split ts-workspaces into seperate extendable configuration
- Remove all overrides and integrate directly into eslint-config package
Move ESLint config from package.json to `.eslintrc.js` to prepare for future monorepository membership
Split Stylelint into its own package
> Consolidate tooling configuration into components monorepo

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldCheckbox/__snapshots__/FieldCheckbox.test.tsx.snap
- packages/components/src/Form/Fields/FieldRadio/__snapshots__/FieldRadio.test.tsx.snap
- packages/components/src/Form/Fields/FieldSelect/__snapshots__/FieldSelect.test.tsx.snap
- packages/components/src/Form/Fields/FieldText/__snapshots__/FieldText.test.tsx.snap
- packages/components/src/Form/Fields/FieldTextArea/__snapshots__/FieldTextArea.test.tsx.snap
- packages/components/src/Form/Fields/FieldToggleSwitch/__snapshots__/FieldToggleSwitch.test.tsx.snap
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Form/Label/Label.test.tsx
- packages/components/src/Form/Label/Label.tsx
- packages/components/src/Form/Label/__snapshots__/Label.test.tsx.snap
- packages/components/src/Form/__snapshots__/Form.test.tsx.snap
> Lock down `Label` styles

- CHANGELOG.md
- packages/icons/src/svg/Pivot.svg
> Add pivot icon

- storybook/src/Tree/FieldPicker.stories.tsx
- storybook/src/Tree/Tree.stories.tsx
Better example for FieldPicker
> FieldPicker example

- www/src/documentation/components/dialogs/layout.mdx
- Just documenting `ModalHeader` props
> Document modal header detail

- www/src/documentation/components/content/tabs.mdx
- update documentation, small typo
- porp - prop
> update documentation, small typo

- CHANGELOG.md
- packages/components/src/Dialog/DialogContext.ts
- packages/components/src/Dialog/Layout/DialogContent.tsx
- packages/components/src/Dialog/Layout/DialogFooter.tsx
- packages/components/src/Dialog/Layout/DialogHeader.tsx
- packages/components/src/Portal/Portal.tsx
> Remove aliases to Modal

- CHANGELOG.md
- www/src/documentation/components/forms/fields.mdx
Updates a few typos in the `Field` documentation
> Typos in field documentation

- CHANGELOG.md
- packages/components/src/Tabs/Tabs.tsx
- storybook/src/Tabs.stories.tsx
- www/src/documentation/components/content/tabs.mdx
> update Tab to support hooks

- CHANGELOG.md
- packages/components/src/Link/Link.test.tsx
- packages/components/src/Link/Link.tsx
- packages/components/src/Link/__snapshots__/Link.test.tsx.snap
> Link fixes (don't emit junk to DOM, better tests)

- CHANGELOG.md
- packages/icons/src/svg/AddComment.svg
- packages/icons/src/svg/Comment.svg
- packages/icons/src/svg/Feedback.svg
- [X ] Updated CHANGELOG
- [X ] PR is ideally < ~400LOC
> Adding Icon artwork for AddComment, Comment, and Feedback

- CHANGELOG.md
- packages/components/src/Avatar/Avatar.tsx
- packages/components/src/Avatar/AvatarCombo.tsx
- packages/components/src/Avatar/__snapshots__/Avatar.test.tsx.snap
* Fixed bug around display of `Avatar*` especially `AvatarCombo`
> Fix Avatar styling conflicts with role="button"

- CHANGELOG.md
- packages/components/src/Form/Inputs/Combobox/Combobox.tsx
- packages/components/src/Form/Inputs/Select/Select.test.tsx
- storybook/src/Forms/Select.stories.tsx
- Fixes this bug https://codesandbox.io/s/nifty-smoke-k232p?file=/src/index.tsx
- See storybook example at /?path=/story/forms-select--update-options
> Select: make input value reflect change to option label

- packages/components/src/Tabs/TabPanels.tsx
> TabPanels shouldn't support taking focus

- storybook/.storybook/main.js
- storybook/package.json
- yarn.lock
- Upgrade storybook to latest release
> Storybook 6.0

- www/src/components/Navigation/Navigation.tsx
- www/src/components/Navigation/Page.tsx
- www/src/components/Navigation/Section.tsx
> update style for hover and active

- storybook/src/ButtonOutline.stories.tsx
- storybook/src/ButtonTransparent.stories.tsx
- storybook/src/FieldText.stories.tsx
- www/src/documentation/components/actions/button-group.mdx
- www/src/documentation/components/actions/button-outline.mdx
- www/src/documentation/components/actions/button-toggle.mdx
- www/src/documentation/components/actions/button-transparent.mdx
- www/src/documentation/components/actions/button.mdx
> update storybook to suport prop demos

- www/gatsby-config.js
- www/package.json
- www/src/components/Search.tsx
- yarn.lock
- added `gatsby-plugin-google-analytics`
- added some event tracking in the Search component
> Hack Extract: Gatsby/Google Analytics

- CHANGELOG.md
- packages/components/src/Chip/Chip.test.tsx
- packages/components/src/Chip/Chip.tsx
- storybook/src/Chip.stories.tsx
- Chip supports prefix as props
> Chip supports prefix as props

- package.json
- yarn.lock
- Upgrade node-fetch & node-forge to address vulnerabilities
> Upgrade node-fetch & node-forge to address vulnerabilities

- CHANGELOG.md
- packages/components/src/Dialog/Layout/__snapshots__/DialogFooter.test.tsx.snap
- packages/components/src/Layout/Space/Space.tsx
- packages/components/src/Layout/Space/__snapshots__/Space.test.tsx.snap
> Revert Space flex-shrink: 0

- packages/components/src/ActionList/ActionList.tsx
- packages/components/src/ActionList/ActionListFilters.test.tsx
- packages/components/src/ActionList/ActionListFilters.tsx
- packages/components/src/Form/Inputs/InputFilters/InputFilters.story.tsx
- packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
- packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
- packages/components/src/Form/Inputs/InputFilters/InputFiltersChipEditor.tsx
- storybook/src/ActionList/ActionList.stories.tsx
Some suggestions for https://github.com/looker-open-source/components/pull/1476
* Filter the `Select` as the user types
* Change `InputFilters` to a controlled component (otherwise the changes from the user can't be applied in `ActionList` or wherever else this component may be used
* Simplify the use of `ButtonGroup`
> ActionListFilter / InputFilters suggestions

- CHANGELOG.md
- packages/components/src/Dialog/stories/Dialog.story.tsx
- packages/components/src/Popover/Popover.test.tsx
- packages/components/src/Popover/Popover.tsx
- packages/components/src/Popover/index.ts
- packages/components/src/Popover/usePopover.tsx
- packages/components/src/Popover/usePopoverToggle.tsx
- packages/components/src/Popover/useVerticalSpace.tsx
- Introduce domProps pattern from useDialog
- Break apart Popover into separate files
- Replace `function` keywords with arrow functions
> Popover improvements

- packages/components/src/Menu/Menu.tsx
- packages/components/src/Menu/MenuContext.ts
- packages/components/src/Menu/MenuList.tsx
- www/src/documentation/components/overlays/menu.mdx
> Add groupedMenusRef prop to menu to support better UX in a group of menus

- packages/components/src/Button/ButtonBase.tsx
- packages/components/src/Button/IconButton.tsx
- Fix TS issue that 3.9.x TS makes evident.
> Correct buttonCSS typing

- packages/components/src/ActionList/Column/ItemColumn.tsx
- packages/components/src/__mocks__/DataTable/data.tsx
- update DataTable to eneble links on rows
> Lara/enable link/1330

- packages/components/CHANGELOG.md
- packages/components/src/DataTable/Column/DataTableCell.tsx
- packages/components/src/DataTable/stories/items.tsx
- www/src/documentation/components/content/data-table.mdx
- update DataTableCell to use description for consistency
> update DataTableCell to use description for consistency

- jest-image-snapshots.config.js
- package.json
- packages/components/package.json
- packages/design-tokens/package.json
- packages/storybook-config/package.json
- storybook/package.json
- yarn.lock
- Storybook 6.1 - now with better search (and other stuff)
Image-Snapshots 4x faster!!
> Storybook 6.1

- .github/workflows/ci.yml
> Github Actions for CI

- packages/components/src/Dialog/stories/Dialog.story.tsx
> Fix dialog story

- packages/components/src/Tree/TreeItem.tsx
- packages/components/src/Tree/TreeStyle.tsx
- packages/components/src/Tree/utils/getBackgroundColor.ts
> Tree: getBackgroundColor tweaks

- packages/components/src/Form/Inputs/InputTimeSelect/InputTimeSelect.tsx
> Declare useCallback dependency

- packages/components/src/InputDateRange/InputDateRange.story.tsx
- Fixes lint error in master caused by Menu PR
> Fix Menu in InputDateRange.story

- www/src/MDX/Ol.tsx
- www/src/MDX/Ul.tsx
- www/src/MDX/index.ts
> Fix MDX exports (for circular dependencies PR)

- www/src/pages/index.tsx
> Doc: Fix Getting Started link

- .github/workflows/release-please.yml
> chore: Add release-please action

- .github/workflows/release-drafter.yml
> fix: Correct release-drafter yaml config typo

- www/src/documentation/components/forms/input-filters.mdx
docs: Correct InputFilters example in documentation
> docs: Correct InputFilters example in documentation

- www/src/documentation/components/forms/input-filters.mdx
> docs: Correct mis-spelling in InputFilters

- .github/workflows/canary-release.yml
- .github/workflows/release-pull-request.yml
- .github/workflows/release.yml
Remove Node 10 installation (just use pre-installed Node v12 that works just fine in core `.github/workflows/test.yml`
> chore: Correct mis-configuration with Github Actions setup

- packages/components/src/DataTable/Header/DataTableHeaderCell.tsx
- packages/components/src/DataTable/Item/DataTableRow.tsx
- packages/components/src/DataTable/getNextFocus.ts
- packages/components/src/DataTable/stories/items.tsx
- packages/components/src/Form/Inputs/InputProps.ts
> Updates to DataTable getNextFocus

- package.json
- yarn.lock
> fix(deps): Update dependencies to resolve external vulnerabilities (socket.io & immer)

- .github/workflows/canary.yml
- .github/workflows/release-pull-request.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
> chore(ci): Enable yarn cache restoration on all CI workflows

- packages/components/src/Portal/Portal.tsx
> fix(components): pointer-events style in Dialog

- packages/components/src/Accordion/AccordionDisclosure.tsx
> fix(Accordion): indicator will now follow theme color changes properly

- packages/components/src/DataTable/DataTable.test.tsx
- packages/components/src/DataTable/Item/DataTableItem.tsx
- packages/components/src/DataTable/Item/DataTableRow.tsx
- packages/components/src/DataTable/stories/Interaction.tsx
- packages/components/src/DataTable/stories/Responsive.tsx
- packages/components/src/DataTable/stories/items.tsx
- packages/components/src/DataTable/types.ts
- www/src/documentation/components/content/data-table.mdx
> fix: DataTable Simplify onClick behavior

- packages/components/src/Form/Inputs/InlineInputText/InlineInputText.test.tsx
> fix: InlineInputText updated test coverage

- packages/components/src/ProgressCircular/ProgressCircular.test.tsx
> test(ProgressCircular): Improve test coverage

- packages/components/src/InputDate/InputDate.test.tsx
- packages/components/src/InputDateRange/InputDateRange.story.tsx
- packages/components/src/InputDateRange/InputDateRange.test.tsx
- packages/components/src/InputDateRange/InputDateRange.tsx
> test: InputDateRange tests

- packages/components-providers/src/I18n/resources.ts
- packages/components/src/Avatar/AvatarUser.tsx
- packages/components/src/Calendar/CalendarNav.tsx
- packages/components/src/CopyToClipboard/CopyToClipboard.tsx
- packages/components/src/DataTable/BulkActions/BulkActions.tsx
- packages/components/src/DataTable/Filters/ColumnSelector.tsx
- packages/components/src/DataTable/Item/DataTableItem.tsx
- packages/components/src/DataTable/Table.tsx
- packages/components/src/DataTable/utils/useDataTableSortManager.tsx
- packages/components/src/Dialog/Confirm/ConfirmationDialog.tsx
- packages/components/src/Dialog/Prompt/PromptDialog.tsx
- packages/components/src/Form/Fields/RequiredStar.tsx
- packages/components/src/Form/Inputs/AdvancedInputControls.tsx
- packages/components/src/Form/Inputs/Checkbox/CheckMarkMixed.tsx
- packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
- packages/components/src/Form/Inputs/InputSearch/InputSearch.tsx
- packages/components/src/Form/Inputs/InputText/InputText.tsx
- packages/components/src/Form/Inputs/InputTimeSelect/InputTimeSelect.tsx
- packages/components/src/InputDate/InputDate.tsx
- packages/components/src/MessageBar/MessageBar.tsx
- packages/components/src/Pagination/Pagination.tsx
- packages/components/src/Status/Status.tsx
> feat: components i18n

- packages/components-providers/package.json
- packages/components-providers/src/ExtendComponentsProvider.test.tsx
- packages/components-providers/src/ThemeProvider.test.tsx
- yarn.lock
> test(components-providers): Add coverage for ExtendComponentsProvider and ThemeProvider

- packages/components/src/Breakpoint/Breakpoint.test.tsx
Simple coverage for `Breakpoint` component
> test(Breakpoint): Add basic coverage

- www/gatsby-config.js
- www/src/components/Search.tsx
> docs: Narrow web site search to title-only

- .github/pull_request_template.md
> chore: Update pull-request-template

- packages/components-providers/src/I18n/resources.ts
- packages/components/src/Chip/Chip.tsx
- packages/components/src/Form/Inputs/AdvancedInputControls.tsx
- packages/components/src/Form/Inputs/Combobox/ComboboxInput.tsx
- packages/components/src/Form/Inputs/Combobox/ComboboxMultiInput.tsx
- packages/components/src/Form/Inputs/Combobox/types.ts
- packages/components/src/Form/Inputs/InputChips/InputChips.tsx
- packages/components/src/Form/Inputs/InputChips/InputChipsBase.tsx
- packages/components/src/Form/Inputs/InputSearch/InputSearch.tsx
- packages/components/src/Form/Inputs/Select/SelectMulti.tsx
- packages/components/src/Form/Inputs/Select/SelectOptions.tsx
- www/src/documentation/components/content/chip.mdx
- www/src/documentation/components/forms/input-chips.mdx
- www/src/documentation/components/forms/input-search.mdx
- www/src/documentation/components/forms/select-multi.mdx
> feat: customize icon label for localization

- packages/components/src/DataTable/DataTable.test.tsx
- packages/components/src/DataTable/DataTable.tsx
- packages/components/src/DataTable/Filters/DataTableFilters.test.tsx
- packages/components/src/DataTable/Filters/DataTableFilters.tsx
- packages/components/src/DataTable/stories/Interaction.tsx
- packages/components/src/DataTable/types.ts
> feat(DataTable): Allow filters to be specified by composition rather than complex prop object

- packages/components/src/Button/MultiFunctionButton.tsx
- packages/components/src/CopyToClipboard/CopyToClipboard.tsx
> Child ref setter

- packages/components/src/Menu/MenuHeading.tsx
- packages/components/src/Menu/MenuList.story.tsx
An alternate way to allow menu heading overrides while still keeping HT developers in the happy path
> Menu Heading Styled System

- .github/pull_request_template.md
- CONTRIBUTING.md
Adds contribution guidelines and updates the project’s pull request template.
It should help new contributors be more successful in getting quick and effective reviews as well as help us remember all of the items that go into a successful bug fix or enhancement.
> chore: Contribution guidelines and pull request template update

- .github/pull_request_template.md
- CONTRIBUTING.md
> docs: Use Github-smart links

- .github/pull_request_template.md
- CONTRIBUTING.md
> docs: Fix links to CONTRIBUTING in pull request template

- packages/components/src/Dialog/Dialog.test.tsx
- packages/components/src/Form/Fields/Field.test.tsx
- packages/components/src/Form/Inputs/InputText/InputText.test.tsx
- packages/components/src/Form/Inputs/InputTime/InputTime.tsx
- packages/components/src/Form/Inputs/InputTime/utils.ts
- packages/components/src/Form/Inputs/InputTimeSelect/InputTimeSelect.tsx
This was the by-product of auditing a random things on other PRs and picking up the left-over stashes into a small collection of coverage improvements.
> test: Small collection of miscellaneous test coverage fix-ups

- www/src/documentation/components/content/tabs.mdx
> docs(Tabs): Per user-feedback simplify Tabs documentation to more clearly illustrate common use-cases

- package.json
- yarn.lock
Address Github automated vulnerability warnings for two transient dependencies.
> chore: Patch transient dependency versions

- .github/workflows/codeql-analysis.yml
Introduce CodeQL to see what it can offer: https://codeql.github.com/docs/
> chore: Introduce codeql-analysis

- package.json
- packages/components-providers/src/TrapStack/TrapStackProvider.tsx
- packages/components-providers/src/TrapStack/types.ts
- packages/components-providers/src/TrapStack/utils.ts
- packages/components/src/Avatar/Avatar.test.tsx
- packages/components/src/Avatar/AvatarCombo.story.tsx
- packages/components/src/Avatar/AvatarUser.story.tsx
- packages/components/src/Avatar/AvatarUser.tsx
- packages/components/src/Calendar/Calendar.tsx
- packages/components/src/DataTable/stories/useSortManager.tsx
- packages/components/src/Form/Fields/FieldText/FieldText.story.tsx
- packages/components/src/Form/Inputs/InputTimeSelect/InputTimeSelect.tsx
- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.test.tsx
- packages/components/src/List/ListDivider.tsx
- packages/components/src/Menu/MenuHeading.hooks.ts
- packages/components/src/Panel/Panel.test.tsx
- packages/components/src/Panel/Panel.tsx
- packages/components/src/utils/useTrapStack.ts
- packages/design-tokens/src/system/reset.test.tsx
- packages/eslint-config/index.js
- www/src/MDX/Li.tsx
- www/src/MDX/Ol.tsx
- www/src/MDX/Paragraph.tsx
- www/src/MDX/Ul.tsx
- yarn.lock
16 errors remaining all are of these two types:
> chore: Fix typescript-eslint dependency version and related lint breakages

- packages/components/src/Tree/TreeItem.tsx
- packages/components/src/Tree/stories/FieldPicker.story.tsx
- www/src/MDX/Pre/allComponents.ts
- www/src/documentation/components/content/demos/ListItemPropTable.tsx
- www/src/documentation/components/content/list.mdx
- www/src/documentation/components/content/tree.mdx
**List Documentation Updates**
- Added explanations of `itemRole="none"` and side effects of using said `itemRole`
**Tree Documentation Updates**
- Added notes about `labelBackgroundOnly` prop
- Added notes about `forceLabelPadding` prop
- Added notes about `onClickWhitespace` prop
> docs: Updated Tree and List docs

- packages/components/src/Accordion/Accordion.tsx
> fix(Accordion): Fixed accordion key error when using legacy composition

- packages/components/src/Tree/Tree.test.tsx
- packages/components/src/Tree/Tree.tsx
> fix(Tree): Properly pass down aria roles to nested Accordion

- playground/package.json
- playground/webpack.config.js
- yarn.lock
How to test:
```
yarn checkout luke/playground-fix
yarn
yarn playground
```
> chore(Playground): Correct dependency versions to get `yarn playground` working again

- packages/components/src/Accordion/AccordionDisclosure.tsx
- packages/components/src/Tree/Tree.tsx
- packages/components/src/Tree/TreeStyle.tsx
Suggestion for https://github.com/looker-open-source/components/pull/2295
> feat: TreeStyle/AccordionDisclosure suggestion

- packages/components/src/List/types.ts
> refactor(ListItem): Marked "current" prop as deprecated

- package.json
- yarn.lock
Can I use keeps complaining about an out-of-date database. This fixes that situation.
> chore(deps): Update caniuse

- babel.config.js
- jest.config.js
- storybook/.storybook/main.js
- storybook/package.json
- tsconfig.build.json
Preparation for the filter-components package where story files are named `.stories.tsx`.
> chore: Support .stories files

- apps/playground/package.json
- apps/playground/src/index.tsx
- packages/components-providers/src/FontFaceLoader/FontFaceLoader.test.tsx
- packages/components-providers/src/FontFaceLoader/FontFaceLoader.tsx
> fix(FontFaceLoader): Memoize font-import to prevent font-loading flash

- packages/components/src/Dialog/useDialog.tsx
- packages/components/src/Form/Inputs/Select/Select.test.tsx
- packages/components/src/Overlay/OverlaySurface.tsx
- packages/components/src/Popover/Layout/PopoverHeader/PopoverHeader.story.tsx
- packages/components/src/Popover/Layout/PopoverHeader/PopoverHeader.test.tsx
- packages/components/src/Popover/Layout/PopoverHeader/PopoverHeader.tsx
- packages/components/src/Popover/Layout/PopoverLayout.tsx
- packages/components/src/Popover/Popover.test.tsx
- packages/components/src/Popover/stories/Popover.story.tsx
- packages/components/src/Popover/usePopover.tsx
> feat(Popover): updated aria-labelledby and role for A11Y

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/release.yml
- CODEOWNERS
- Don't run coverage on merge to `main` (not compatible)
- Optimize Storybook snapshot re-shoot
- Clean-up release workflow to remove unused parts
- Add CODEOWNERS
> chore: CI Configuration tweaks

- packages/components/src/Accordion2/useAccordion2.tsx
- packages/components/src/ListItem/ListItemContent.tsx
- packages/components/src/Tree/Tree.tsx
- packages/components/src/Tree/TreeItem.tsx
- packages/components/src/Tree/stories/HoverDisclosure.story.tsx
- packages/components/src/Tree/stories/Tree.story.tsx
- packages/components/src/Tree/utils/getNextTreeFocus.ts
Various changes that allow all (but 2 onClickWhitespace-related) jest tests to pass.
**TODO:** Chase down the `onClickWhitespace` tests
> Various fixes to make jest happy

- packages/components/src/Popover/Layout/PopoverHeader/PopoverHeader.tsx
- packages/components/src/Popover/stories/Popover.story.tsx
> fix(PopoverHeader):  update width for use with Popover

- packages/components/src/Popover/stories/Popover.story.tsx
- packages/components/src/Popover/usePopover.tsx
> fix(usePopover): aria-haspopup updated

- packages/filter-components/package.json
- packages/filter-expressions/package.json
- packages/filter-expressions/src/utils/get_expression_type.ts
Fix main & module fields so they'll work for publishing.
> fix(Filter Packages): main and module fields

- packages/components/src/Tree/TreeCollection.test.tsx
- packages/components/src/Tree/stories/Tree.story.tsx
> test(Tree): Added story and test to cover Tree with detail accessory enabled

- packages/components/src/Form/Inputs/Select/Select.test.tsx
- packages/components/src/Overlay/OverlaySurface.tsx
- packages/components/src/Popover/Popover.test.tsx
- packages/components/src/Popover/usePopover.tsx
> fix(Popover): Screen reader accessibility

- apps/filter-demo/package.json
- packages/filter-components/USAGE.md
- www/package.json
- yarn.lock
Updates USAGE.md to include peer dependencies.
> docs(Filter Components): Add peer dependencies to install instructions

- packages/components/src/Layout/Semantics/Layout/Layout.test.tsx
> test(Layout): Add coverage

- packages/components/src/utils/useScrollLock.test.tsx
Improves coverage mostly with the help of `jest.spyOn`. The changes I made were in `useScrollLock.test` but the file whose coverage I was aiming to improve is `ScrollLock/utils.ts`.
> test(useScrollLock): improve coverage

- packages/components/src/Modal/ModalFooter/ModalFooter.test.tsx
- packages/components/src/Modal/ModalHeader/ModalHeader.test.tsx
- packages/components/src/Modal/ModalLayout/ModalLayout.test.tsx
> test(ModalLayout-ModalHeader-ModalFooter): add covarege

- www/src/Layout/Default.tsx
- www/src/documentation/foundations/color.mdx
- www/src/documentation/foundations/demos/DensityTable.tsx
- www/src/documentation/foundations/demos/index.ts
- www/src/documentation/foundations/density.mdx
First iteration around documenting our current density scale
> docs(Density): Add docs for density

- jest.setup.js
- package.json
- packages/components-date/src/FieldDate/FieldDate.story.tsx
- packages/components/package.json
- packages/components/src/Dialog/Layout/DialogLayout.test.tsx
- packages/components/src/Form/Fields/FieldToggleSwitch/FieldToggleSwitch.test.tsx
- packages/components/src/Modal/ModalLayout/ModalLayout.tsx
- packages/components/src/Popover/Layout/PopoverLayout.story.tsx
- packages/components/src/Popover/Layout/PopoverLayout.test.tsx
- packages/filter-components/src/Filter/Filter.stories.tsx
- storybook/.storybook/componentsDecorator.tsx
- yarn.lock
Adds `@storybook/testing-react` test dependency and leverages it where it's useful.
> test: Introduce @storybook/testing-react

- www/src/documentation/foundations/demos/SpacingOptionsTable.tsx
- www/src/documentation/foundations/spacing.mdx
Fixes a few typos in the spacing docs
> docs: Fix a few small issues with spacing docs

- packages/design-tokens/src/elevation/index.ts
- packages/design-tokens/src/elevation/types.ts
- www/src/documentation/foundations/demos/ElevationList.tsx
- www/src/documentation/foundations/elevation.mdx
Add elevation level `plus0` to match spec
> fix(Elevation): add elevation level of plus0 to match spec

- packages/components/src/NavTree/NavTree.test.tsx
- packages/components/src/NavTree/NavTree.tsx
- packages/components/src/NavTree/index.ts
- packages/components/src/Tree/Tree.tsx
Also minor change to export NavTree types
> fix(NavTree): Made sure NavTree had role="treeitem"

- .envrc
- .gitignore
- shell.nix
> chore: Nix setup

- CHANGELOG.md
- packages/components/CHANGELOG.md
- packages/design-tokens/CHANGELOG.md
Clean-up changelogs and summarize recent releases in top-level changelog
> chore: CHANGELOG clean-ups

- packages/components/src/NavTree/NavTree.story.tsx
- packages/components/src/NavTree/NavTreeItem.test.tsx
- packages/components/src/NavTree/NavTreeItem.tsx
- packages/components/src/Tree/TreeItem.test.tsx
- packages/components/src/Tree/TreeItem.tsx
- Also added additional tests for both TreeItem and NavTreeItem
> fix(TreeItem): Fixed bad link props dispersion bug on TreeItem

- packages/components/src/NavTree/NavTree.story.tsx
- packages/components/src/NavTree/NavTreeItem.test.tsx
- packages/components/src/NavTree/NavTreeItem.tsx
- packages/components/src/Tree/TreeItem.test.tsx
- packages/components/src/Tree/TreeItem.tsx
> fix(TreeItem): Link-related prop dispersion bug

- packages/components/src/List/List.spec.tsx
- packages/components/src/List/List.story.tsx
- packages/components/src/List/List.tsx
- packages/components/src/List/utils/getNextItemFocus.ts
- packages/components/src/List/utils/index.ts
- packages/components/src/Menu/Menu.story.tsx
- packages/components/src/Menu/MenuList.tsx
- packages/components/src/Menu/useNestedMenu.tsx
- packages/components/src/NavList/NavList.spec.tsx
- packages/components/src/NavList/stories/NavList.story.tsx
- packages/components/src/NavTree/NavTree.tsx
- packages/components/src/Tree/TreeCollection.tsx
- packages/components/src/Tree/utils/index.ts
- packages/components/src/utils/useArrowKeyNav.ts
> feat(List): Added dual axis keyboard navigation

- packages/components/src/Form/Inputs/Checkbox/FauxCheckbox.tsx
- packages/components/src/Form/Inputs/Combobox/ComboboxMultiOption.tsx
> fix(SelectOptions): remove Checkbox component

- .github/workflows/ci.yml
- bin/lint-yarn.sh
- package.json
- yarn.lock
- Verify `yarn.lock` status within CI scripts
- Add yarn-deduplicate a devDependency
> test: Add CI check to validate that yarn.lock file reflects latest package.json and has been deduplicated

- www/src/documentation/components/content/tabs.mdx
Addresses https://buganizer.corp.google.com/issues/199538219
> docs(Tabs2): Correct MDX example

- packages/components/src/Link/Link.spec.tsx
- packages/components/src/Link/Link.tsx
https://buganizer.corp.google.com/issues/200619492
> feat(Link): Optionally disabled automatic `rel` additions via `dangerouslyDisableRel` prop

- packages/components/src/Form/Fields/Field/FieldInline.tsx
- packages/components/src/Form/Fields/FieldCheckbox/FieldCheckbox.spec.tsx
- packages/components/src/Form/Fields/FieldToggleSwitch/FieldToggleSwitch.spec.tsx
> fix(FieldInline): Improve accessibility via composition improvements

- packages/components/src/Dialog/Dialog.spec.tsx
- packages/components/src/Dialog/stories/Dialog.stories.tsx
- packages/components/src/Dialog/useDialog.tsx
- packages/components/src/Drawer/stories/Drawer.stories.tsx
- packages/components/src/Panel/usePanel.tsx
- packages/components/src/Tooltip/useTooltip.tsx
- packages/components/src/utils/useAnimationState.ts
- www/src/documentation/components/dialogs/drawer.mdx
- www/src/documentation/components/dialogs/index.mdx
Update Dialog to have a method available before the component opens and after it closes.
> feat(Dialog): add methods onAfterClose and OnAfterOpen

- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.spec.tsx
I missed a `requestAnimationFrame` mock in `RangeSlider.spec.tsx` and this one is causing a TS error in the core prodcut. To be clear, there are still a couple I haven't dealt with yet (there's a ticket), but I don't _think_ those are currently problematic for the source-of-truth move.
> chore: Remove requestAnimationFrame mock in RangeSlider.spec.tsx

- packages/components-data/README.md
- packages/visualization-playground/README.md
- packages/visualizations-adapters/README.md
- packages/visualizations-single-value/README.md
- packages/visualizations-table/README.md
- packages/visualizations-visx/README.md
- packages/visualizations/README.md
Render a deprecation warning on the readme files for the following packages:
- components-data
- visualization-playground
- visualizations-adapters
- visualizations-single-value
- visualizations-table
- visualizations-visx
- visualizations
> Render deprecation warnings on visualization readme files

- packages/components-data/README.md
- packages/visualization-playground/README.md
- packages/visualizations-adapters/README.md
- packages/visualizations-single-value/README.md
- packages/visualizations-table/README.md
- packages/visualizations-visx/README.md
- packages/visualizations/README.md
Reverts looker-open-source/components#3000
> Revert "Render deprecation warnings on visualization readme files"
