looker-open-source/components

- packages/www/src/documentation/components/text/headings.mdx
- packages/www/src/documentation/components/text/text.mdx
- packages/www/src/documentation/getting-started/index.mdx
converts all instances of `textTransform="caps"` to `textTransform="capitalize"`
> Fix text transform examples

- packages/www/src/Layout/SidebarToggle/SidebarToggle.tsx
Sets a sane toggle button default size to prevent this unfortunate position jump that happens on load in production:
> Set default toggle size

- packages/components/src/Form/Fields/FieldToggleSwitch/__snapshots__/FieldToggleSwitch.test.tsx.snap
- packages/components/src/Form/Inputs/ToggleSwitch/ToggleSwitch.tsx
- packages/components/src/Form/Inputs/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
`<div on={true}` causes a React warning. This solution isn't elegant but it works and I couldn't find any better inspiration in https://github.com/styled-components/styled-components/issues/135
The other props like `size` and `disabled` weren't causing breakage but I filtered those as well since they have no place on a `<div/>`.
> Fix on prop bleeding to dom in ToggleSwitch

- packages/www/src/Layout/SidebarToggle/SidebarToggle.tsx
Avoids issue where SidebarToggle is mispositioned when SSR rendering is used and JS hasn't had a chance to do any position calculations
> Use only CSS positioning to place IconButton for SidebarToggle

- packages/components/src/Form/Fields/FieldColor/FieldColor.test.tsx
- packages/components/src/Form/Fields/FieldColor/FieldColor.tsx
- Added `newColor` as an argument to `callOnChange` since using the `color` state is unreliable (state is asynchronous)
- [-] Link(s) to related Github issues
> fix FieldColor onChange

- packages/components/src/Modal/ModalSurface.tsx
- packages/components/src/Overlay/OverlaySurface.tsx
- packages/components/src/Popover/Popover.tsx
- packages/components/src/utils/index.ts
- packages/components/src/utils/useFocusTrap.ts
- `Toolitp` renders `OverlaySurface` but should not engage a focus-trap. In fact it causes a browser-crashing bug when `Tooltip`, `Popover` and another focus-trapping element such as a `Dialog` are in play, causing the blur/focus events get stuck in a loop. So I moved `useFocusTrap` to `Popover` instead.
- No elements are visible when `ModalSurface` mounts so `focus-trap`/`tabbable` can't find anything to focus on. A delay before enabling `useFocusTrap` fixes this.
- [-] Includes test coverage for all changes
- [-] Link(s) to related Github issues
> Fix focus trap issues

- packages/components/src/Menu/MenuGroupLabel.tsx
- packages/components/src/Menu/MenuItem/MenuItem.test.tsx
- packages/components/src/Menu/MenuItem/MenuItem.tsx
- packages/components/src/Menu/MenuItem/MenuItemButton.tsx
- packages/components/src/Menu/MenuItem/MenuItemListItem.tsx
- packages/components/src/Menu/MenuItem/__snapshots__/MenuItem.test.tsx.snap
- packages/components/src/Menu/MenuList.tsx
- packages/components/src/Menu/__snapshots__/MenuGroup.test.tsx.snap
- packages/playground/src/index.tsx
- packages/www/src/documentation/components/overlays/menu.mdx
- Removes use of z-index to enforce menu component stacking order. This is primarily accomplished through working around any need for `position` settings on MenuItem, so it no longer competes with the MenuGroupLabel `position: sticky;` behavior.
> Refactor z-index out of menu components

- packages/components/src/Modal/ModalPortal.tsx
- packages/components/src/utils/useScrollLock.ts
- Fixes an issue where the long contents of `Dialog` cannot be scrolled.
- Made the `allowScrollWithin` argument (a `RefObject`) required in `useScrollLock` – the downsides of not providing this when it's intended are bigger than the possibility of ever wanting to use it without.
- Created a fallback ref in `ModalPortal` to pass to `useScrollLock` if the optional `portalRef` prop is not present.
> Require allowScrollWithin ref on useScrollLock

- CHANGELOG.md
- packages/components/src/Link/Link.tsx
- packages/components/src/Link/__snapshots__/Link.test.tsx.snap
- packages/components/src/Tooltip/Tooltip.test.tsx
- packages/components/src/Tooltip/Tooltip.tsx
- packages/components/src/Tooltip/TooltipContent.tsx
- packages/www/src/documentation/components/overlays/tooltip.mdx
- Update color of `Link` within `Tooltip` to `blue200` to ensure visibility
- Fix issue where `width` property isn't respected
- Remove `maxWidth` property
- Update examples to show use of width, placement and `Link`
> Tooltip Improvements

- CHANGELOG.md
- packages/components/src/Button/Button.test.tsx
- packages/components/src/Button/ButtonOutline.test.tsx
- packages/components/src/Button/ButtonTransparent.test.tsx
- packages/components/src/Button/__snapshots__/Button.test.tsx.snap
- packages/components/src/Button/__snapshots__/ButtonOutline.test.tsx.snap
- packages/components/src/Button/__snapshots__/ButtonTransparent.test.tsx.snap
- packages/components/src/Button/__snapshots__/IconButton.test.tsx.snap
- packages/components/src/Form/Fields/FieldToggleSwitch/__snapshots__/FieldToggleSwitch.test.tsx.snap
- packages/components/src/Form/Inputs/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
- packages/components/src/Layout/Box/__snapshots__/Box.test.tsx.snap
- packages/design-tokens/src/theme.ts
- packages/design-tokens/src/tokens/color/palette.ts
- packages/design-tokens/src/tokens/color/semantic_colors.ts
- Implements the theme changes used in #91 
- Creates new `legacySemanticColors`, `legacyPalette`, and `legacyTheme` to provide the option of maintaining current color settings
> Update theme colors, and copy old values to legacy variables

- CHANGELOG.md
- packages/icons/src/svg/ChangeHistory.svg
Updates the `ChangeHistory` icon
**Before**
**After**
> Fix change history icon

- CHANGELOG.md
- packages/components/src/Overlay/OverlaySurfaceArrow.tsx
- Fix missing border on `OverlaySurfaceArrow`
> Fix missing OverlaySurfaceArrow border

- packages/www/src/documentation/components/text/headings.mdx
- packages/www/src/documentation/components/text/text.mdx
- Use `textAlign` instead of `align`
> Correct usage of textAlign vs. align

- CHANGELOG.md
- packages/components/src/Modal/ModalManager.tsx
- Add `onClose` callback for ModalManager
> Add `onClose` callback for ModalManager

- packages/components/src/Modal/ModalSurface.tsx
- Rolling back `Style.defaultProps.maxWidth` for now since it can't be overwritten (without the use of `!important`) by `surfaceStyles` – the latter can't match the former's media query values.
- In the future, `surfaceStyles` could be updated to support responsive values.
> Simplify ModalSurface maxWidth (& remove minWidth)

- CHANGELOG.md
- packages/components/src/Modal/Dialog/Confirm.test.tsx
- packages/components/src/Modal/Dialog/ConfirmationDialog.tsx
✨ Changes
- updated cancel button color on UseConfirm and Confirm components
✅ Requirements
- [  ] Includes test coverage for all changes
📷 Screenshots
> update cancel button color to neutral

- packages/components/package.json
- packages/design-tokens/package.json
- packages/icons/package.json
- packages/test-utils/package.json
- The es2015 target wasn't actually in use (esm instead) so removing that to accelerate builds
> Remove es2015 package generation

- CHANGELOG.md
- packages/components/src/Form/Inputs/Slider/Slider.tsx
- packages/components/src/Form/Inputs/Slider/__snapshots__/Slider.test.tsx.snap
- packages/playground/src/index.tsx
- packages/www/src/documentation/components/modals/dialog.mdx
- Removes z-index and fixes element ordering so that slider knobs don't obscure modal content
- Fixes url linking between Dialog and Confirm documents
> [LENS-470] Slider stacking and doc fixes

- packages/components/src/Divider/Divider.tsx
- packages/components/src/Divider/__snapshots__/Divider.test.tsx.snap
- packages/components/src/Form/Fieldset/Fieldset.tsx
- packages/components/src/Form/Fieldset/Legend.tsx
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Tabs/Tab.tsx
- packages/components/src/Tabs/__snapshots__/Tabs.test.tsx.snap
- packages/components/src/utils/GlobalStyle.tsx
- Tab (button tag), Divider and Legend should not have borders by default
- Disabled Tab should not have hover behavior
- Refine reset stylesheet a bit
- Snapshot updates
> Refine reset a little bit

- packages/components/src/Modal/Modal.tsx
- packages/playground/src/Confirm/ConfirmDemo.tsx
- packages/playground/src/index.tsx
- add support for a styled system array of widths in the modal typescript definitions
> [LENS-498] Responsive Dialog Widths

- CHANGELOG.md
- `Menu` now supports `hoverDisclosureRef` prop so that `MenuDisclosure` is only shown when the element in question is hovered over.
- `Select` now renders a custom component instead of the native `select`.
- Allows for new features including `isFilterable` / `onFilter` to allow the user to filter through options, and `isClearable` to allow the user to clear out the value.
- Uses experimental `ComboBox` components (more info on this soon!)
- Lots of minor dependency updates (gatsby-\*, typescript, etc.)
- `MenuItem` now supports focusVisible behavior
- `Dialog` / `DialogManager` TS interfaces correct to properly reflect support for responsive sizes
- `Tooltip` will no longer inherit `white-space`, `text-transform` or `word-break` behaviors of the component it uses for positioning …
> 0.7.11 Changelog update

- packages/components/src/Popover/Popover.tsx
Popover uses `window` object without first verifying that it exists. When Gatsby does its build it loads components without a real browser and therefore throws an exeception when trying to run this code.
Added a check to verify that window object exists before attempting to get its innerHeight
> Fix Gatsby build error with Popover

- CHANGELOG.md
- packages/components/src/Menu/MenuList.tsx
- Don't add `aria-labelledby` on `MenuList` if `id` is not found on `MenuContext` (i.e. `MenuList` is used without `Menu`)
> Remove aria-labelledby on MenuList used without Menu

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldSelect/FieldSelect.test.tsx
- packages/components/src/Form/Fields/FieldSelect/__snapshots__/FieldSelect.test.tsx.snap
- packages/components/src/Form/Inputs/Combobox/Combobox.test.tsx
- packages/components/src/Form/Inputs/Combobox/Combobox.tsx
- packages/components/src/Form/Inputs/Combobox/ComboboxContext.ts
- packages/components/src/Form/Inputs/Combobox/ComboboxInput.tsx
- packages/components/src/Form/Inputs/Combobox/helpers.ts
- packages/components/src/Form/Inputs/InputProps.ts
- packages/components/src/Form/Inputs/InputText/InputText.tsx
- packages/components/src/Form/Inputs/Select/Select.tsx
- `autoComplete` wasn't getting passed down b/c we were incorrectly looking for all lowercase `autocomplete` 
- while testing I discovered and fixed a few related issues:
- `autoFocus` had the same issue
- "email" and other valid [HTML5 input types](http://html5doctor.com/html5-forms-input-types/) were not supported on `InputText` or one of our other input components, so I added the types that are similar in appearance to type="text"
- the "no options" message on an empty `Select` was itself behaving like an option
> Fix: InputText autoComplete 

- CHANGELOG.md
- packages/components/src/Modal/Modal.tsx
- packages/components/src/Modal/ModalContext.ts
- packages/components/src/Popover/Popover.tsx
- packages/components/src/utils/useFocusTrap.ts
- packages/playground/src/Select/SelectDemo.tsx
- packages/playground/src/index.tsx
- Fixes an issue where clicking on an option of a `Select` inside a `Dialog` breaks the `Dialog`'s focus trap and blurs the `Select`'s, which prevents the click from registering a change.
> Fix focus trap issue with Select and Dialog

- CHANGELOG.md
- packages/components/src/Modal/Dialog/Dialog.tsx
- packages/components/src/Modal/Modal.tsx
- packages/components/src/Modal/ModalSurface.tsx
- packages/playground/src/Dialog/DialogMaxWidthDemo.tsx
- packages/playground/src/index.tsx
- packages/playground/src/template.html
- packages/www/src/documentation/components/modals/dialog.mdx
-  Adds responsive maxWidth prop support for `ModalSurface` and all consumers
> [LENS-438] Make ModalSurface maxWidth overwrite-able

- CHANGELOG.md
- packages/components/src/Banner/Banner.tsx
- packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
- Use `Box` instead of `Flex` for  `Banner` children so they still get the full available width but don't unintentionally render as a row of columns.
- Add `flexShrink: 0` to the intent icon so it stays at a fixed size.
> Fix: Banner children display

- packages/components/src/Form/Fields/FieldSelect/__snapshots__/FieldSelect.test.tsx.snap
- packages/components/src/Form/Inputs/Combobox/Combobox.tsx
- packages/components/src/Form/Inputs/InputChips/InputChips.tsx
- packages/components/src/Form/Inputs/InputSearch/InputSearch.tsx
- packages/components/src/Form/Inputs/InputSearch/__snapshots__/InputSearch.test.tsx.snap
- packages/www/src/documentation/components/forms/select.mdx
- `InputText` inside of `InputSearch` needs to have width = 100%, otherwise `Select` has issues in a flex row.
- `InputChips` has a different internal layout, so it needs `InputText` to be width = auto.
Issue:
Fixed:
> Fix Select (& InputChips / InputSearch) width issues

- packages/components/src/Form/Inputs/Combobox/state.ts
- packages/playground/src/Select/SelectDemo.tsx
- packages/playground/src/index.tsx
- An integration test in the core product is getting into a state such that this warning occurs `"Unknown action \"SELECT_WITH_CLICK\" for state \"NAVIGATING\""`.
- Though I'm not able to reproduce that state, there's no reason NAVIGATING -> SELECT with click can't be a valid flow, so now it is.
> Fix issue with Select/Combobox integration testing

- CHANGELOG.md
- packages/components/src/Form/Inputs/InputChips/InputChips.test.tsx
- packages/components/src/Form/Inputs/InputChips/InputChips.tsx
- **Added:** When pasting content, `InputChips` doesn't immediately convert to chips
- **Fixed:** And when it does convert to chips (blur, Enter, or next comma typed), it's not trimming values before calling `validate`, resulting in false negatives and weird "growing whitespace" behavior.
Issue:
Fixed:
> InputChips: fixes for pasting

- packages/www/.eslintrc.js
-  Correct bug in Gatsby ESLint configuration that was causing console warnings at Gatsby-boot
> Correct bug in Gatsby ESLint configuration

- CHANGELOG.md
- packages/components/src/Popover/Popover.tsx
- packages/playground/src/Select/SelectDemo.tsx
- packages/playground/src/index.tsx
The root issue was in `usePopover` – when the toggle was a mousedown event, it would open just before the "click outside" listener was able to close any prior popovers (and would also bypass the event.stopPropagation since it was only stopping a click event, not mousedown). If both popovers were inside a `Modal`, the closing popover would re-enable the parent scroll lock, and the one that just opened would be un-scrollable. This specifically affected multiple `Select`s inside a `Modal`.
> Fix: Multiple `Select`s in a `Modal` opened successively break scrolling

- packages/components/src/Calendar/CalendarNav.tsx
- packages/www/src/documentation/components/content/calendar.mdx
- packages/www/src/documentation/components/forms/input-date.mdx
A few small tweaks to InputDate based on @lukelooker's feedback last week.
- Add tooltip describing "view today" button when focusing on the current month label 
- Update documentation headings for clarity, and on-page linking by removing `:` characters 
- Update the "recipe" title to remove reference to filters
> InputDate followup revisions

- CHANGELOG.md
- packages/www/src/documentation/components/actions/button-group.mdx
- packages/www/src/documentation/components/actions/button.mdx
- packages/www/src/documentation/components/content/inline-input-text.mdx
- packages/www/src/documentation/components/forms/input-date.mdx
- packages/www/src/documentation/components/text/paragraph.mdx
- Fixed a few docs pages that had 404 source links
> Fix source links in docs

- packages/components/src/ActionList/ActionListItem.tsx
- packages/components/src/ActionList/ActionListItemActions.tsx
- packages/components/src/Tooltip/Tooltip.tsx
- packages/components/src/utils/useHovered.ts
- packages/playground/src/ActionList/ActionListDemo.tsx
A super rough stab at using pure css to hide/show the action list options menu. This should hopefully simplify the lifecycle and remove the need to coordinate disparate requestAnimationFrame calls.
> Remove requestAnimationFrame dependencies

- CHANGELOG.md
- packages/components/src/Popover/Popover.tsx
- Fixed an issue where the next click after a popover closes is canceled (this should only happen while the popover is open).
**Issue:**
**Fix:**
> Fix usePopover subsequent click issue

- CHANGELOG.md
- packages/components/src/Popover/Popover.tsx
- packages/playground/src/Popovers/Testing.tsx
Background info:
1. `Select` opens (via `usePopopver`) on mousedown
2. This revealed a scroll-lock bug fixed in https://github.com/looker-open-source/components/pull/562
3. The change above caused the following issue, fixed in the current PR:
When an element (modal, another popover, etc) is stacking on top of a popover, a mousedown on this element closes the popover (usually thereby removing the other element as well)
> Fix Popover mousedown issue

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldColor/FieldColor.test.tsx
- packages/components/src/Form/Fields/FieldColor/FieldColor.tsx
- packages/components/src/Form/Fields/FieldColor/Swatch/Swatch.tsx
- packages/components/src/Form/Fields/FieldColor/Swatch/__snapshots__/Swatch.test.tsx.snap
- packages/components/src/Form/Fields/FieldColor/__snapshots__/FieldColor.test.tsx.snap
- packages/playground/src/Form/FieldColorDemo.tsx
- `FieldColor` was not truly controllable – any change to the value prop would not register.
- With these changes, a developer takes control of the state using the `onChange` and `value` props
- Added support for `defaultValue` for when an initial value is needed but the field can still be uncontrolled.
- A demo of the issue: https://codesandbox.io/s/reverent-curran-inmig
**Issue:**
**Fix:**
> Fix controlled FieldColor

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldSelect/__snapshots__/FieldSelect.test.tsx.snap
- packages/components/src/Form/Inputs/Combobox/ComboboxInput.tsx
- packages/icons/src/svg/CaretDown.svg
This PR slightly adjusts the Caret Down Icon, this PR optically centers the icon so it sites better visually where it's used
in black is where the old icon was positioned, the red is where it is optically aligned
> Fix caret down icon

- packages/www/package.json
- yarn.lock
WWW is broken locally in master. When I run `yarn develop:www` gatsby fails to build locally, outputting this error:
```
ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
Can't resolve 'eslint-loader' in '/Users/danielchristopher/Looker/components/packages/www'
File: .cache/caches/gatsby-plugin-mdx/mdx-scopes-dir/687e7dadc0c7d4f63882f41a4f3d9ffc.js
failed Building development bundle - 5.393s
```
I don't know why eslint-loader is suddenly required in our package manifest, but this update resolves the issue for me.;
> Gatsby dev dependency

- packages/components/src/Avatar/AvatarUser.tsx
- packages/components/src/Avatar/__snapshots__/Avatar.test.tsx.snap
- Switching the img for an object tag in AvatarUser will prevent the "broken" image from being shown and will instead simply display nothing if the image fails to load.
> AvatarUser shouldn't show broken image on unavailable avatar

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldCheckbox/FieldCheckbox.test.tsx
- packages/components/src/Form/Fields/FieldCheckbox/__snapshots__/FieldCheckbox.test.tsx.snap
- packages/components/src/Form/Inputs/Checkbox/Checkbox.tsx
- packages/components/src/Form/Inputs/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/www/src/documentation/components/forms/checkbox.mdx
- The `defaultChecked` property serves as a workaround to a bug with using the "checked" prop without an "onChange" prop. Resolves [this JIRA issue](https://looker.atlassian.net/browse/LENS-614).
> Checkbox: Support for "defaultChecked"

- packages/components/src/Form/Inputs/Slider/Slider.tsx
- packages/components/src/Form/Inputs/Slider/__snapshots__/Slider.test.tsx.snap
- packages/playground/src/Slider/SliderDemo.tsx
- packages/www/src/documentation/components/forms/slider.mdx
- Remove Slider's `branded` option
- Small snapshot updates to match
> Remove Slider's branded option

- packages/components/src/Button/IconButton.test.tsx
- packages/components/src/Button/IconButton.tsx
- packages/playground/src/Tooltip/TooltipDemo.tsx
- As of https://github.com/looker-open-source/components/pull/576 we are no longer clobbering `IconButton` event handlers coming from props, which resulted in duplicate tooltips in the core product.
- This update checks if any of the props event handlers matches (via `toString` ??) the event handlers for built-in tooltip to detect an outer tooltip.
**Issue:**
**Fix:**
> Fix duplicate tooltips on IconButton

- packages/components/src/Modal/ModalPortal.tsx
- packages/components/src/Modal/ModalSurface.tsx
- packages/playground/src/Menu/MenuDemo.tsx
- packages/playground/src/index.tsx
- If a `Modal` opens without any tabbable elements, the containing div itself should receive focus as a fallback (often this occurs as when the UI loads data from an API)
- This functionality was lost when I moved the focus trap target to during an overhaul of focus trap & scroll lock
- The issue is evident in the core product where an icon shown only on hover & focus opens a modal that initially has no buttons (while data loads). Focus remains on the icon when it should move to the modal container.
**Issue:**
**Fix:**
> Fix focus trap for modal's with no tabbable element

- packages/components/src/Tabs/TabPanels.tsx
- packages/playground/src/Tabs/TabsDemo.tsx
- packages/playground/src/index.tsx
- Added FlexboxProps and Layout Props to `TabPanels` component
- **Use case:** There are times where you want the contents of TabPanel to take up whatever space is left in a surrounding flex container. Adding these props means that `TabPanels` will take up all remaining space in a flex container using "height: 100%" or "flex: 1".
- **Note:** Also added TabsDemo to demonstrate a "flex container surrounding a Tabs element scenario".
> TabPanels: Added FlexboxProps and LayoutProps

- CHANGELOG.md
- packages/icons/src/svg/ArrowDown.svg
- packages/icons/src/svg/ArrowDropDown.svg
- packages/icons/src/svg/ArrowDropUp.svg
- packages/icons/src/svg/ArrowLeft.svg
- packages/icons/src/svg/ArrowUp.svg
- packages/playground/src/ActionList/ActionListDemo.tsx
- packages/playground/src/Popovers/ContentOverflow.tsx
- packages/playground/src/Popovers/EdgeOverflow.tsx
This PR adds an icon `ArrowLeft` as well as it renames `ArrowDropDown` and `ArrowDropUp` Icon's to be more consistent to `ArrowDown` and `ArrowUp`
> Arrow icon updates

- packages/components/src/Button/ButtonOutline.tsx
- packages/components/src/Button/__snapshots__/ButtonOutline.test.tsx.snap
- Bug in usage of semanticColors in ButtonOutline caused an issue where the underlying HTML element could influence the rendering. 0
- Properly referencing semanticColor structure corrects this bug.
Before:
After
> Correct ButtonOutline inferred background color

- packages/components/src/Form/Inputs/Combobox/Combobox.test.tsx
- packages/components/src/Form/Inputs/Combobox/ComboboxOption.tsx
- packages/playground/src/index.tsx
- `ComboboxOption` should not highlight the input value if the input value is showing the currently selected option.
- This was happening when, e.g. the currently selected option was "Hour", and the "hour" text in the other options was being highlighted: "2 **hour**s",  "4 **hour**s", etc.
**Issue:**
**Fixed:**
> Fix ComboboxOption highlighting

- CHANGELOG.md
- packages/components/src/Modal/Dialog/ConfirmLayout.tsx
- packages/components/src/Modal/Layout/ModalHeader.test.tsx
- packages/components/src/Modal/Layout/ModalHeader.tsx
- packages/components/src/Modal/Layout/__snapshots__/ModalHeader.test.tsx.snap
- Confirm no longer includes "Close" icon in header
- ModalHeader - allow hiding of Dialog closing IconButton (hideClose)
> Confirm no longer includes "Close" icon in header

- packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
- packages/components/src/Button/Button.test.tsx
- packages/components/src/Button/__snapshots__/Button.test.tsx.snap
- packages/components/src/Button/__snapshots__/ButtonOutline.test.tsx.snap
- packages/components/src/Button/__snapshots__/ButtonTransparent.test.tsx.snap
- packages/components/src/Button/__snapshots__/IconButton.test.tsx.snap
- packages/components/src/Button/icon.ts
- packages/components/src/Modal/Layout/__snapshots__/ModalHeader.test.tsx.snap
This PR updates how icons are sized in `Button` before the icon was the same at all `Button` sizes. With this PR we scale the icon size based on the size of the `Button`
**Before**
Here is before where all the icons render at 16px
**After**
Now the icon scales with the button, most noticeable in `xsmall` and `large` sizes
> Scale icon size in Button

- CHANGELOG.md
- packages/components/src/Overlay/OverlaySurface.tsx
- packages/components/src/utils/usePopper.ts
- packages/playground/src/index.tsx
- PopperJS 2.0 isn't behaving well with `placement: 'top'` (whether set or as a result of "flipping") and an anchor element whose "offset parent" is the window itself.
- I couldn't quite pin down why this was happening but I think it has something to do with PopperJS expecting the `bottom:0` to be the bottom of the page but it's actually the bottom of the window.
- Setting the `adaptive` option to false in `computeStyles` fixes the issue because then it uses only `top` and `left` properties which are more reliable.
- You won't see this issue in components.looker.com because the scrolling content section prevents it from happening, but you can see it in the playground (on master) as demonstrated by this screen capture:
**Fixed:**
> Fix usePopper top placement with window "offset parent"

- packages/www/src/documentation/components/actions/demos/Button.tsx
- Gatsby is weird. Removing theme usage within it for now.
> Remove accidental theme-bleed in Gatsby

- packages/components/src/Form/Fields/FieldCheckbox/__snapshots__/FieldCheckbox.test.tsx.snap
- packages/components/src/Form/Inputs/Checkbox/Checkbox.test.tsx
- packages/components/src/Form/Inputs/Checkbox/Checkbox.tsx
- packages/components/src/Form/Inputs/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/playground/src/Checkbox/CheckboxDemo.tsx
- packages/playground/src/Checkbox/MixedStateCheckboxDemo.tsx
This PR updates checkbox state to allow defaultChecked to behave more like the standard html element. The checkbox will initially display as checked, but it will allow you to toggle the state without an onchange handler
> [LENS-670] Fix Checkbox defaultChecked behavior

- CHANGELOG.md
- packages/components/src/Form/Inputs/Combobox/ComboboxInput.tsx
- Fix BTOA-related bug
- Update CHANGELOG for 0.7.27
> Only use BTOA library if window is not available

- packages/components/src/Form/Inputs/InlineInputText/InlineInputText.tsx
- packages/components/src/Form/Inputs/InlineInputText/__snapshots__/InlineInputText.test.tsx.snap
-  update InlineInputText to have the correct import path for pick
> update InlineInputText to have the correct import path for pick

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldCheckbox/__snapshots__/FieldCheckbox.test.tsx.snap
- packages/components/src/Form/Fields/FieldInline.tsx
- packages/components/src/Form/Fields/FieldRadio/__snapshots__/FieldRadio.test.tsx.snap
- packages/components/src/Form/Fields/FieldToggleSwitch/__snapshots__/FieldToggleSwitch.test.tsx.snap
- removed labelFontWeight from FieldInline 
- update test for it
> removed labelFontWeight from FieldInline and update test for it

- CHANGELOG.md
- packages/components/src/Form/Inputs/Select/Select.test.tsx
- packages/components/src/Form/Inputs/Select/SelectOptions.tsx
- packages/components/src/Form/Inputs/Select/utils/options.ts
- packages/playground/src/Select/SelectDemo.tsx
- packages/playground/src/Select/SelectMultiDemo.tsx
- packages/www/src/documentation/components/forms/select.mdx
- Renamed option group `title` to `label` (closer to [HTML spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup), audit of core product shows it's not being used yet) and made it optional
- Added dividers between groups, per design spec:
> Group options within Select component without titles

- packages/components/src/Button/ButtonBase.tsx
- packages/components/src/Form/Fields/Field.tsx
- packages/components/src/Form/Fields/FieldColor/Swatch/Swatch.tsx
- packages/components/src/Form/Fields/FieldInline.tsx
- packages/components/src/Form/Fields/FieldSelect/__snapshots__/FieldSelect.test.tsx.snap
- packages/components/src/Form/Fields/FieldText/__snapshots__/FieldText.test.tsx.snap
- packages/components/src/Form/Fields/FieldTextArea/__snapshots__/FieldTextArea.test.tsx.snap
- packages/components/src/Form/Fields/FieldToggleSwitch/__snapshots__/FieldToggleSwitch.test.tsx.snap
- packages/components/src/Form/Fields/RequiredStar.tsx
- packages/components/src/Form/Fieldset/Legend.tsx
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Form/Inputs/InputDateRange/InputDateRange.tsx
- packages/components/src/Form/Inputs/InputSearch/InputSearch.tsx
- packages/components/src/Form/Inputs/InputSearch/__snapshots__/InputSearch.test.tsx.snap
- packages/components/src/Form/Inputs/InputText/InputText.tsx
- packages/components/src/Form/Inputs/InputText/__snapshots__/InputText.test.tsx.snap
- packages/components/src/Form/Inputs/InputTime/InputTime.tsx
- packages/components/src/Form/Inputs/Select/Select.tsx
- packages/components/src/Form/Inputs/Select/SelectMulti.tsx
- packages/components/src/Form/Inputs/ToggleSwitch/Knob.tsx
- packages/components/src/Form/Inputs/ToggleSwitch/ToggleSwitch.tsx
- packages/components/src/Form/Inputs/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
- packages/components/src/Form/Label/Label.tsx
- packages/components/src/Form/__snapshots__/Form.test.tsx.snap
- packages/components/src/Modal/ModalPortal.tsx
- packages/playground/src/Form/FieldsDemo.tsx
- Removing support for `Customizable*` overrides in preparation for improved theming flexibility.
- [-] Update documentation
> Deprecate customizable input attribute support

- CHANGELOG.md
- packages/components/src/Menu/Menu.test.tsx
- packages/components/src/Menu/MenuItem/MenuItem.tsx
- packages/www/src/documentation/components/overlays/menu.mdx
- Close `Menu` in `MenuItem`'s click handler
- Remove test and docs example that implement `useContext(ModalContext)` since it's built-in now
- Add test for on-click close
- Add note in docs that items intended to mount after `MenuItem` is clicked should not be nested inside `MenuList`
> Close Menu on MenuItem click

- CHANGELOG.md
- packages/components/src/ActionList/ActionList.test.tsx
- packages/components/src/ActionList/ActionListItem.tsx
- packages/components/src/ActionList/ActionListItemColumn.tsx
- `ActionListItem` no longer has `cursor: pointer` or a visible shadow when an `onClick` prop isn't passed in.
- Unrelated fix: `ActionListItemColumn` stays aligned with header columns by moving `overflow: hidden` out of the inner layout and into the main `ActionListItemColumn` div's css.
> Fix "ActionListItem without onClick has shadow" bug

- CHANGELOG.md
- packages/components/src/utils/useScrollLock.ts
- packages/playground/src/Popovers/Testing.tsx
- packages/playground/src/index.tsx
- `useScrollLock` wasn't using `overflow: hidden` on `body` because often some other ancestor (or potentially multiple ancestors) of the trigger element is/are scrollable, so instead it simply cancels the window scroll event.
- However, there was still a "jitter" effect on attempted scroll, which adding `overflow: hidden` on `body` resolves, at least when the scrolling element is, in fact, the `body`.
I![scroll-lock](https://user-images.githubusercontent.com/53451193/80173772-a9050d00-85a5-11ea-800b-54853dbe4e0d.gif)
> Add body overflow hidden to useScrollLock

- packages/components/src/ActionList/ActionListManager.tsx
Per designer specification the "empty state" should sit approximately where the first item would appear.
- Change default height of ActionListManager for better empty state behavior
Before
After
> Change default height of ActionListManager for better empty state behavior

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldBase.tsx
- packages/components/src/Form/Fields/FieldRadio/__snapshots__/FieldRadio.test.tsx.snap
- packages/components/src/Form/Inputs/Radio/FauxRadio.tsx
- packages/components/src/Form/Inputs/Radio/Radio.test.tsx
- packages/components/src/Form/Inputs/Radio/Radio.tsx
- packages/components/src/Form/Inputs/Radio/__snapshots__/Radio.test.tsx.snap
- packages/www/src/documentation/components/forms/radio.mdx
- Remove readOnly prop on Radio
> Remove readOnly prop on Radio

- CHANGELOG.md
- packages/www/src/MDX/Pre/CodeSandbox.tsx
UX Improvement to make it easier to use keyboard navigation in the www components website. Tabbing will now skip over live code editors.
> WWW: Remove tabIndex from live code editor

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldToggleSwitch/__snapshots__/FieldToggleSwitch.test.tsx.snap
- packages/components/src/Form/Inputs/ToggleSwitch/Knob.tsx
- packages/components/src/Form/Inputs/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
- After a [recent change](https://github.com/looker-open-source/components/pull/802), `Knob` in `ToggleSwitch` is passing `on` down to a `div`, causing a React warning
- Changed/reverted `Knob` to only pass down `className`
> Fix ToggleSwitch React warning

- CHANGELOG.md
- packages/components/src/Form/Inputs/InlineInputText/InlineInputText.test.tsx
- packages/components/src/Form/Inputs/InlineInputText/InlineInputText.tsx
- packages/components/src/Form/Inputs/InlineInputText/__snapshots__/InlineInputText.test.tsx.snap
- packages/playground/src/InlineInputText/InlineInputTextDemo.tsx
- packages/playground/src/index.tsx
- packages/www/src/documentation/components/forms/inline-input-text.mdx
- add placeholder attribute to InlineInputText
> Lara/inline input text placeholder/lens677

- CHANGELOG.md
- packages/icons/src/svg/ViewColumn.svg
- [ X ] Updated CHANGELOG
- [ X ] PR is ideally < ~400LOC
> Updated ViewColumn icon to better match keyline and guides

- CHANGELOG.md
- packages/components/src/ActionList/ActionListItemAction.tsx
- packages/playground/src/ActionList/ActionListDemo.tsx
We previously added a minor `color` prop to `ActionListItemAction` that could accept the string "danger". Doing so would make the text of the `ActionListItemAction` red.
This was done to support a use case in helltool, but this functionality is no longer needed by the original requesters. 
- Removed color prop from `ActionListItemAction`
> Action List Item Action: Remove color prop

- CHANGELOG.md
- packages/components/src/Button/ButtonItem.tsx
- packages/components/src/Form/Fields/FieldCheckbox/FieldCheckbox.tsx
- packages/components/src/Form/Fields/FieldCheckbox/__snapshots__/FieldCheckbox.test.tsx.snap
- packages/components/src/Form/Fields/FieldCheckboxGroup/FieldCheckboxGroup.tsx
- packages/components/src/Form/Fields/FieldInline.tsx
- packages/components/src/Form/Fields/FieldRadio/FieldRadio.tsx
- packages/components/src/Form/Fields/FieldRadio/__snapshots__/FieldRadio.test.tsx.snap
- packages/components/src/Form/Fields/FieldRadioGroup/FieldRadioGroup.tsx
- packages/components/src/Form/Fields/FieldSelect/FieldSelect.tsx
- packages/components/src/Form/Fields/FieldText/FieldText.tsx
- packages/components/src/Form/Fields/FieldTextArea/FieldTextArea.tsx
- packages/components/src/Form/Fields/FieldToggleSwitch/FieldToggleSwitch.tsx
- packages/components/src/Form/Fields/FieldToggleSwitch/__snapshots__/FieldToggleSwitch.test.tsx.snap
- Add `for` attribute to labels in `FieldInline` and `ButtonItem` (core product CI can't find custom-styled inputs without it)
- Convert `id = uuid()` to `id = useID` for consistent value over re-renders (see screenshot below)
> Label for attribute

- CHANGELOG.md
- packages/components/src/Form/Fields/Field.tsx
- packages/components/src/Form/Fields/FieldCheckbox/__snapshots__/FieldCheckbox.test.tsx.snap
- packages/components/src/Form/Fields/FieldInline.tsx
- packages/components/src/Form/Fields/FieldRadio/__snapshots__/FieldRadio.test.tsx.snap
- packages/components/src/Form/Fields/FieldSelect/__snapshots__/FieldSelect.test.tsx.snap
- packages/components/src/Form/Fields/FieldText/__snapshots__/FieldText.test.tsx.snap
- packages/components/src/Form/Fields/FieldTextArea/__snapshots__/FieldTextArea.test.tsx.snap
- packages/components/src/Form/Fields/FieldToggleSwitch/__snapshots__/FieldToggleSwitch.test.tsx.snap
- packages/components/src/Form/Fieldset/Fieldset.tsx
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Form/Inputs/Checkbox/Checkbox.tsx
- packages/components/src/Form/Inputs/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/components/src/Form/Inputs/Radio/Radio.tsx
- packages/components/src/Form/Inputs/Radio/__snapshots__/Radio.test.tsx.snap
- packages/components/src/Form/__snapshots__/Form.test.tsx.snap
- packages/playground/src/index.tsx
- packages/www/src/MDX/Pre/CodeSandbox.tsx
- packages/www/src/documentation/components/forms/fields.mdx
This PR is to address a bug in the spacing of our some of our form controls. A style set on our live editor was setting the line height to `1.5rem` that style was cascading to our form controls, introducing incorrect spacing. 
This PR moves the extra line spacing to just the interactive code editor, instead of the wrapper around the preview and code editor. It also sets explicit line heights on our fields so that external line-heights do not introduce the incorrect spacing.
---
Here is a few examples, notice extra spacing between label and text input, misalignment of checkbox/radios 
---
> Update spacing on fields to be more explicit 

- packages/www/src/documentation/components/forms/demos/FormValidationDemo.tsx
- Labels were mixed up in documentation...
Before: 
After:
> Correct labels in example (flipped)

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldCheckbox/__snapshots__/FieldCheckbox.test.tsx.snap
- packages/components/src/Form/Fields/FieldInline.tsx
- packages/components/src/Form/Fields/FieldRadio/__snapshots__/FieldRadio.test.tsx.snap
- packages/components/src/Form/Fields/FieldToggleSwitch/__snapshots__/FieldToggleSwitch.test.tsx.snap
- `htmlFor` was on the nested `<Label as="span">` instead of the outer `<label>` – which is where it is now.
> Move htmlFor to correct label in FieldInline

- CHANGELOG.md
- packages/components/src/Button/IconButton.tsx
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Form/Inputs/InputTime/InputTime.tsx
- packages/components/src/Form/Inputs/InputTimeSelect/InputTimeSelect.tsx
- packages/components/src/Form/__snapshots__/Form.test.tsx.snap
- packages/components/src/Layout/Space/Space.test.tsx
- packages/components/src/Layout/Space/Space.tsx
- packages/components/src/Layout/Space/SpaceVertical.tsx
- packages/components/src/Layout/Space/__snapshots__/Space.test.tsx.snap
- packages/components/src/Layout/Space/__snapshots__/SpaceVertical.test.tsx.snap
- packages/www/src/documentation/components/actions/button.mdx
- packages/www/src/documentation/components/actions/icon-button.mdx
- packages/www/src/documentation/components/content/banner.mdx
- packages/www/src/documentation/components/content/card.mdx
- packages/www/src/documentation/components/content/divider.mdx
- packages/www/src/documentation/components/forms/checkbox.mdx
- packages/www/src/documentation/components/forms/input-date-range.mdx
- packages/www/src/documentation/components/forms/input-date.mdx
- packages/www/src/documentation/components/forms/input-time-select.mdx
- packages/www/src/documentation/components/forms/input-time.mdx
- packages/www/src/documentation/components/forms/range-slider.mdx
- packages/www/src/documentation/components/forms/select-multi.mdx
- packages/www/src/documentation/components/forms/select.mdx
- packages/www/src/documentation/components/layout/space.mdx
- packages/www/src/documentation/components/overlays/menu.mdx
- packages/www/src/documentation/components/overlays/popover.mdx
- packages/www/src/documentation/getting-started/data-fetching.mdx
- packages/www/src/documentation/getting-started/theme.mdx
- Fix Space issue w/ IconButton 
- Add around, between & evenly support to Space
- Use `Space` for IconButton and Button documentation (POC of fixes)
> Fix Space issue w/ IconButton and add around, between & evenly support

- packages/www/src/documentation/components/forms/select.mdx
- "virtualizerd" to "virtualized'
> Fix typo on Select documentation

- .vscode/settings.json
- CHANGELOG.md
- packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
- packages/components/src/Button/ButtonGroup.tsx
- packages/components/src/Button/ButtonItem.tsx
- packages/components/src/Button/ButtonSet.tsx
- packages/components/src/Button/ButtonToggle.test.tsx
- packages/components/src/Button/ButtonToggle.tsx
- packages/design-tokens/src/system/space.ts
- packages/design-tokens/src/tokens/space.ts
- packages/playground/src/Actions/ButtonSetDemo.tsx
- packages/playground/src/index.tsx
- packages/www/src/documentation/components/actions/button-group.mdx
- Minor changes to css in `ButtonGroup`, `ButtonToggle` and `ButtonSet` (the common component they share) to allow wrapping.
- To see it in action, go to http://localhost:8000/components/actions/button-group/ and copy/paste the last item a bunch of times.
> Support wrapping in ButtonGroup/Toggle

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldTime/FieldTime.tsx
- packages/components/src/Form/Inputs/InputTime/InputTime.tsx
> update FiedTime width

- CHANGELOG.md
- packages/components/src/Form/Inputs/InlineInputText/InlineInputText.tsx
- packages/components/src/Form/Inputs/InlineInputText/__snapshots__/InlineInputText.test.tsx.snap
- InlineInputText no longer collapses when value is empty
> InlineInputText no longer collapses when value is empty

- CHANGELOG.md
- packages/components/src/Button/IconButton.test.tsx
- packages/components/src/Calendar/CalendarNav.tsx
- packages/components/src/Tooltip/Tooltip.test.tsx
- packages/components/src/Tooltip/Tooltip.tsx
- packages/playground/src/Tooltip/TooltipDemo.tsx
- packages/playground/src/index.tsx
- packages/www/src/MDX/Pre/CodeSandbox.tsx
- packages/www/src/documentation/components/actions/icon-button.mdx
- packages/www/src/documentation/components/overlays/popover.mdx
- packages/www/src/documentation/components/overlays/tooltip.mdx
- Changelog for 0.7.32
- Render-props free version of Tooltip!
> RenderProps-free Tooltip (and 0.7.32 changelog)

- packages/components/src/Form/Inputs/InputSearch/InputSearch.test.tsx
- packages/components/src/Form/Inputs/InputSearch/InputSearch.tsx
- Re-introduce forwardRef for InputSearch
- ref assignment for InputSearch is required by one integration point with the CORE product to dynamic reassignment of focus.
- In general we should try to make sure all Input* components support ref assignment
> Re-introduce forwardRef for InputSearch

- README.md
- babel.config.js
- package.json
- packages/components/package.json
- packages/components/src/Form/Inputs/OptionsGroup/CheckboxGroup.test.tsx
- packages/components/src/Form/Inputs/OptionsGroup/RadioGroup.test.tsx
- packages/components/src/Tooltip/Tooltip.tsx
- packages/design-tokens/package.json
- packages/icons/package.json
- packages/playground/package.json
- packages/playground/src/Form/OptionsGroupDemo.tsx
- packages/providers/package.json
- packages/test-utils/package.json
- packages/www/package.json
- yarn.lock
- Added `yarn release` to pre-build packages
- Reconfigured babel build a bit to properly build packages for external consumption
- Correct `lodash` imports to not cause a global lodash/underscore collision in consumers
> Publishing fixes

- CHANGELOG.md
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Form/__snapshots__/Form.test.tsx.snap
- packages/components/src/Layout/Space/Space.tsx
- packages/components/src/Layout/Space/SpaceVertical.tsx
- packages/components/src/Layout/Space/__snapshots__/Space.test.tsx.snap
- packages/components/src/Layout/Space/__snapshots__/SpaceVertical.test.tsx.snap
- `Space` & `SpaceVertical` default to 100% width of their container again
> `Space` & `SpaceVertical` default to 100% width of their container again

- packages/www/src/documentation/components/forms/text-area.mdx
- Update TextArea documentation to reflect removal of `both` & `horizontal` support
> Update TextArea documentation to reflect removal of `both` & `horizontal` support

- CHANGELOG.md
- packages/components/src/Form/Inputs/InlineInputText/InlineInputText.tsx
- packages/components/src/Form/Inputs/InlineInputText/__snapshots__/InlineInputText.test.tsx.snap
- packages/playground/src/index.tsx
- `InlineInputText` prop simple removes border-bottom
> InlineInputText simple prop updated

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldTextArea/__snapshots__/FieldTextArea.test.tsx.snap
- packages/components/src/Form/Inputs/TextArea/TextArea.tsx
- packages/components/src/Form/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
- TextArea has min-height as defaultProps
> TextArea has min-height as defaultProps

- CHANGELOG.md
- packages/components/src/Form/Inputs/InlineInputText/InlineInputText.tsx
- packages/components/src/Form/Inputs/InlineInputText/__snapshots__/InlineInputText.test.tsx.snap
- packages/components/src/Form/Inputs/InlineTextArea/InlineTextArea.tsx
- packages/playground/src/index.tsx
- `InlineInputText` has color inherit from parent
> InlineInputText has color inherit from parent

- CHANGELOG.md
- packages/components/src/Form/Inputs/InlineInputText/InlineInputText.tsx
- packages/components/src/Form/Inputs/InlineInputText/__snapshots__/InlineInputText.test.tsx.snap
- Prevent InlineInputText collapse without special character
> Prevent InlineInputText collapse without special character

- packages/components/src/Form/Fields/FieldSelect/__snapshots__/FieldSelect.test.tsx.snap
- packages/components/src/Form/Fields/FieldText/__snapshots__/FieldText.test.tsx.snap
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Form/Inputs/InputSearch/__snapshots__/InputSearch.test.tsx.snap
- packages/components/src/Form/Inputs/InputText/InputText.tsx
- packages/components/src/Form/Inputs/InputText/__snapshots__/InputText.test.tsx.snap
- packages/components/src/Form/__snapshots__/Form.test.tsx.snap
- InputText fix for Firefox
- This still leaves minor breakage in place for narrow InputText fields (and it's derivatives) that have an associated Icon (see screenshot) but addresses the core breakage.
> InputText fix for Firefox

- CHANGELOG.md
- packages/components/src/Tooltip/Tooltip.tsx
- packages/components/src/Tooltip/TooltipContent.tsx
- packages/design-tokens/src/index.ts
- packages/design-tokens/src/theme.ts
- packages/design-tokens/src/tokens/color/index.ts
- Leverage theme slots for background, type and link colors
> `Tooltip` uses theme slots for background, type and link

- CHANGELOG.md
- packages/components/src/Form/Inputs/InputDate/InputDate.tsx
- Fixes a bug where `InputDate` would always render the current month regardless of what the value prop was set to. It worked correctly for `defaultValue`
> InputDate: Render correct month for value prop

- CHANGELOG.md
- packages/components/src/MessageBar/MessageBar.tsx
- packages/design-tokens/src/index.ts
- MessageBar should passthrough DOM properties
> MessageBar should passthrough DOM properties

- CHANGELOG.md
- packages/components/src/Form/Inputs/InlineInputText/InlineInputText.tsx
- packages/components/src/Form/Inputs/InlineInputText/__snapshots__/InlineInputText.test.tsx.snap
- `InlineInputText` now correctly renders underlying text and not absorbing `text-align` from parent element
> `InlineInputText` now correctly renders underlying text

- packages/components/src/Modal/Layout/ModalHeader.test.tsx
- packages/components/src/Modal/Layout/ModalHeader.tsx
- packages/components/src/Modal/Layout/__snapshots__/ModalHeader.test.tsx.snap
- ModalHeader now properly passes through DOM properties (`id`, `aria-label`, etc...)
> ModalHeader now properly passes through DOM properties

- CHANGELOG.md
- packages/components/src/Tooltip/Tooltip.tsx
- packages/playground/src/index.tsx
- Tooltip now appends the hover class onto the child's className prop rather than replacing it
Code for Screenshot above:
```
<Tooltip
width="20rem"
placement="right"
textAlign="left"
content={
<>
This is a tooltip with quite a bit of text. It's probably not ideal
to have this much text in a Tooltip. Perhaps you should link to
another document
</>
}
>
<ButtonOutline>Tooltip with lots of text</ButtonOutline>
</Tooltip>
<Tooltip
width="20rem"
placement="right"
textAlign="left"
content={
<>
This is a tooltip with quite a bit of text. It's probably not ideal
to have this much text in a Tooltip. Perhaps you should link to
another document
</>
}
>
<ButtonOutline className="hover">
Tooltip with lots of text
</ButtonOutline>
</Tooltip>
```
> Fixed child class replacement bug

- CHANGELOG.md
- packages/components/src/Form/Inputs/InputTime/InputTime.tsx
- playground/src/index.tsx
- `InputTime` now renders warning icon when validationType="error" is passed
> updating InputTime to have Warning Icon when ValidationType=error

- CHANGELOG.md
- packages/components/src/Button/ButtonSet.tsx
- packages/components/src/Button/__snapshots__/ButtonGroup.test.tsx.snap
- packages/components/src/Button/__snapshots__/ButtonToggle.test.tsx.snap
- A last-minute change on my previous `ButtonGroup` PR broke the row spacing
> Fix ButtonGroup row spacing when wrapping

- CHANGELOG.md
- packages/components/src/Form/Inputs/Combobox/ComboboxOption.tsx
- Explicitly set the `ComboboxOption` checkmark icon size to 1rem (this was the default before tshirt sizing was added)
> Fix ComboboxOption checkmark size

- CHANGELOG.md
- packages/components-providers/src/ComponentsProvider.tsx
- packages/components/src/Layout/Box/__snapshots__/Box.test.tsx.snap
- storybook/src/Theme/Font.stories.tsx
- Corrects a bug ComponentsProvider where the passed in theme was ignored
- Adds Storybook example (`/?path=/story/theme--font`)
- Also adds additional font support for i18n characters to our default font-stack
> Corrects a bug ComponentsProvider where the passed in theme was ignored

- packages/components/src/Badge/Badge.tsx
- packages/components/src/Button/IconButton.tsx
- packages/components/src/Form/Fields/Field.tsx
- packages/components/src/Form/Fields/FieldBase.tsx
- packages/components/src/Form/Fields/FieldCheckbox/__snapshots__/FieldCheckbox.test.tsx.snap
- packages/components/src/Form/Fields/FieldInline.tsx
- packages/components/src/Form/Fields/FieldRadio/FieldRadio.tsx
- packages/components/src/Form/Fields/FieldRadio/__snapshots__/FieldRadio.test.tsx.snap
- packages/components/src/Form/Fields/FieldSelect/FieldSelect.test.tsx
- packages/components/src/Form/Fields/FieldSelect/__snapshots__/FieldSelect.test.tsx.snap
- packages/components/src/Form/Fields/FieldToggleSwitch/__snapshots__/FieldToggleSwitch.test.tsx.snap
- packages/components/src/Form/Fieldset/Fieldset.tsx
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Form/Inputs/Checkbox/Checkbox.tsx
- packages/components/src/Form/Inputs/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/components/src/Form/Inputs/OptionsGroup/CheckboxGroup.tsx
- packages/components/src/Form/Inputs/OptionsGroup/OptionsGroup.ts
- packages/components/src/Form/Inputs/OptionsGroup/RadioGroup.tsx
- packages/components/src/Form/Inputs/Radio/Radio.tsx
- packages/components/src/Form/Inputs/Radio/__snapshots__/Radio.test.tsx.snap
- packages/components/src/Status/Status.tsx
- packages/design-tokens/src/system/index.ts
- storybook/src/Forms/Fieldset.stories.tsx
- www/src/documentation/components/forms/fields.mdx
- `Badge` now supports `ref` assignment (Tooltip badge is now possible)
- `IconButton` now supports `tooltipTextAlign`
- `Field`
- No longer supports `labelWidth` property (unused feature)
- No longer supports `labelFontSize` and `labelFontWeight` properties (all your fonts belong to us)
- `FieldInline` (`FieldCheckbox`, `FieldRadio` & `FieldToggleSwitch`)
- Now supports `detail` property
- `:disabled` state slightly more discernable from default state now
- `Radio` & `Checkbox` disabled states corrected
- `OptionsGroup` (`CheckboxGroup`, `RadioGroup`)
- Now have tighter vertical spacing to feel more connected
- Supports `detail` on Options array
- `Status` now allows DOM attributes (`aria-*` and the like)
> Form Improvements

- CHANGELOG.md
- packages/components/src/Avatar/__snapshots__/Avatar.test.tsx.snap
- packages/components/src/Button/__snapshots__/Button.test.tsx.snap
- packages/components/src/Button/__snapshots__/IconButton.test.tsx.snap
- packages/components/src/Form/Fields/FieldSelect/__snapshots__/FieldSelect.test.tsx.snap
- packages/components/src/Form/Inputs/InputSearch/__snapshots__/InputSearch.test.tsx.snap
- packages/components/src/Form/Inputs/TextArea/__snapshots__/TextArea.test.tsx.snap
- packages/components/src/Icon/Icon.tsx
- packages/components/src/Icon/__snapshots__/Icon.test.tsx.snap
- packages/components/src/Menu/MenuItem/__snapshots__/MenuItem.test.tsx.snap
- packages/components/src/MessageBar/__snapshots__/MessageBar.test.tsx.snap
- packages/components/src/Modal/Layout/__snapshots__/ModalHeader.test.tsx.snap
- packages/components/src/Status/__snapshots__/Status.test.tsx.snap
- playground/src/index.tsx
- storybook/src/Icon.stories.tsx
- www/src/documentation/components/content/icon.mdx
-  artwork props added to Icon
>  artwork props added to Icon

- CHANGELOG.md
- packages/components/src/Form/Inputs/Combobox/ComboboxList.tsx
- packages/components/src/Form/Inputs/Combobox/ComboboxMulti.test.tsx
- packages/components/src/Form/Inputs/Combobox/ComboboxMultiInput.tsx
- packages/components/src/Form/Inputs/Combobox/ComboboxOptionIndicator.tsx
- packages/components/src/Form/Inputs/Combobox/utils/state.ts
- packages/components/src/Form/Inputs/Combobox/utils/useFocusManagement.ts
- packages/components/src/Form/Inputs/InputChips/InputChips.test.tsx
- packages/components/src/Form/Inputs/InputChips/InputChips.tsx
- packages/components/src/Form/Inputs/InputChips/InputChipsBase.tsx
- packages/components/src/Form/Inputs/Select/Select.tsx
- packages/components/src/Form/Inputs/Select/SelectMulti.test.tsx
- packages/components/src/Form/Inputs/Select/SelectMulti.tsx
- storybook/src/Forms/Combobox/Combobox.stories.tsx
- storybook/src/Forms/SelectMulti.stories.tsx
- www/src/documentation/components/forms/input-chips.mdx
- www/src/documentation/components/forms/select-multi.mdx
- www/src/documentation/components/forms/select.mdx
This PR's main focus is `SelectMulti` free-form input but also includes a couple other adjacent changes needed for this component to be used successfully as an advanced string filter
- `freeInput` in `ComboboxMultiInput` and `SelectMulti` toggles to `InputChips` instead of `InputChipsBase` (the former supports entering values comma-, enter-, tab-, and newline-separated lists)
- This isn't enabled by default in order to better validate the user input with available options.
- Preserve escaped comma and tab characters in `InputChips` (requirement for filters)
- Set `ComboboxList` `minWidth` to the wrapper width if `props.width` has been set to `'auto'` to enable the list width to grow to accommodate wide options (the current behavior is to wrap them)
- Move `removeOnBackspace` from …
> SelectMulti free form input ++

- CHANGELOG.md
- packages/components/src/Button/ButtonItem.tsx
- packages/components/src/Button/ButtonSet.tsx
- packages/components/src/Button/__snapshots__/ButtonGroup.test.tsx.snap
- packages/components/src/Button/__snapshots__/ButtonToggle.test.tsx.snap
- storybook/src/Buttons/ButtonGroup.stories.tsx
- Fixed: Font-size was too small in FF & Safari (browser default)
- Fixed: Awkward white space after highlighted item in `ButtonToggle` (browser default margin)
- Update the "wrapping" check to re-run if `options` prop changes (if it was empty on initial render then enough options were added to make it wrap, the wrapping styles were not applied)
> Fix ButtonGroup & ButtonToggle display issues

- packages/components/src/Button/ButtonItem.tsx
- packages/components/src/Form/Fieldset/Fieldset.tsx
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Menu/MenuList.tsx
- packages/components/src/Modal/Confirm/ConfirmLayout.tsx
- packages/components/src/Sidebar/SidebarGroup.tsx
- packages/components/src/Text/Paragraph.test.tsx
- packages/components/src/Text/Text.test.tsx
- packages/components/src/Text/TextBase.tsx
- packages/components/src/Text/__snapshots__/Paragraph.test.tsx.snap
- packages/components/src/Text/__snapshots__/Text.test.tsx.snap
- packages/design-tokens/package.json
- packages/design-tokens/src/utils/omit.ts
- packages/design-tokens/src/utils/styled-system__props.d.ts
- www/src/Layout/Navigation/Header.tsx
- yarn.lock
- Fixed omitStyledProps to properly omit Flex and Border properties on DOM elements
> Fix Jest warning for invalid DOM prop on Fieldset

- CHANGELOG.md
- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.tsx
- packages/components/src/Form/Inputs/Slider/Slider.tsx
- packages/components/src/Form/Inputs/Slider/__snapshots__/Slider.test.tsx.snap
- Smaller font size and tighter spacing to make the two slider components fit within a 36px vertical space
- [x PR is ideally < ~400LOC
> [LENS-926] Condense Slider and RangeSlider layouts

- CHANGELOG.md
- packages/components/src/Form/Inputs/Combobox/ComboboxMultiOption.tsx
- packages/components/src/Form/Inputs/Combobox/utils/useAddOptionToContext.ts
- packages/components/src/Form/Inputs/Select/Select.test.tsx
- packages/components/src/Form/Inputs/Select/SelectOptions.tsx
- `SelectMulti`: After the changes for `ComboboxOptionIndicator`, the create option had an awkwardly large space to the left – should've just updated it to `indicator={false}` during that change.
- `Select` & `SelectMulti`: Keyboard navigation was broken when filtering due to a typo-esque error during the performance improvements. Added a new test to catch any future breakage.
> Fix SelectMulti create option & filtering keyboard nav

- CHANGELOG.md
- packages/components/src/Button/IconButton.test.tsx
- packages/components/src/Form/Fields/FieldSelect/FieldSelect.test.tsx
- packages/components/src/Form/Fields/FieldSelect/FieldSelect.tsx
- packages/components/src/Form/Fields/FieldSelect/__snapshots__/FieldSelect.test.tsx.snap
- packages/components/src/Form/Fields/FieldSelectMulti/FieldSelectMulti.test.tsx
- packages/components/src/Form/Fields/FieldSelectMulti/FieldSelectMulti.tsx
- packages/components/src/Form/Inputs/InputTimeSelect/InputTimeSelect.test.tsx
- packages/components/src/Form/Inputs/Select/SelectMulti.test.tsx
- packages/components/src/Menu/Menu.test.tsx
- packages/components/src/Popover/Popover.test.tsx
- packages/components/src/Tooltip/Tooltip.test.tsx
- packages/components/src/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- Fixed act warnings in all tests
- Added an `aria-label` to `FieldSelect` & `FieldSelectMulti` when fixing the test revealed that the input couldn't be found via the label.
> Fix act warnings in all tests

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldTextArea/FieldTextArea.tsx
- packages/components/src/Form/Fields/FieldTextArea/__snapshots__/FieldTextArea.test.tsx.snap
- FieldTextArea` now properly links label + textarea via `id` assignment to textarea
> FieldTextArea now properly links label + textarea via "id" assignment to textarea

- tsconfig.build.json
- Stop TSC from emitting test definitions
> Stop TSC from emitting test definitions

- CHANGELOG.md
- packages/components/src/Button/IconButton.tsx
- packages/components/src/Button/__snapshots__/IconButton.test.tsx.snap
- packages/components/src/MessageBar/__snapshots__/MessageBar.test.tsx.snap
- packages/components/src/Modal/Layout/__snapshots__/ModalHeader.test.tsx.snap
- www/src/documentation/components/actions/icon-button.mdx
- IconButton improved hover/active states and no background on hover
- Refined IconButton to remove the need for common overrides used to suppress default :hover background as well as provide more distinct :hover & :active psuedo states.
- Also addressed a weird bug where a border would be momentarily rendered when the cursor removed focus from a IconButton with no border specified
> IconButton improved hover/active states and no background on hover

- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Form/__snapshots__/Form.test.tsx.snap
- packages/components/src/Layout/Grid/Grid.tsx
- packages/components/src/Layout/Space/Space.tsx
- packages/components/src/Layout/Space/SpaceVertical.tsx
- packages/components/src/Layout/Space/__snapshots__/Space.test.tsx.snap
- packages/components/src/Layout/Space/__snapshots__/SpaceVertical.test.tsx.snap
- packages/components/src/Modal/Layout/__snapshots__/ModalFooter.test.tsx.snap
- storybook/src/Layout/Space.stories.tsx
- Use gap for supporting browser (Firefox) 
- Fix tooltip interaction issue
> Use gap for supporting browser (Firefox) fix tooltip interaction issue

- CHANGELOG.md
- packages/components/src/Form/Fieldset/Fieldset.tsx
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Form/Inputs/OptionsGroup/CheckboxGroup.tsx
- packages/components/src/Form/Inputs/OptionsGroup/RadioGroup.tsx
- storybook/src/Forms/CheckboxGroup.stories.tsx
- Expose `wrap` option on Fieldset and use OptionsGroup(s)
- `CheckboxGroup` & `RadioGroup` options now properly wrap when the exceed the container width
> Expose `wrap` option on Fieldset for use by OptionsGroup(s)

- CHANGELOG.md
- packages/components/src/Form/Inputs/Combobox/ComboboxList.tsx
- packages/components/src/Form/Inputs/Combobox/ComboboxOptionIndicator.tsx
- packages/components/src/Form/Inputs/Select/SelectOptions.tsx
- The alignment of the option group label got messed up with the `indicator` changes
> Fix Select group label alignment

- CHANGELOG.md
- packages/components/src/Overlay/OverlaySurface.tsx
- packages/components/src/Overlay/OverlaySurfaceArrow.tsx
- packages/components/src/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- packages/components/src/utils/usePopper.ts
- https://github.com/looker-open-source/components/pull/712 replaced padding on `OverlaySurface` > `Outer` with an offset in `usePopper` ("it seemed like a cool feature")
- This broke the `Tooltip` logic that checks on mouse out of the trigger whether the element that has been "mouse entered"  (`relatedTarget`) is the tooltip itself because the `relatedTarget` was whatever was underneath the offset gap.
- This PR removes the offset and reinstates the padding
> Fix tooltip hover

- CHANGELOG.md
- packages/components/src/Overlay/OverlaySurface.tsx
- Fixes small offset discrepancy on `OverlaySurface` from `Tooltip` hover fix: https://github.com/looker-open-source/components/pull/1128
> Fix OverlaySurface offset

- CHANGELOG.md
- packages/components/src/Menu/MenuItem.tsx
- packages/components/src/Menu/MenuItemLayout.tsx
- packages/components/src/Menu/MenuList.tsx
- packages/components/src/Menu/__snapshots__/MenuGroup.test.tsx.snap
- packages/components/src/Menu/__snapshots__/MenuItem.test.tsx.snap
- www/src/documentation/components/overlays/menu.mdx
- MenuItem disabled
- MenuList group dividers
> MenuItem disabled, MenuList group dividers

- CHANGELOG.md
- packages/components/src/Menu/MenuItem.tsx
- packages/components/src/Menu/MenuItemLayout.tsx
- packages/components/src/Menu/__snapshots__/MenuGroup.test.tsx.snap
- packages/components/src/Menu/__snapshots__/MenuItem.test.tsx.snap
- `MenuItem`
- properly renders when `[aria-current='false']`
- is now exported as Styled Component
- renders properly in Safari / older Chrome implementations
> MenuItem fixes

- CHANGELOG.md
- packages/components/src/Form/Inputs/InputTimeSelect/InputTimeSelect.test.tsx
- packages/components/src/Form/Inputs/InputTimeSelect/InputTimeSelect.tsx
- Updates InputTimeSelect to fire the onChange event when users `tab` out of the text input box. This is to ensure that users don't lose their selection (i.e. manually typing `3:07 pm`) when tabbing over to the next field.
> InputTimeSelect tab key behavior

- CHANGELOG.md
- packages/components/src/Form/Fieldset/Fieldset.tsx
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- `Fieldset` accordion mode now auto-indents children within inner `AccordionContent`
> Fieldset: Accordion mode auto-indentation

- CHANGELOG.md
- packages/components/src/Popover/Popover.tsx
- packages/components/src/utils/useFocusTrap.ts
- storybook/src/Overlays/Popovers/Testing.stories.tsx
- This started off with the goal of getting the "return focus to trigger on Dialog close" behavior working again
- In the meantime, another bug presented itself where you can't open pick from (or sometimes even open) a `Select` rendered in a `Dialog` that was opened from a (still open) `Popover` – instead that original `Popover` inappropriately regains focus.
> Focus Trap: fix return focus & Popover > Dialog > Select

- CHANGELOG.md
- packages/components/src/Form/Inputs/InputText/InputText.tsx
- Fixes output order of theme.reset within `InputText` this could cause situations where reset overrides default parameters.
Note that `InputChips` is not quite correct height.
> InputText + theme.reset fix

- CHANGELOG.md
- packages/components/src/Form/Inputs/Combobox/ComboboxList.tsx
- packages/components/src/Form/Inputs/Combobox/utils/useBlur.ts
- packages/components/src/Form/Inputs/Combobox/utils/useInputEvents.ts
- packages/components/src/Form/Inputs/InputChips/InputChips.tsx
- packages/components/src/Form/Inputs/Select/Select.test.tsx
- packages/components/src/Form/Inputs/Select/SelectMulti.test.tsx
- storybook/src/Forms/Select.stories.tsx
- The keyboard nav was still broke when filtering down from > 100 options to < 100 options due to windowed options weirdness
- `SelectMulti` onBlur was doubly broken:
- with `freeInput` it wasn't creating a chip onBlur because the blur handler from `ComboboxMultiInput` > `useInputEvents` > `useBlur` was clobbering that of `InputChips`
- but that blur handler was broken itself, looking only for `ComboboxContext` and not `ComboboxMultiContext`
> Select/SelectMulti: fix filtering keyboard nav, onBlur behavior

- packages/components/src/Sidebar/SidebarGroup.tsx
- This PR updates the method we use to toggle sidebar links. Rather than removing links from the dom entirely, I simply shrink the container to `height: 0` so that the hidden links will still be in the dom. This will hopefully alert Google search to the existence of other pages, allowing google site-search as a stopgap solution until proper search functionality is implemented. Per @whscullin's [request](https://looker.slack.com/archives/C9NHFLY0G/p1593627269194000?thread_ts=1593624285.191300&cid=C9NHFLY0G)
> Gatsby Sidebar SEO

- CHANGELOG.md
- packages/components/src/Button/IconButton.test.tsx
- packages/components/src/Tooltip/Tooltip.tsx
- storybook/src/Overlays/Tooltip.stories.tsx
- Tooltip being rendered next to its trigger keeps causing issues: unwanted margin in `Space`/`SpaceVertical` and being blocked by `Menu`/`Popover`
- The only reason I can remember to _not_ use `Portal` for `Tooltip` was that it might be awkward when scrolling, but PopperJS seems to handle this well
> Tooltip: add Portal

- CHANGELOG.md
- packages/design-tokens/src/theme.ts
- CORE product needs a zIndexFloor due to Firefox issue with `order` - this could be an issue with other use cases as well so setting a `1` seems like a logical, light-weight fix.
> zIndexFloor defaults to 1

- CHANGELOG.md
- packages/components/src/Link/Link.test.tsx
- packages/components/src/Link/Link.tsx
- packages/components/src/Link/__snapshots__/Link.test.tsx.snap
- packages/design-tokens/src/system/color/specifiable.ts
- packages/design-tokens/src/tokens/color/index.ts
@jhardy While working on this I realized that we don't provide `:visited` and `:active` states. Any thoughts on that?
- A few places in the product have links the leverage the `key` color and have to manually override styles
> Allow for key-colored Link

- CHANGELOG.md
- packages/components/src/Tabs/TabList.tsx
- storybook/src/Tabs.stories.tsx
- www/src/documentation/components/content/tabs.mdx
- TabList now supports distribute prop
> TabList now supports distribute prop

- README.md
- config/deploy.sh
- package.json
- packages/components/README.md
- www/gatsby-config.js
- www/package.json
- www/src/Layout/Navigation/Page.tsx
- www/src/documentation/components/content/calendar.mdx
- www/src/documentation/components/content/list.mdx
- www/src/documentation/components/dialogs/index.mdx
- www/src/documentation/components/forms/fieldset.mdx
- www/src/documentation/utilities/globalstyle.mdx
This change reconfigures Gatsby so that it expects to be deployed to a subfolder (specifically https://looker-open-source.github.io/components). 
- Corrects several root relative links that will break when this change is made.
- Corrects sidebar navigation links to use Gatsby helper to detect and use prefix if applicable
Reproducing the deployment environment locally is a little annoying but it is feasible.
```
yarn deploy
mkdir faux-server
mv public faux-server
cd faux-server
python -m SimpleHTTPServer
```
> Deploy to a subfolder

- CHANGELOG.md
- packages/components/src/Button/icon.ts
- packages/components/src/Tree/Tree.tsx
- packages/components/src/Tree/TreeGroup.tsx
- packages/components/src/Tree/TreeItem.tsx
- storybook/src/Tree/FieldPicker.stories.tsx
- storybook/src/Tree/Tree.stories.tsx
- www/src/documentation/components/content/tree.mdx
- **Note:** All changes were made in response to design feedback from New Explore Experience
- `iconSizes`
- Added `xxsmall` case: `ButtonBase` supports `xxsmall`, but `ButtonIcon` previously did not have a specific case for `xxsmall`. Doing this means that each potential size value of `Button` has a corresponding `ButtonIcon` size
- `Tree`
- Removed `fontWeight` prop
- Added `visuallyAsBranch` prop to control inner disclosure font weight
- `TreeItem`
- Defaulted text color to `text2`
- Added `PrimaryIcon` helper component that styles primary icon with `opacity: 0.5`
Proper sizing on `xxsmall` "+ Add"
button in detail:
`visuallyAsBranch` changes font weight of `Tree` disclosure text to "normal":
`TreeItem` and `TreeGroup` have default text color of `theme.colors.text2` (also `opacity: …
> Tree: Style Updates

- CHANGELOG.md
- packages/components/src/Menu/MenuGroup.test.tsx
- packages/components/src/Menu/MenuGroup.tsx
- packages/components/src/Menu/MenuItem.tsx
- packages/components/src/Menu/MenuList.test.tsx
- storybook/src/Overlays/Menu.stories.tsx
- `MenuGroup` now checks parent `MenuItemContext`s for `renderIconPlaceholder`
- Doing this means that if a `MenuGroup` is the child of a `MenuList` or another `MenuGroup`, it will enable `renderIconPlaceholder` for its children assuming its parent context is set to true
> MenuGroup: Fix iconPlaceholder bug for MenuGroups with only 1 MenuItem

- .gitignore
- playground/package.json
- playground/src/index.tsx
- playground/webpack.config.js
- storybook/src/Dialog/SaveChanges.stories.tsx
- yarn.lock
This PR adds an "analyze" script to the playground. It allows for production of a graph showing the dependency sizes of our core package (at least as it's imported into playground)
You can try it out via `yarn workspace playground analyze` (for unknown reasons it hangs when complete but a quick `ctrl-c` kills off the hanging task. 🤷 
You can then view the result produced in `packages/playground/dist/analyze.html`
This could use additional tooling and documentation in the future (ideally it'd be part of our CI run to produce base line numbers for future comparison) but this initial pass is just being used to establish a baseline number and begin the process of isolating some of our more expensive dependencies.
> Enable bundle size statistics capture

- CHANGELOG.md
- packages/components/src/Button/__snapshots__/Button.test.tsx.snap
- packages/components/src/Button/__snapshots__/ButtonOutline.test.tsx.snap
- packages/components/src/Button/__snapshots__/IconButton.test.tsx.snap
- packages/components/src/Dialog/Layout/__snapshots__/DialogHeader.test.tsx.snap
- packages/design-tokens/src/utils/color/stateful.ts
- storybook/src/Buttons/IconButton.stories.tsx
Currently it's hard to discern the different between the :active ("pressed") intent state and the others. This PR proposes a minor change to make it more discernable
> Proposal: Make IntentPressed (:active) state more discernable

- CHANGELOG.md
- packages/components/src/Accordion/Accordion.tsx
- packages/components/src/Accordion/AccordionContent.tsx
- packages/components/src/Accordion/AccordionContext.tsx
- packages/components/src/Accordion/AccordionDisclosure.tsx
- packages/components/src/Tree/Tree.tsx
- storybook/src/Accordion.stories.tsx
- www/src/documentation/components/content/accordion.mdx
- `Accordion` added "id" prop
-  Used to generate "accordionDisclosureId" and "accordionContentId" values which are passed down to the disclosure and content elements via `AccordionContext`
- `AccordionDisclosure`
- Converted from div to button element
- Utilizes `aria-expanded` and `aria-controls` attributes
- `AccordionContent`
- Utilizes `aria-labelledby` and `role` attributes
**Note:** If this approach seems 👍  I'll update documentation to elaborate on use of `id` prop on `Accordion`.
> Accordion: Accessibility improvements

- CHANGELOG.md
- packages/components/src/ActionList/ActionList.tsx
- packages/components/src/ActionList/ActionListCheckbox.tsx
- packages/components/src/ActionList/ActionListHeader/ActionListHeader.tsx
- packages/components/src/ActionList/ActionListItem.tsx
- storybook/src/ActionList/ActionList.tsx
- www/src/documentation/components/content/action-list.mdx
- `ActionListCheckbox` passes row ID into "aria-describedby" attribute
- `ActionList` new "headerRowId" prop
- Used to set the id of the header row, which is then used for the "aria-describedby" of the select all checkbox
- Fixed bug where passing object (with single attribute "all") into `canSelect` results in select all checkbox regardless of "all" setting
> Action List: Checkbox accessibility

- CHANGELOG.md
- packages/components/src/Form/Inputs/Combobox/ComboboxContext.ts
- packages/components/src/Form/Inputs/Combobox/ComboboxList.tsx
- packages/components/src/Form/Inputs/Combobox/ComboboxMulti.tsx
- packages/components/src/Form/Inputs/Combobox/ComboboxMultiInput.tsx
- packages/components/src/Form/Inputs/Combobox/utils/state.ts
- packages/components/src/Form/Inputs/Combobox/utils/useBlur.ts
- packages/components/src/Form/Inputs/Combobox/utils/useComboboxRefs.ts
- packages/components/src/Form/Inputs/Combobox/utils/useInputPropRefs.ts
- packages/components/src/Form/Inputs/Select/Select.tsx
- packages/components/src/Form/Inputs/Select/SelectMulti.tsx
- packages/components/src/Popover/Popover.test.tsx
- packages/components/src/Popover/Popover.tsx
- storybook/src/Forms/SelectMulti.stories.tsx
- storybook/src/Overlays/Popovers/Testing.stories.tsx
- Convention seems to say that a [_select_](https://material-ui.com/components/selects/) (no typing allowed) should stay focused after the click that dismisses the list, while a [_combobox_ / _autocomplete_](https://material-ui.com/components/autocomplete/) (typing allowed) should lose focus in this scenario.
- **Issue 1:** Because we don't currently follow this convention, there's a bug with `SelectMulti` > `freeInput` where you lose the input value on dismiss click, but the expected behavior is that the value should be tokenized (similar to `InputChips`).
- Updating to follow convention and allow the `Select`/`SelectMulti` input to lose focus (and whatever was clicked to receive that event / focus) on the list-dismissal click when typing is allowed (`isFilterable` or `freeInput`) fixes …
> Fix SelectMulti freeInput + honor click outside

- CHANGELOG.md
- packages/components/src/Menu/MenuDisclosure.tsx
This PR sets the default placement for `MenuDisclosure`'s tooltip to the bottom. This brings consistency to how we do it with icon buttons
> Move the default tooltip placement for menu disclosure

- CHANGELOG.md
- packages/components/src/Form/Inputs/Combobox/utils/useBlur.ts
- packages/components/src/Form/Inputs/InputChips/InputChips.tsx
- **Issue 1:** In this PR https://github.com/looker-open-source/components/pull/1241 I broke toggling when clicking on a `Select` caret icon after you've opened and closed it once:
- **Issue 2:** On `SelectMulti` + `freeInput` clicking on the caret icon to close the list was always broken due to an unnecessary `onInputChange` call (which triggers the combobox's `SUGGESTING` state):
> Fix Select/SelectMulti toggling from the caret icon

- CHANGELOG.md
- packages/components/src/Menu/MenuItem.tsx
- packages/components/src/Menu/__snapshots__/MenuGroup.test.tsx.snap
- detail is now part of MenuItem's clickable area
> update MenuItem detail to be part of the clickable area

- CHANGELOG.md
- packages/components/src/Menu/MenuItem.test.tsx
- packages/components/src/Menu/MenuItem.tsx
- www/src/documentation/components/overlays/menu.mdx
- update MenuItem to not support click and its not a link if disabled
> update MenuItem to not support click and its not a link if disabled

- CHANGELOG.md
- packages/components/src/Tabs/TabList.tsx
- Tabs no longer show scrollbar when overflowing
NOTE: To emulate this behavior for easy testing switch "System Preferences > General" "Show Scroll bars" to "Always"
> Tabs no longer show scrollbar when overflowing

- CHANGELOG.md
- packages/components/src/Accordion/AccordionDisclosure.tsx
- storybook/src/Tree/FieldPicker.stories.tsx
- Changed default color of `Tree` disclosure from black (dependent on browser default for button) to text4
- Design specs from Explore requested that the default `Tree` color be text4
> Set Tree disclosure's default color to text4

- CHANGELOG.md
- packages/components/src/Popover/Popover.tsx
- packages/components/src/Tooltip/Tooltip.tsx
- packages/components/src/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- www/src/documentation/components/overlays/popover.mdx
This PR removes the arrow from tooltip, menu and popover by default.
> Remove arrow from tooltip, menu, and popover by default

- CHANGELOG.md
- packages/components/src/Form/Inputs/Combobox/utils/useInputEvents.ts
- Workaround for this issue in `focus-trap` https://github.com/davidtheclark/focus-trap/issues/114 – when `Select` (without `isFilterable`) is the first focus-able element in a focus-trapped component (`Dialog` or `Popover`), the text is getting inappropriately highlighted.
> Fix focus-trap selecting text in non-filterable Select

- CHANGELOG.md
- packages/components/src/Accordion/AccordionDisclosure.tsx
- packages/components/src/Accordion/AccordionDisclosureGrid.tsx
- packages/components/src/Dialog/Layout/DialogHeader.tsx
- packages/components/src/Dialog/Layout/__snapshots__/DialogFooter.test.tsx.snap
- packages/components/src/Dialog/Layout/__snapshots__/DialogHeader.test.tsx.snap
- packages/components/src/Layout/Space/Space.tsx
- packages/components/src/Layout/Space/__snapshots__/Space.test.tsx.snap
- packages/components/src/Tree/Tree.tsx
- `Accordion` & `Tree` presentation fixes for IE11
- `DialogHeader` presentation fix for IE11
- `Space` presentation fix for IE11 (also affects consumers)
> IE11 Fixes (Accordion, Tree, DialogHeader, Space)

- CHANGELOG.md
- packages/components/src/Form/Inputs/Combobox/ComboboxContext.ts
- packages/components/src/Form/Inputs/Combobox/ComboboxList.tsx
- packages/components/src/Form/Inputs/Combobox/utils/useComboboxRefs.ts
- packages/components/src/Popover/Popover.tsx
When focus leaves the input, the handler in `useBlur` tries to determine if focus landed somewhere in the list. To do that it was using a ref on the `ul` but when you click on the scrollbar to drag it, focus lands on `OverlaySurface.Outer`. Since `ComboboxList` already has access to `popperInstanceRef`, I updated `listRef` to take the `elements.popper` value from there.
`Popover` has an internal `useVerticalHeight` hook that keeps long popovers from going off the page (which would be bad, because of the scroll lock). It updates on window resize, but wasn't updating with the popover's position changed (via `popoverInstanceRef.update()`). I'm piggy-backing on the effects of that update – a changed value for `style.transform` from `usePopper` – to trigger an update in `useVerticalHeight`.
> Fix Select popover-related issues

- CHANGELOG.md
- packages/components/src/Form/Fields/Field.tsx
- packages/components/src/Form/Fields/FieldText/__snapshots__/FieldText.test.tsx.snap
- packages/components/src/Form/Fields/FieldTextArea/__snapshots__/FieldTextArea.test.tsx.snap
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Form/Inputs/InlineInputText/InlineInputText.tsx
- packages/components/src/Form/Inputs/InlineInputText/__snapshots__/InlineInputText.test.tsx.snap
- packages/components/src/Form/Inputs/InputChips/InputChipsBase.tsx
- packages/components/src/Form/__snapshots__/Form.test.tsx.snap
- storybook/src/Forms/Chips.stories.tsx
- storybook/src/Forms/Search.stories.tsx
- `SelectMulti` & `InputChips`:
- Enable vertical scrolling if a max-height is set.
- The `white-space: nowrap` on `Chip` causes it to break out of the flex layout – fixed with `min-width: 0` (see screenshot 1) https://stackoverflow.com/questions/38223879/white-space-nowrap-breaks-flexbox-layout
- `InputSearch`, `Select`, `InputChips` & `SelectMulti`
- with `autoResize` and a max-width that has been reached, the x `IconButton` becomes unclickable (blocked by the hidden text) – see screenshot 2
> Fix InputChips/InputText layout issues

- CHANGELOG.md
- packages/components/src/Form/Inputs/AdvancedInputControls.tsx
- packages/components/src/Form/Inputs/InputChips/InputChips.test.tsx
- packages/components/src/Form/Inputs/InputChips/InputChipsBase.tsx
- packages/components/src/Form/Inputs/InputSearch/InputSearchControls.tsx
- `InputChipsBase` (used in `InputChips` and `SelectMulti`) renders an `InputText`, which moves focus to the inner input just after mousedown
- This behavior disrupts clicking on other elements in the component, like a `Chip` (the whole thing, if a user wants to select a specific chip to delete, or copy its text, as well as the x icon), and the clear field x icon button.
- Some of the disruption can only be seen if the inner input is below the fold (see screen capture below) whereas trying to select a specific chip or copy its text just never works.
- The fix is to add `stopPropagation` on the `Chip` and clear field button, but then move focus to the inner input after the action is complete (where appropriate)
> InputChipsBase: fix click/mousedown/focus issues

- CHANGELOG.md
- packages/components/src/Menu/MenuItem.tsx
- www/src/documentation/components/overlays/menu.mdx
- update MenuItem to support Tooltip
> update MenuItem to support Tooltip

- CHANGELOG.md
- packages/components/src/Form/Inputs/Combobox/utils/getComboboxText.ts
- packages/components/src/Form/Inputs/Select/Select.test.tsx
- packages/components/src/Form/Inputs/Select/Select.tsx
- packages/components/src/Form/Inputs/Select/utils/options.ts
- storybook/src/Forms/Select.stories.tsx
- Currently `Select` only respects an empty string as initial `value` or `defaultValue` if a `placeholder` is defined (and not also an empty string 😛) or if `isClearable` is true
- There has been at least one use case in the core product that needed an empty initial value but neither `isClearable` nor `placeholder` were desirable. (`placeholder=" "` was the workaround used)
- Even with `isClearable` or `placeholder` select was not respecting a `value` change to `''` (see the new example in `Select.stories.tsx`)
- The same use case in the core product that revealed this bug, also showed that the `name` prop wasn't getting passed down to the input.
- Also added support for empty string `value`/`defaultValue` and an option with _its_ value also empty (for example picking "Any option" from a …
> Select: support empty string value

- CHANGELOG.md
- packages/components/src/Tree/TreeGroup.tsx
Updates the spacing on the tree group label to better reflect specs
> Update tree group label spacing to better reflect specs

- CHANGELOG.md
- packages/components/src/Tabs/TabList.tsx
This PR adjusts distributed tabs so that they take up an equal amount of space like the spec calls for.
You can see the effects of this change in this screenshot. Before the tab Rebecca Purple was quite a bit larger than the second tab with the emoji. With this change, you can see in the after screenshot where the tabs no all take up equal space
> Equal space for distributed tabs

- packages/design-tokens/src/utils/color/blend.ts
This change adjusts our blending levels for the text blends to closer align with our previous palette. Our generated text colors were a bit lighter this PR brings them closer to previous levels. Here are some before and after images, the left is our previous palette colors, the right is our generated colors
> Update text blends to closer match previous color palette

- CHANGELOG.md
- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.tsx
- playground/src/index.tsx
https://looker.atlassian.net/browse/LENS-1138
- Updates `RangeSlider` css so that the value label position will align with the thumb label control in ie11
> [LENS-1138] IE11 Range Slider Fix

- CHANGELOG.md
- packages/components/src/Form/Fields/FieldText/__snapshots__/FieldText.test.tsx.snap
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Form/Inputs/InputSearch/__snapshots__/InputSearch.test.tsx.snap
- packages/components/src/Form/Inputs/InputText/InputText.tsx
- packages/components/src/Form/Inputs/InputText/__snapshots__/InputText.test.tsx.snap
- packages/components/src/Form/__snapshots__/Form.test.tsx.snap
Re-add padding to the internal input in `InputText` when `autoResize` is used, after it got lost in https://github.com/looker-open-source/components/pull/1336/files#diff-d0f856b4a667dca8d688eed0eedc54e0
> Fix horiz padding on autoResize

- CHANGELOG.md
- packages/components/src/Tree/Tree.tsx
For reasons I'm still a bit hazy on, helltool is overriding the `font-weight` of `Tree`'s `AccordionDisclosure`. TLDR, what's happening is that helltool is inserting additional CSS stylings into some of the selectors generated by styled-components. For more context, see this Slack thread in the #components_exploration-experience channel:
https://looker.slack.com/archives/C017GM9RY3V/p1598381270001900
However, what I am relatively sure of is that moving the location where we set `font-weight` from the child `AccordionDisclosure`'s JSX to `Tree`'s styled-component selectors should resolve this (i.e. `Tree` respects the "visuallyAsBranch" prop when it comes to setting font-weight). 
This is because that the problem selector (i.e. the one receiving unexpected additional CSS stylings) is less …
> Tree: Set child AccordionDisclosure font-weight in styled-component selector

- CHANGELOG.md
- packages/components/src/Form/Inputs/Select/Select.test.tsx
- packages/components/src/Form/Inputs/Select/Select.tsx
- packages/components/src/Form/Inputs/Select/SelectMulti.test.tsx
- packages/components/src/Form/Inputs/Select/SelectMulti.tsx
- packages/components/src/Form/Inputs/Select/SelectOptions.tsx
- packages/components/src/Form/Inputs/Select/utils/options.ts
- storybook/src/Forms/Select.stories.tsx
- www/src/documentation/components/forms/select-multi.mdx
- www/src/documentation/components/forms/select.mdx
- Previously only `SelectMulti` supported `showCreate` and `formatCreateLabel` (when `isFilterable` is true)
- While `SelectMulti` may have more frequent use cases for these props, `Select` also needs them, since it otherwise has no way for the user to enter a custom value
- Noticed and fixed a couple related bugs:
- `SelectMulti` failing to appropriately show "No options" when `showCreate` is used
- `Select` overwriting search value with the current option value if the option's value and label are different
> Select: support showCreate

- packages/components/src/Menu/MenuItem.tsx
- packages/components/src/Menu/__snapshots__/MenuGroup.test.tsx.snap
Adjusts menu alignment for menu items that have a description
notice how icons are aligned center
Icons now align with `flex-start` if there is a description
> Fix alignment of icons in menu items with descriptions

- packages/components/src/ActionList/ActionListItemAction.tsx
- `ActionListItemAction` Renamed "role" prop to "itemRole" prop
- The purpose of the prop is to pass either "link" or "button" down to the underlying `MenuItem`'s `itemRole` prop. However, the name of that prop on `ActionListItemAction` was `role` rather than `itemRole`. Because props from `ActionListItemAction` are destructured  onto the underlying `MenuItem`, the underlying `MenuItem` was not able to receive a value for its `itemRole` via the `ActionListItemAction`.
`itemRole` prop receiving "link", "button", and not being used:
`ActionListItemAction` with `itemRole="link"`:
`ActionListItemAction` with `itemRole="button"`:
`ActionListItemAction` with no explicitly passed in `itemRole` prop:
> ActionListItemAction: Renamed "role" prop to "itemRole" prop

- CHANGELOG.md
- packages/components/src/Popover/Popover.tsx
- storybook/src/Overlays/Popovers/Popover.stories.tsx
- Something changed in 16.9 (looked but I couldn't find exactly what it was) such that if a page has both an `onMouseUp` (anywhere) and `click` and `mouseup` event listeners added directly to the `document` with `useCapture=true` _after_ a `mousedown`, the click handler will not be called.
- Removing `useCapture` on the `mouseup` listener fixes this.
- Here's a sandbox showing the issue issue https://codesandbox.io/s/boring-platform-tbbf4
- See it fixed at [your local storybook]/?path=/story/overlays-popover--mouse-up
- To see it without `@looker/components`, check out this sandbox: https://codesandbox.io/s/magical-bush-70ngs
- I tried capturing this with a unit test but apparently jsdom is not subject to this behavior.
> Fix Popover click outside issue with onMouseUp

- CHANGELOG.md
- packages/components/src/Dialog/Prompt/Prompt.test.tsx
- packages/components/src/Dialog/Prompt/PromptDialog.tsx
- storybook/src/Overlays/Prompt.stories.tsx
- www/src/documentation/components/dialogs/prompt.mdx
- `Prompt` no longer does `clearOnCancel` by default (but can optionally enable it if desired)
> Prompt clearOnCancel

- CHANGELOG.md
- packages/icons/src/svg/FeedbackOutline.svg
> Add new feedback outline icon

- packages/components/src/Divider/DividerVertical.tsx
* DividerVertical supports SpaceProps
> Hack Extract: DividerVertical supports SpaceProps

- packages/components/src/Form/Fields/Field.tsx
- packages/components/src/Form/Fields/FieldCheckbox/__snapshots__/FieldCheckbox.test.tsx.snap
- packages/components/src/Form/Fields/FieldRadio/__snapshots__/FieldRadio.test.tsx.snap
- packages/components/src/Form/Fields/FieldText/__snapshots__/FieldText.test.tsx.snap
- packages/components/src/Form/Fields/FieldTextArea/__snapshots__/FieldTextArea.test.tsx.snap
- packages/components/src/Form/Fields/FieldToggleSwitch/__snapshots__/FieldToggleSwitch.test.tsx.snap
- packages/components/src/Form/Fieldset/Fieldset.tsx
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Form/Inputs/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/components/src/Form/Label/Label.tsx
- packages/components/src/Form/Label/__snapshots__/Label.test.tsx.snap
- packages/components/src/Form/__snapshots__/Form.test.tsx.snap
- storybook/src/Forms/Fieldset.stories.tsx
Refines the spacing between `Fields` and their `Label`, as well as fields in `FieldSets`.
This also moves label weight to `500` variant
---
> Update spacing and font weight on form labels

- CHANGELOG.md
- packages/components/src/Tabs/TabList.tsx
- packages/design-tokens/src/system/index.ts
- Tablist supports fontSize
- TabList supports SpacingProps
- `fontSize` = small regardless of `distribute` prop
> TabList changes

- package.json
- packages/components-providers/package.json
- packages/components-test-utils/package.json
- packages/components-theme-editor/package.json
- packages/components/package.json
- packages/components/src/Dialog/Surface.tsx
- packages/components/src/Form/Inputs/InputColor/InputColor.tsx
- packages/components/src/Link/Link.test.tsx
- packages/components/src/List/List.test.tsx
- packages/components/src/List/__snapshots__/List.test.tsx.snap
- packages/components/src/utils/getCurrentNode.ts
- packages/design-tokens/package.json
- playground/package.json
- www/package.json
This pulls in a small collection of changes that will be needed when we make the upgrade to Styled Components 5. 
While that upgrade is waiting for our repository migration I figured it'd make sense to incorporate these changes so we're ready to go when we can do the upgrade freely.
> Preparatory work for Styled Components 5 & latest TS

- packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
Would it be worth adding `eslint-plugin-lodash` to the `eslint-config` package if just for the import-scope rule?
https://github.com/wix/eslint-plugin-lodash/blob/master/docs/rules/import-scope.md
> Fix lodash import to "single method"

- packages/design-tokens/package.json
- www/package.json
- www/src/MDX/Pre/CodeSandbox.tsx
- www/src/MDX/Pre/CodeStatic.tsx
- www/src/MDX/Pre/prismTheme.ts
- yarn.lock
- Move prismTheme to www package
- Remove prism devDependency from design-tokens
- Upgrade PrismJS to address security vulnerability documented at: https://github.com/looker-open-source/components/network/alert/yarn.lock/prismjs/open
> Move prismTheme to www package + upgrade PrismJS

- package.json
- www/package.json
- yarn.lock
- Address github-reported dependency vulnerability.
- `resolutions` only works in "root" package.json
> Properly force PrismJS version = 1.21.0

- CHANGELOG.md
- packages/components/src/Tree/TreeItem.tsx
The current behavior turn off the hover when the tree item is selected.
On this PR we change the logic so TreeItemLabel always have a hover state, even when selected.
> feat(TreeItem/TreeItemLabel): change the TreeItemLabel hover behavior

- CHANGELOG.md
- packages/components/src/Dialog/Layout/DialogFooter.tsx
- packages/components/src/Dialog/Layout/DialogHeader.tsx
- packages/components/src/Dialog/Layout/__snapshots__/DialogFooter.test.tsx.snap
- packages/components/src/Dialog/Layout/__snapshots__/DialogHeader.test.tsx.snap
DialogHeader & DialogFooter should not collapse to smaller than the space required for their content and specified padding.
> DialogHeader & DialogFooter no longer shrink in Safari

- CHANGELOG.md
- packages/components/src/Form/Fieldset/__snapshots__/Fieldset.test.tsx.snap
- packages/components/src/Form/Legend/Legend.tsx
- packages/components/src/Form/Legend/__snapshots__/Legend.test.tsx.snap
- packages/components/src/Menu/MenuGroupLabel.tsx
- packages/components/src/Menu/__snapshots__/MenuGroup.test.tsx.snap
Use fonts.brand for Legend & MenuGroupLabel
> Use fonts.brand for Legend & MenuGroupLabel

- CHANGELOG.md
- packages/components/src/Dialog/Dialog.test.tsx
- packages/components/src/Dialog/useDialog.tsx
- Deal with scenario where Dialog only has isOpen specified
> Deal with scenario where Dialog only has isOpen specified

- CHANGELOG.md
Accidentilly landed IconButton icon size change in previous PR. This updates the CHANGELOG accordingly
> Fix CHANGELOG for change that snuck in

- packages/components/src/Tree/TreeItem.tsx
- packages/components/src/Tree/stories/FieldPicker.story.tsx
- www/src/documentation/components/content/tree.mdx
- Added "onMetaEnterKeyDown" prop to `TreeItem`
> TreeItem: Support Cmd + Enter callback prop

- packages/components/package.json
- yarn.lock
Upgrade focus-trap to 6.1.3 to fix IE11 transpile issue (IE11 won't boot with ES6)
Background: https://github.com/focus-trap/focus-trap/blob/master/CHANGELOG.md
> Upgrade to focus-trap@6.1.3 (ie11 transpile fix)

- CHANGELOG.md
- packages/components/package.json
- packages/components/src/Button/ButtonItem.tsx
- packages/components/src/Card/Card.tsx
- packages/components/src/Dialog/Backdrop.tsx
- packages/components/src/Dialog/Dialog.test.tsx
- packages/components/src/Dialog/DialogSurface.tsx
- packages/components/src/Dialog/SurfaceBase.tsx
- packages/components/src/Dialog/useAnimation.ts
- packages/components/src/Dialog/useDialog.tsx
- packages/components/src/Drawer/DrawerSurface.tsx
- packages/components/src/Drawer/useDrawer.tsx
- packages/components/src/Form/Inputs/ToggleSwitch/Knob.tsx
- packages/components/src/Menu/MenuItemLayout.tsx
- packages/design-tokens/src/index.ts
- packages/design-tokens/src/system/transitions.ts
- packages/design-tokens/src/tokens/transitions.ts
- www/src/Shared/ComponentResources/Resource.tsx
- www/src/documentation/components/dialogs/index.mdx
- yarn.lock
- `useDialog` (`Dialog` & `Drawer`) refactored
- Removed use of `react-transition-group` dependency
- Added support for `aria-busy`
- Simplified implementation of `DialogRender` component
> Dialog improvements (animation, remove backdrop customization)

- babel.config.js
- package.json
- storybook/babel.config.js
- yarn.lock
- React version between components and storybook fell out of sync causing Storybook errors.
- Babel upgrade requires minor babel.config tweak.
> Resolve Storybook upgrade issues (React & @babel)

- CHANGELOG.md
- packages/icons/src/svg/ScheduleOutline.svg
Adds a new `ScheduleOutline` icon
> Add schedule outline icon

- CHANGELOG.md
- packages/components/src/Button/ButtonItem.tsx
- packages/components/src/Button/__snapshots__/ButtonGroup.test.tsx.snap
- packages/components/src/Button/__snapshots__/ButtonToggle.test.tsx.snap
Updates the font on `ButtonItem` to body font
> Update ButtonItem to use body font

- README.md
- packages/components/src/Button/ButtonBase.tsx
- packages/components/src/Button/__snapshots__/Button.test.tsx.snap
- packages/components/src/Button/__snapshots__/ButtonOutline.test.tsx.snap
- packages/components/src/Button/__snapshots__/ButtonTransparent.test.tsx.snap
- packages/components/src/Button/iconButtonColor.ts
- packages/components/src/Calendar/Calendar.tsx
- packages/components/src/Form/Inputs/ToggleSwitch/Knob.tsx
- packages/components/src/Form/Inputs/ToggleSwitch/ToggleSwitch.tsx
- packages/components/src/Form/Inputs/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap
- packages/components/src/Tabs/Tab.tsx
- packages/components/src/Tabs/__snapshots__/Tabs.test.tsx.snap
- packages/design-tokens/src/utils/helpers.ts
Correct a mis-step with extracting polished
> Correct a mis-step with extracting polished

- CHANGELOG.md
- packages/components/src/Form/Inputs/InputColor/Swatch/Swatch.test.tsx
- packages/components/src/Form/Inputs/InputColor/Swatch/Swatch.tsx
- packages/components/src/Form/Inputs/InputColor/Swatch/__snapshots__/Swatch.test.tsx.snap
- packages/design-tokens/src/utils/helpers.ts
- storybook/src/Forms/Color.stories.tsx
- www/src/documentation/components/forms/input-color.mdx
This PR adjust how a swatch displays its disabled state.
> Update swatch to have new disabled state

- CHANGELOG.md
- packages/components/src/Form/Inputs/Combobox/utils/useBlur.ts
- packages/components/src/Form/Inputs/InputChips/InputChipsBase.tsx
- packages/components/src/utils/getNextFocusTarget.ts
- packages/components/src/utils/index.ts
- playground/package.json
IE11 doesn't add `relatedTarget` to a blur event so the logic to keep the list open on input blur if the user is clicking into the list was failing, the list was closing prematurely, and the click on the option failed to register.
I added a utility `getNextFocusTarget` that uses `relatedTarget` if available and `document.activeElement` if not. The reason to not use `document.activeElement` across the board is that only IE11 updates that value _before_ the blur event. Other browsers don't update till _after_ the blur event.
`InputChips` was also using a blur event's `relatedTarget` for selecting chips behavior so I used `getNextFocusTarget` there as well.
Both components can be tested in the playground.
> Fix: IE11 click option in Select, etc

- packages/components/CHANGELOG.md
- packages/components/src/utils/useFocusTrap.ts
- Test at `:3333/?path=/story/fieldselect--select-demo`
- Clicking an option on a `Select` in a `Dialog` results in the `Select` losing focus
- Because the focus trap is being re-enabled when the `Select` list closes, and now surface itself is set to `initialFocus`
- (This was probably already happening if there was a `[data-autofocus="true"]` element in the `Dialog`)
> Fix Select + Dialog focus issue

- packages/components/CHANGELOG.md
- packages/components/src/Menu/MenuDisclosure.tsx
- packages/components/src/Tooltip/Tooltip.tsx
Remove extra space `Tooltip` adds to its child's `className`
> Fix Tooltip className space

- packages/components/CHANGELOG.md
- packages/components/src/Form/Fields/FieldSelect/FieldSelect.story.tsx
- packages/components/src/Form/Inputs/Select/Select.test.tsx
- packages/components/src/Form/Inputs/Select/SelectOptions.tsx
- packages/components/src/Form/Inputs/Select/utils/options.ts
- packages/components/src/Form/Inputs/Select/utils/useWindowedOptions.tsx
- packages/components/src/List/IconPlaceholder.tsx
- packages/components/src/Menu/MenuItem.tsx
- packages/storybook-config/src/main.js
1. Fixed `Select` alignment of options when some have icons and others do not.
2. `Select` inappropriately shows "No options" when the current value is empty, after filtering a long list down to a single option then deleting the filter text. 
_Test with the 2nd Select on :3333/?path=/story/fieldselect--select-content_
3. Fixed `Select` remounting its options when the options prop changes due to this fix for a different issue: https://github.com/looker-open-source/components/pull/1240. This causes select via click to fail if the options prop "changes" (same values, new array instance) after a mousedown, e.g. if a parent component contains `usePopover`. 
_Test with the Open Popover button on :3333/?path=/story/fieldselect--select-demo_
> Select: options-related fixes

- packages/components/CHANGELOG.md
- packages/components/src/utils/usePopper.ts
- On very slow pages, Popover flashes in briefly in the upper left corner of the page (due the initial `styles` value) before moving to its proper place, with `PopperJS`-calculated positioning
- Hiding the surface with `opacity` or `visibility` causes all sorts of unit test havoc, but moving it off the screen with a negative `top` value should do the trick.
- `display: none` is definitely a no-go – it would break `PopperJS`'s ability to calculate the correct position based on the surface's dimensions
- I tried and failed to create an example page slow enough to reproduce the bug, but I'm 99% sure this will fix the issue – and it doesn't break anything
> usePopper: render off screen until true position is calculated

- packages/components/CHANGELOG.md
- packages/components/src/Form/Inputs/InputSearch/InputSearch.tsx
- packages/components/src/Form/Inputs/Select/Select.tsx
- packages/components/src/Form/Inputs/Select/SelectMulti.tsx
- packages/components/src/Menu/Menu.tsx
- packages/components/src/Menu/MenuContext.ts
- packages/components/src/Menu/MenuList.tsx
- packages/components/src/Popover/Popover.test.tsx
- packages/components/src/Popover/usePopover.tsx
- packages/components/src/Popover/usePopoverToggle.tsx
- storybook/src/Overlays/Popovers/Popover.stories.tsx
- www/src/documentation/components/overlays/menu.mdx
- www/src/documentation/components/overlays/popover.mdx
- Reversed the default of `Popover`'s `cancelClickOutside` prop from true to false
- Removed `groupedPopoversRef` and the very recent `groupedMenusRef` since they won't be needed anymore
1. Do we want to keep the `cancelClickOutside` prop? If so, should we document it or keep it on the DL?
2. Currently a **non-filterable** `Select` has `cancelClickOutside={true}` to mimic a native browser select. Do we still want this?
> Popover: honor 1st click outside

- storybook/package.json
Removed storybook postbuild task that uses puppeteer since we're not using it yet and it's causing issues with the storybook build inside docker.
> removing postbuild task from storybook

- packages/components/CHANGELOG.md
- packages/components/src/Form/Fields/FieldCheckboxGroup/FieldCheckboxGroup.story.tsx
- packages/components/src/Form/Fields/FieldSelect/FieldSelect.story.tsx
- packages/components/src/Form/Fields/FieldSelectMulti/FieldSelectMulti.story.tsx
- packages/components/src/Form/Fields/FieldTimeSelect/FieldTimeSelect.story.tsx
- packages/components/src/Form/Inputs/Checkbox/Checkbox.tsx
- packages/components/src/Form/Inputs/InlineInputText/InlineInputText.tsx
- packages/components/src/Form/Inputs/InlineTextArea/InlineTextArea.tsx
- packages/components/src/Form/Inputs/InputProps.ts
- packages/components/src/Form/Inputs/InputSearch/InputSearch.story.tsx
- packages/components/src/Form/Inputs/InputSearch/InputSearch.tsx
- packages/components/src/Form/Inputs/InputText/InputText.tsx
- packages/components/src/Form/Inputs/InputTime/InputTime.tsx
- packages/components/src/Form/Inputs/InputTimeSelect/InputTimeSelect.tsx
- packages/components/src/Form/Inputs/OptionsGroup/CheckboxGroup.tsx
- packages/components/src/Form/Inputs/OptionsGroup/OptionsGroup.ts
- packages/components/src/Form/Inputs/OptionsGroup/RadioGroup.tsx
- packages/components/src/Form/Inputs/Radio/Radio.tsx
- packages/components/src/Form/Inputs/Select/Select.tsx
- packages/components/src/Form/Inputs/Select/SelectMulti.tsx
- packages/components/src/Form/Inputs/TextArea/TextArea.tsx
- packages/components/src/Form/Inputs/ToggleSwitch/ToggleSwitch.tsx
- storybook/src/Forms/Time.stories.tsx
- Apply `autoFocus` and `data-autofocus` props to the `ComboboxInput` in all `Combobox`-based components
> Support autoFocus in Combobox-based components

- packages/components/CHANGELOG.md
- packages/components/src/Layout/Semantics/Page.tsx
- Fix `Page` size (% instead of VH/VW)
> Fix Page sizing

- CHANGELOG.md
- packages/components/src/DataTable/Column/DataTableCell.tsx
- packages/components/src/DataTable/DataTable.test.tsx
- packages/components/src/DataTable/Item/DataTableRow.tsx
- DataTable supports onClick of Link/Anchor as text inside rows and does not select the row
> DataTable supports onClick of Link/Anchor as text inside rows and does not select the row

- packages/components/src/Form/Inputs/InputChips/InputChipsBase.tsx
Suggestion for https://github.com/looker-open-source/components/pull/1650 to prevent deleting chips via `Backspace` key when focused on the input, or selecting the chips via click or keyboard.
> InputChipsBase readOnly suggestions

- packages/components/src/Form/Inputs/Combobox/ComboboxContext.ts
- packages/components/src/Form/Inputs/Combobox/utils/useComboboxRefs.ts
- packages/components/src/Form/Inputs/Combobox/utils/useInputEvents.ts
- packages/components/src/Form/Inputs/Combobox/utils/useInputPropRefs.ts
- packages/components/src/Form/Inputs/Combobox/utils/useKeyDown.ts
Suggestions for https://github.com/looker-open-source/components/pull/1650 to update existing uses of `readOnly` in `./Combobox` to `inputReadOnly`.
> Combobox inputReadOnly suggestions

- CHANGELOG.md
- packages/components/src/Calendar/Calendar.tsx
- packages/components/src/Calendar/CalendarNav.tsx
- packages/components/src/Calendar/CalendarNavDisabled.tsx
- packages/components/src/InputDate/InputDate.story.tsx
- packages/components/src/InputDate/InputDate.tsx
- packages/components/src/InputDateRange/InputDateRange.story.tsx
- packages/components/src/InputDateRange/InputDateRange.tsx
- update InputDate to support disabled
- update InputDate to support readOnly
- update InputDateRange to support readOnly
- Disabled - with value
- ReadOnly - with value
- Disabled - no value
- ReadOnly - no value
> update InputDate and InputDateRange to support disabled and readOnly

- packages/components/src/Badge/Badge.tsx
- packages/components/src/Badge/__snapshots__/Badge.test.tsx.snap
- packages/components/src/ChipButton/ChipButton.tsx
- packages/components/src/Form/Inputs/AdvancedInputControls.tsx
- packages/components/src/Form/Inputs/Combobox/ComboboxList.tsx
- packages/components/src/Form/Inputs/InputColor/LuminositySlider/LuminositySlider.tsx
- packages/components/src/Form/Inputs/InputHidden/InputHidden.tsx
- packages/components/src/Form/Inputs/InputTime/InputTime.tsx
- packages/components/src/Form/Inputs/Slider/Slider.tsx
- packages/components/src/Sidebar/SidebarGroup.tsx
- packages/components/src/Text/Code.tsx
- packages/components/src/Text/Paragraph.tsx
- www/src/MDX/Code.tsx
- www/src/MDX/Li.tsx
- www/src/MDX/Ol.tsx
- www/src/MDX/Paragraph.tsx
- www/src/MDX/Ul.tsx
- www/src/Shared/ComponentResources/Resource.tsx
- www/src/Shared/ComponentStatus/ComponentStatus.tsx
- www/src/Shared/Props/Props.tsx
Per Styled Components 5 release removed support for "subfunctions":
Oddly they still seem to work but in the interest of not having ambient breakage later I figured it'd be good to remove these.
> SC5 Support: Remove use of attrs({})

- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/components/src/Form/Inputs/AdvancedInputControls.tsx
- packages/components/src/Form/Inputs/Combobox/Combobox.test.tsx
- packages/components/src/Form/Inputs/Combobox/utils/useBlur.ts
- packages/components/src/Form/Inputs/Combobox/utils/useFocusManagement.ts
- packages/components/src/Form/Inputs/Combobox/utils/useInputEvents.ts
- packages/components/src/Form/Inputs/InputChips/InputChipsBase.tsx
- packages/components/src/Form/Inputs/InputText/InputText.test.tsx
- packages/components/src/Form/Inputs/InputText/InputText.tsx
- packages/components/src/Form/Inputs/Select/Select.test.tsx
- packages/components/src/utils/targetIsButton.ts
- yarn.lock
- **Issue:** Clicking on the caret icon _while_ `Select` is focused fails to open the list.
- **Cause:** The caret click triggered a blur event on the input, which tells `Combobox` to close... _after_ the mousedown event tells it to open. "Blur event -> close" wins.
- **Fix:** `InputText` focuses the input after any mousedown on a non-button element inside the wrapper div – e.g. the caret icon. Adding a check inside the mousedown handler for if the input is already focused and then `e.preventDefault()` avoids the unnecessary blur & refocus, thus fixing the `Select` issue.
- **Issue:** The 1st click on the caret icon on a `SelectMulti` doesn't focus the field.
- **Cause:** In `InputChipsBase.tsx` there was a `onMouseDown={stopPropagation}` that was put in place to prevent the default …
> Select: fix click caret to open while focused

- packages/components/CHANGELOG.md
- packages/components/src/Popover/stories/Popover.story.tsx
- packages/components/src/Tooltip/Tooltip.story.tsx
- packages/components/src/Tooltip/Tooltip.test.tsx
- packages/components/src/Tooltip/Tooltip.tsx
- Allows a `Tooltip` to be nested directly inside a `Popover`
- Previously, `Tooltip` would not forward on the props that `Popover` spreads onto its children, and the React `Function components cannot be given refs` error would be triggered.
- This changes `Tooltip` to accept the `domProps` from `Popover` and pass them down, along with those generated internally, to its child.
> Tooltip: support nesting inside Popover

- packages/components/CHANGELOG.md
- packages/components/src/Tree/Tree.tsx
- packages/components/src/Tree/TreeItem.tsx
- Set `TreeItem`'s `children` prop and `Tree`'s `label` prop to "ReactNode"
- Supports "In Use" use case for Explore team
> Tree: Set children/label to ReactNode type

- packages/components/CHANGELOG.md
- packages/components/src/Tooltip/Tooltip.test.tsx
- packages/components/src/Tooltip/useTooltip.tsx
- `Tooltip`'s `onFocus` handler may be triggered before the callback ref on the trigger is updated, for example an `autoFocus` input receiving focus just as it mounts.
- A recent change for the [Focus Trap refactor](https://github.com/looker-open-source/components/pull/1644) added a check if the element exists and does NOT have `data-notooltip`. In the `autoFocus` scenario, the element does not exist yet (it will soon) but the focus event should not be igored.
- The updated check is for _either_ the element has no `data-tooltip` or it doesn't exist (yet, hopefully).
> Fix Tooltip for autoFocus input

- packages/components/CHANGELOG.md
- packages/components/src/Button/IconButton.story.tsx
- packages/components/src/Menu/Menu.story.tsx
- packages/components/src/Menu/MenuItemLayout.tsx
- packages/components/src/Menu/MenuList.test.tsx
- packages/components/src/Menu/MenuList.tsx
- packages/components/src/Menu/__snapshots__/MenuGroup.test.tsx.snap
- www/src/documentation/components/overlays/menu.mdx
- Fixed: `variable` windowing was being incorrectly applied to any `MenuList` where the first item was not exactly `MenuItem`, even with <100 children. Now `variable` must be explicitly set – the detection logic for `MenuGroup` vs `MenuItem` was faulty – these components are often wrapped, which would fail a check like `child.type === MenuGroup`.
- Fixed: sticky `MenuGroup` label stacking under item labels. A later change for the focus ring style added `position: relative` to the button, which makes it win the stacking order against the `position: sticky` group label. Moving `position: relative` inside `:focus` where it's needed fixes this. (It would still stack on top of the group label if it has focus, but I think that's ok)
> MenuList windowing fixes

- packages/components/CHANGELOG.md
- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.test.tsx
- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.tsx
- packages/components/src/utils/useMouseDragPosition.ts
This reverts commit 1a1c89f7e6c2b698bd91d772e5e60c8f43ef4897.
Revert "Range Slider Touch Support"
> Revert "Range Slider Touch Support"

- packages/components-providers/src/FocusTrap/utils.ts
- packages/components/CHANGELOG.md
- packages/components/src/Dialog/stories/Dialog.story.tsx
- Pre 0.9.26, a click outside a focus trap deactivated it, but that behavior was lost in the refactor
- This PR re-adds click outside to deactivate to focus trap
> Deactivate focus trap on click outside

- packages/components/CHANGELOG.md
- packages/components/src/Form/Inputs/Combobox/ComboboxList.tsx
- packages/components/src/Form/Inputs/Combobox/stories/Combobox.story.tsx
- When the user hovers over or keyboard navigates to an option, it becomes the "navigated-to" option in Combobox state.
- If the navigated-to option is outside of the scroll window, it is auto-scrolled into view at either the top or bottom of the list, as appropriate.
- This logic is meant for keyboard nav, but targets the navigated-to state, and thus is run for hovering as well.
- If the list is smaller when it first opens and grows as options are added, the height is not getting appropriately updated, so the check for being outside of the scroll window can be incorrectly true.
- As the user scrolls, and the mouseenter event fires when scrolling pauses, the hovered option is unnecessarily auto-scrolled to the top or bottom of the list.
- Fixing the logic that keeps track of the list's …
> Fix Combobox jumpy scrolling

- packages/components/CHANGELOG.md
- packages/components/src/Tooltip/TooltipContent.tsx
- Reverts a change from the deprecate defaultProps PR, see comment here: https://github.com/looker-open-source/components/pull/1716/files#r549421281
> TooltipContent width fix

- packages/components/CHANGELOG.md
- packages/components/src/Form/Inputs/InputText/InputText.tsx
- A recent change in https://github.com/looker-open-source/components/pull/1692 added a `preventDefault()` on `InputText`'s wrapper `<div>` mousedown event if the internal input was already focused. That change fixed a bug in `Select`, where `InputText` is an underlying component.
- The aim was to avoid triggering a blur and having to re-focus the input when the caret icon (or summary text, etc) is clicked.
- The unintended side effect was that it broke moving the cursor the input and selecting text with the mouse.
- This PR checks if the mousedown originated in the input and doesn't do anything if so.
- I tried to add a test to guard against this issue but apparently jsdom doesn't simulate moving the cursor around or selecting text on mousedown.
> Fix InputText mousedown issue

- www/src/Layout/Layout.tsx
- www/src/MDX/Blockquote.tsx
- www/src/MDX/Code.tsx
- www/src/MDX/Hr.tsx
- www/src/MDX/Li.tsx
- www/src/MDX/Link.tsx
- www/src/MDX/Ol.tsx
- www/src/MDX/Paragraph.tsx
- www/src/MDX/Pre/CodeSandbox.tsx
- www/src/MDX/Pre/CodeStatic.tsx
- www/src/MDX/Pre/Pre.tsx
- www/src/MDX/Pre/index.ts
- www/src/MDX/Ul.tsx
- www/src/MDX/index.ts
Remove usage of default exports wherever possible. 
Admittedly, none of these use cases affect tree-shaking as they're outside of the library build src but figured I'd remove the pattern as much as possible.
> Remove default exports

- packages/components/CHANGELOG.md
- packages/components/src/DataTable/utils/edgeShadow.ts
> Fixes Safari bug box-shadow applied to DataTable ::after element

- packages/icons/CHANGELOG.md
- packages/icons/src/svg/WarningOutline.svg
> add outline warning icon

- packages/components/CHANGELOG.md
- packages/components/src/utils/useWindow.test.tsx
- packages/components/src/utils/useWindow.tsx
- Previously the initial state for `useWindow` was to render all items in the list, then the height of the list container element is measured, and the state updates to only render the necessary items.
- This basically defeated the purpose of windowing, making the initial render just as slow as it would have been without `useWindow`.
- This PR updates the initial state to only render the first list item until the correct window size is calculated immediately after.
> fix: MenuList windowing initial render performance

- packages/components/CHANGELOG.md
- packages/components/src/Pagination/Pagination.test.tsx
- packages/components/src/Pagination/Pagination.tsx
Addresses feedback from Issue #1775
> fix: Pagination component now enables first and last page of results at same thresholds for previous and next

- packages/components/src/Dialog/stories/Dialog.story.tsx
- packages/components/src/Drawer/stories/Drawer.story.tsx
- www/src/documentation/components/dialogs/drawer.mdx
Also hide "open" drawers and dialogs from Storybook docs to improve
usability of embedded Storybook examples
Addresses #1779
> docs: Correct useDrawer example and properly document Drawer placement

- .github/workflows/canary-release.yml
- .github/workflows/test.yml
Previous configuration was inaccurately bumping version (`1.0.0`) instead of using conventional-commit scheme + `canary-x`
> chore: Tag canary release properly

- packages/components/src/DataTable/DataTable.tsx
- packages/components/src/DataTable/Item/DataTableRow.tsx
- packages/components/src/DataTable/Table.tsx
- packages/components/src/DataTable/getNextFocus.ts
- Moves `useArrowKeyNav` from `DataTable` to `Table` – the bulk actions & filtering components at the top of `DataTable` should have "normal" tabbing.
- Removes `tabIndex={-1}` from the hidden column
- Uses the `getTabStops` from `../utils` (since everything we want to get focus should now be `[tabindex="-1"]` no need to use a custom one anymore)
> fix: tabbing in & out of the table

- .gitignore
- package.json
- packages/components-providers/package.json
- packages/components-providers/tsconfig.build.json
- packages/components-test-utils/package.json
- packages/components-test-utils/tsconfig.build.json
- packages/components-theme-editor/package.json
- packages/components-theme-editor/tsconfig.build.json
- packages/components/package.json
- packages/components/tsconfig.build.json
- packages/design-tokens/package.json
- packages/design-tokens/tsconfig.build.json
- packages/eslint-config/tsconfig.build.json
- packages/icons/package.json
- packages/icons/tsconfig.build.json
- packages/prettier/tsconfig.build.json
- packages/storybook-config/tsconfig.build.json
- packages/stylelint-config/tsconfig.build.json
Currently build requires that users do deep imports againist a somewhat unconventional path and in so doing they also break TS import checks.
```
import { InputDate } from '@looker/components/esm/InputDate'
```
NOTE: TSC (Typescript compiler) won't match up types in the `types` folder, a double import will fix it but it's super awkward and requires ESLint hijinks to not get errors about duplicate imports
```
import { InputDate } from '@looker/components/esm/InputDate'
import { InputDate } from '@looker/components/types/InputDate'
```
```
import { InputDate } from '@looker/components/lib/InputDate'
```
Typescript automatically finds `@looker/components/lib/InputDate/InputDate.d.ts` to resolve typings
> fix: Properly build ems/cjs/ts for easy deep-imports

- packages/components/src/Form/Inputs/Select/SelectOptions.tsx
During the `defaultProps` refactor, `.attrs()` on `SelectOptionGroupTitle` was incorrectly applied.
> fix: Select group heading styles

- .github/workflows/test.yml
- jest-a11y.config.js
- package.json
- packages/components/package.json
- packages/components/src/stories.a11y.ts
- packages/components/src/stories.shots.ts
- packages/design-tokens/package.json
- packages/design-tokens/src/stories.shots.ts
- packages/storybook-config/package.json
- packages/storybook-config/src/main.js
- packages/storybook-config/src/storyshotsConfig.ts
- storybook/package.json
- tsconfig.build.json
- yarn.lock
Enable [Axe](https://github.com/dequelabs/axe-core) in Storybook as well as package scripts for bulk testing (to be added to CI in subsequent PR)
Adds a task for `yarn test:a11y` as well as re-arranging some other tests to follow the `test:` convention
> chore: Enable axe in Storybook and bulk testing (no CI support yet)

- .github/workflows/ci.yml
- README.md
- jest.config.js
- package.json
Coverage step caused problems when running against `main` (can't diff the same branch to itself)
Introduced codecov for coverage analysis: 
> chore: Use Codecov for test coverage reporting

- package.json
- packages/components/src/List/ListItem.tsx
The `test:image-snapshots-update` command referenced `yarn image-snapshots` as opposed to the new name `yarn test:image-snapshots`. Should've caught that in previous PR; my mistake.
> chore: Fixed test:image-snapshots-update command

- packages/components/package.json
- yarn.lock
> fix(deps): Downgrade react-hotkeys-hook to resolve hotkey breakages

- packages/components/src/Tabs/Tab.tsx
> fix: Tab no longer spuriously accepts MarginProps

- packages/components/src/DataTable/Table.tsx
- packages/components/src/DataTable/stories/items.tsx
> fix(DataTable): "sticky" cell border-bottom now presents properly in Safari

- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.tsx
- packages/components/src/Form/Inputs/Slider/Slider.tsx
> fix: `RangeSlider` & `Slider` properly display on inverted themes

- www/src/components/HeaderContent/HeaderContent.tsx
- www/src/pages/index.tsx
- Correctly constructs link to `develop` when running within a folder
- Does not show "Hamburger" menu on home page when deployed within a folder (`/components/latest`)
> docs: Fix broken link and correct Header presentation when site is deployed to folder

- packages/components/src/Form/Inputs/Combobox/utils/getComboboxText.ts
- packages/components/src/Form/Inputs/Combobox/utils/state.ts
- packages/components/src/Form/Inputs/Select/SelectMulti.test.tsx
Issue repros: 
1. Unnecessary `SELECT_SILENT` due to filtering: https://codesandbox.io/s/wispy-wildflower-p2kn3
2. Legit `SELECT_SILENT` due to external state change: https://codesandbox.io/s/zealous-jepsen-jjiyh
This issue (2 issues really) was exposed by this fix https://github.com/looker-open-source/components/pull/1433/files#r491123741 for a different issue, but there were actually 2 separate underlying causes:
1. The `SELECT_SILENT` action exists for controlled use cases in order to sync up the `values` prop with the values in context, if they are found to me out of sync (for example the values are updated externally via an API call response). But the logic that mapped `SelectMulti` values (strings) to `ComboboxMulti` values (objects) was incorrectly setting the `label` to an empty …
> fix(components): Unable to filter SelectMulti with 1 or more controlled values

- packages/components/src/InputDate/InputDate.test.tsx
- packages/components/src/InputDate/InputDate.tsx
100% test coverage on InputDate
> test: InputDate code coverage

- packages/components-providers/src/FocusTrap/FocusTrapProvider.tsx
- packages/components-providers/src/FocusTrap/index.ts
- packages/components-providers/src/FocusTrap/types.ts
- packages/components-providers/src/FocusTrap/utils.ts
- packages/components-providers/src/TrapStack/TrapStackProvider.tsx
- packages/components-providers/src/TrapStack/types.ts
- packages/components-providers/src/TrapStack/utils.ts
- packages/components/src/Menu/Menu.test.tsx
- packages/components/src/utils/useFocusTrap.test.tsx
- packages/components/src/utils/useTrapStack.ts
The [Focus Trap refactor](https://github.com/looker-open-source/components/pull/1644) introduced a bug in the "return focus" behavior. When a trap was activated while a another trap was already active – e.g. a nested menu – the reference to original return focus element was lost. When both focus traps were deactivated (pressing the escape key on a nested menu) focus just landed on `<body>` instead of the menu button.
> fix(FocusTrap): Return focus behavior on nested focus traps

- packages/components/src/Form/Inputs/Combobox/Combobox.test.tsx
- packages/components/src/Form/Inputs/Combobox/ComboboxMulti.test.tsx
- packages/components/src/Form/Inputs/Combobox/utils/useKeyDown.ts
Improves coverage for `Combobox/utils/useKeyDown` via new & updated tests in `Combobox.test.tsx` & `ComboboxMulti.test.tsx`
And, what do you know, because coverage was bad, there was a bug! Arrow Up should open a closed, focused `Combobox`, but it was broken. You can test the issue on a [basic Select here](https://looker-open-source.github.io/components/latest/components/forms/input-select) and the fix on the same page locally. To get a closed, focused `Select`, tab navigate to it or click it then hit Escape.
> test: Combobox useKeyDown coverage

- .eslintrc.js
- .vscode/settings.json
- config/i18nIgnoredProps.js
- packages/components/src/Dialog/Confirm/ConfirmationDialog.tsx
- packages/eslint-config/index.js
- packages/eslint-config/package.json
- yarn.lock
Adds in automated linting for i18n
Definitely not perfect but still helpful (I think). Currently flags 12 failures that I think are legitmate.
> test: Add eslint 'i18next/no-literal-string' rule for automatic i18n checking

- packages/components/src/Table/Table.tsx
- packages/components/src/Table/TableCell/TableHeaderCell.tsx
- packages/components/src/Table/TableCell/__snapshots__/TableHeaderCell.test.tsx.snap
- packages/components/src/Table/__snapshots__/Table.test.tsx.snap
While testing some of the theme, I noticed our `Table` components did not respect the theme. This change ensure those components use theme values. 
> fix(Table): text in Table components use colors from the theme

- config/i18nIgnoredProps.js
- packages/components/src/Badge/Badge.tsx
- packages/components/src/Chip/Chip.tsx
- packages/components/src/CopyToClipboard/CopyToClipboard.tsx
- packages/components/src/DataTable/Column/DataTableCell.tsx
- packages/components/src/DataTable/Item/DataTableAction.tsx
- packages/components/src/DataTable/Item/DataTableItem.tsx
- packages/components/src/DataTable/Item/DataTableRow.tsx
- packages/components/src/DataTable/Table.tsx
- packages/components/src/Dialog/Confirm/ConfirmLayout.tsx
- packages/components/src/Dialog/Confirm/ConfirmationDialog.tsx
- packages/components/src/Dialog/Dialog.tsx
- packages/components/src/Form/Fields/Field.tsx
- packages/components/src/Form/Fields/FieldBase.tsx
- packages/components/src/Form/Fieldset/Fieldset.tsx
- packages/components/src/Form/ValidationMessage/ValidationMessage.tsx
- packages/components/src/Icon/Icon.tsx
- packages/components/src/List/ListItem.tsx
- packages/components/src/Tooltip/types.ts
- packages/components/src/Truncate/Truncate.tsx
This PR adds JSDoc call-out to all props should probably be i18n'd upstream.
Also removes a few explicit children`instances that in implicitly added through interface extension of FC generic wrapper.
> chore: Add JSDoc annotation to props that should be i18n'd

- packages/components/src/Form/Inputs/Combobox/utils/useInputEvents.ts
The text in a `Select` (_without_ `isFilterable`) gets inappropriately highlighted when focused via keyboard, which is default browser behavior for text inputs. This change actively deselects the text when `inputReadOnly` on `ComboboxInput` is true – which corresponds to `isFilterable` on `Select` is undefined or false.
> fix(Select): Text highlighted when focused via keyboard

- packages/components/src/Dialog/Dialog.test.tsx
- packages/components/src/Dialog/DialogContext.ts
- packages/components/src/Dialog/Layout/DialogHeader.tsx
- packages/components/src/Dialog/SurfaceBase.tsx
- packages/components/src/Dialog/stories/Dialog.story.tsx
- packages/components/src/Dialog/useDialog.tsx
- packages/components/src/Popover/usePopover.tsx
Storybook DialogHeader inherits Dialog id:
Screen reader reads labelled Dialog:
> feat: Add label to Dialog

- packages/components/src/Icon/Icon.tsx
- packages/components/src/Tree/Tree.test.tsx
- packages/components/src/Tree/types.ts
- packages/design-tokens/src/system/index.ts
This also meant adding the label prop to both `Tree` and `Icon` since they can still accept those as props.
> fix: Removed 'label' from CompatibleHTMLProps interface

- packages/components/src/List/index.ts
- packages/components/src/List/utils/listItemDimensions.ts
If your `ListItem` / `TreeItem` / `MenuItem` has string children, those strings are automatically be styled according to our density dimensions objects. However, if a non-string ReactNode is passed in, those stylings don't take affect (since we don't wrap non-string ReactNode children in a Truncate + Text wrapper).
Exposing the `listItemDimensions` function provides a way for non-string ReactNode children to stay consistent with a given density's intended dimensions.
> chore(List): Exported listItemDimensions util function

- packages/components/src/List/ListItemDetail.tsx
- packages/components/src/List/ListItemWrapper.tsx
Currently, the `${reset}` CSS is removing vertical and right padding, which makes the internal button / a element within `ListItem` much shorter than it should be. Removing the `${reset}` from `ListItemWrapper` should resolve this issue and allow us to proceed with the HT upgrade PR.
**Note:** The relevant snapshot changes to `List` and `Menu` have to do with the "detail" string fonts changing in various snapshots from what I can tell.
> fix(ListItem): Removed reset from ListItemWrapper

- packages/components/src/List/ListItemWrapper.tsx
- packages/components/src/List/utils/listItemBackgroundColor.ts
In the even that `theme.colors.background` does not match the actual background color of a ListItem's container (like with the "Copy my dash" modal), hovering over a disabled item produces a hover background:
Setting the `background-color` to "transparent" when a `ListItem` is disabled and hovered should get the look we want (i.e. no hover background when an item is disabled).
> fix(ListItem): Set background of disabled ListItemWrapper to transparent

- packages/components-providers/src/FocusTrap/utils.ts
- packages/components/src/utils/useFocusTrap.test.tsx
Fixes the `web/components/SessionTimeoutModal/SessionTimeoutModal.spec.tsx` test failure from the integration PR. The test was failing, because the focus logic is targeting a [hidden input](https://github.com/looker/helltool/blob/master/web/components/SessionTimeoutModal/components/DataMethodForm.tsx#L27).
> fix: Focusing hidden input element

- packages/components-providers/src/TrapStack/TrapStackProvider.tsx
- packages/components-providers/src/TrapStack/types.ts
- packages/components-providers/src/TrapStack/utils.ts
- packages/components/src/Dialog/useDialog.tsx
- packages/components/src/utils/useFocusTrap.test.tsx
- packages/components/src/utils/useFocusTrap.ts
- packages/components/src/utils/useTrapStack.ts
Classic `useEffect` dependency mis-use.
[This PR](https://github.com/looker-open-source/components/pull/1886) added a `returnFocusRef` option to `useFocusTrap` in such a way that the `useEffect` in `useTrapStack` would run on every render. For a nested `disabled` focus trap (e.g. `Select`* inside a `Popover`) it would re-activate the a previous focus trap too early (and repeatedly). This PR adds a `useMemo` to fix that.
For the life of me I could not reproduce the bug in jest. But to test on https://looker-open-source.github.io/components/latest/storybook/?path=/story/fieldselect--select-demo try opening the 2nd `Select` as soon as you open the `Popover`. The 1st `Select` will keep focus as the focus trap repeatedly deactivates & re-activates. (See screen captures below.)
*`Select` has a …
> fix(FocusTrap): Overly aggressive return focus behavior

- packages/components/package.json
- packages/components/src/Dialog/Layout/DialogContent.test.tsx
- packages/components/src/Dialog/Layout/DialogContent.tsx
- yarn.lock
Use useResize hook to toggle the overflow styling on `DialogContent`, and remove react-resize-detector as a dependency.
> refactor: Remove react-resize-detector dependency

- packages/components/src/DataTable/Table.tsx
**problem:** if page has `border-collapse: collapse;` as a global css rule. It was causing the border-bottom of the sticky first column to not display.
To see the error on PDT open the link below on Firefox
https://lenslatest.dev.looker.com/admin/pdts?connection=All%20Connections
To see the problem locally add this to: `storybook/storybook/preview-head.html`
this will make the `border-collapse` rule be placed as global to storybook.
```
<style>e
table { border-collapse: collapse }
</style>
```
then open storybook on Firefox and open the `DataTable - select-active-items` example.
> fix(DataTable): Sticky "columns" should display a bottom-border (firefox)

- packages/components/src/Animate/Animate.test.tsx
- packages/components/src/Animate/Animate.tsx
- packages/components/src/Animate/__snapshots__/Animate.test.tsx.snap
This PR will allow `FadeIn` to be used in the core product without breaking a bunch of `toBeVisible` tests. The `animation-fill-mode: both` style makes the initial `opacity: 0` unnecessary by using the beginning of the `animation-name` as the initial state. Removing the extra `opacity: 0` means that `toBeVisible` tests will pass.
> refactor(FadeIn): Change styles to support toBeVisible tests

- packages/components/src/DataTable/Item/DataTableRow.tsx
- packages/components/src/DataTable/Table.tsx
in Safari the DataTable sticky cell wasn't behaving properly.
to see the error on PDT open the link below in Safari:
To repeat the error:
1. on `columns.ts` line 33
- switch `size: 'medium',` for `size: 'nowrap',`
2. on `item.tsx` line 78
- remove ` description={type}`
3. open storybook on `datatable--select-active-items`  in Safari and make the screen smaller so the first column is sticky. The `border-bottom` on that first column changes place.
> fix(DataTable): Safari stick cell bug

- packages/components-providers/src/I18n/resources.ts
- packages/components/src/Calendar/Calendar.tsx
- packages/components/src/Calendar/formatMonthTitle.ts
- packages/components/src/Calendar/index.ts
- packages/components/src/Calendar/types.ts
- packages/components/src/Form/Fields/FieldDateRange/FieldDateRange.tsx
- packages/components/src/Form/Inputs/InputDate/InputDate.test.tsx
- packages/components/src/Form/Inputs/InputDate/InputDate.tsx
- packages/components/src/Form/Inputs/InputDateRange/InputDateRange.tsx
I'm addressing 2 concerns related to a11y with date picker component. Both InputDate and InputRangeDate are affected.
1. Read out the Month+Year, currently displayed on the calendar when it's changed (either via Previous/Next month buttons or Up/Down to change year).
2. Add labels to input texts.
InputDate:
1. Added `aria-live="polite"` to `CalendarNav` makes VO read the new Month+Year nicely.
2. No change. Already labelled.
InputRangeDate:
1. Multiple `aria-live` doesn't seem to work with VO. Only the last Month+Year is mentioned. I need some suggestions on how to address this.
2. Added `aria-labelledby` to both the Start and End date input texts.
> fix: InputDate & InputDateRange accessibility improvements

- packages/components/src/Accordion/Accordion.test.tsx
- packages/components/src/Accordion/AccordionDisclosure.tsx
- packages/components/src/Tree/Tree.tsx
`useHovered` was designed specifically for the "hidden element revealed when hovering over some other element" pattern. In `Tree`'s case, we just need simple mouseEnter and mouseLeave handlers to track hover state for styling purposes.
**Note:** Needed to update some code in `AccordionDisclosure` since it had CompatibleHTMLProps in its interface, but didn't actually pass those down to underlying DOM elements.
> refactor(Tree): Replaced useHovered with simpleHandlers

- packages/components/src/Menu/Menu.story.tsx
- packages/components/src/Menu/Menu.tsx
- packages/components/src/Menu/MenuList.test.tsx
- packages/components/src/Menu/MenuList.tsx
This PR puts back `overflow: hidden` on `MenuList` that got lost in [this change](https://github.com/looker-open-source/components/pull/1906/files#diff-d6c17c6698ceeea0bf50ca79fad14f8e6b235b2feb1ae07b0cd6b353a2b5380aL248).
> fix(MenuList): Windowing

- packages/components-providers/package.json
- packages/components/package.json
- yarn.lock
Having multiple copies of `react-i18next` results in an error, which we saw core product repo. Removing the caret makes it easier to keep versions consistent.
> chore: Upgrade react-i18next

- packages/components/src/List/List.story.tsx
- packages/components/src/utils/checkElementRemoved.ts
- packages/components/src/utils/checkFocusedItemRemoved.ts
- packages/components/src/utils/useArrowKeyNav.test.tsx
- packages/components/src/utils/useArrowKeyNav.ts
If `useArrowKeyNav`'s currently focused element is removed from the DOM, it becomes impossible to get focus back into the list. But as long as the list itself hasn't been removed, we want focus to stay inside until the user moves it elsewhere.
React does not trigger `onBlur` in this scenario. Some browsers do trigger a `focusout` event, but not all. The only reliable way to catch it is using a `MutationObserver` that checks if an element being removed was the focused item.
> fix(useArrowKeyNav): Focus lost when item is removed

- packages/components-providers/package.json
- packages/components-providers/src/ComponentsProvider.test.tsx
- packages/components-providers/src/ComponentsProvider.tsx
- packages/components-providers/src/FontFaceLoader/FontFaceLoader.test.tsx
- packages/components-providers/src/FontFaceLoader/FontFaceLoader.tsx
- packages/components-providers/src/FontFaceLoader/index.ts
- packages/components-providers/src/index.ts
- packages/design-tokens/src/system/typography/font_sources.ts
- packages/design-tokens/src/system/typography/index.ts
- packages/design-tokens/src/theme.ts
- packages/design-tokens/src/utils/typography/googleFontUrl.test.ts
- packages/design-tokens/src/utils/typography/googleFontUrl.ts
- packages/design-tokens/src/utils/typography/index.ts
- yarn.lock
- Leverages `react-helmet-async` to add `<style>` tag for loading fontSources specified in theme.fontSources
- Refactors GoogleFontLoader to instead generate `FontSource` and leverage `FontFaceLoader`
> feat(FontFaceLoader): new component to support flexible font loading

- packages/components/src/utils/useClickable.ts
Added a missing `MouseEvent` to the generic `onClick` type in `useClickable`. I also exported `GenericOnClick` from there to slightly improve the awkwardness of matching it up with a "regular" `onClick`. This hook calls `onClick` from `onKeyDown` for the space & enter keys, which is why `| KeyboardEvent<E>` is needed.
> fix(useClickable): Improve and export onClick type

- packages/components/src/List/List.story.tsx
- packages/components/src/List/List.tsx
- packages/components/src/Menu/MenuList.story.tsx
- packages/components/src/utils/getNextFocus.ts
- www/src/documentation/components/content/list.mdx
- www/src/documentation/components/overlays/menulist.mdx
I noticed that scrolling in a long `Menu` seemed to have a bounce / rubber band effect on `main`. See the "Windowing (3k) Menu" on `main`'s storybook:
https://looker-open-source.github.io/components/latest/storybook/?path=/story/menu--long-menus
Turns out, I had forgotten to pass the `ref` returned from `useWindow` to `List`'s underlying `ul` element 🤦 . From what I can tell, this meant that the scroll position event handlers produced by `useScrollPosition` weren't attaching to the container `ul`, which meant that scroll position wasn't being calculated properly on scroll (which caused the bounce effect).
> fix(List): Fixed List / Menu windowing

- packages/components-providers/package.json
- packages/components/package.json
- packages/components/src/index.ts
- www/src/MDX/Pre/allComponents.ts
- www/src/documentation/develop/internationalization.mdx
- yarn.lock
Re-exports i18n strings & utils from the `@looker/components` package so one doesn't have to install `@looker/components-providers`.
Basic documentation on how to add translations & set the language.
Removes caret from the version, because "global-not-global".
> feat: Export i18n strings and utilities

- packages/components/src/List/index.ts
- packages/components/src/Menu/MenuHeading.tsx
- Export `ListItemContext` so external components can utilize context + `listItemDimensions` util function to pull from our density scale (i.e. if they're using a non-text child for their `ListItem`)
- Change `MenuHeading` child to `ReactNode` (the `MainNav` has `<Highlight/>` children for search in the Explore dropdown, and the heading can be included in the search results so it can't just be a text child afaik)
> refactor: List and Menu quality of life updates

- packages/components/src/Form/Inputs/AdvancedInputControls.tsx
Currently on a `Select` or `SelectMulti` with `isFilterable`, the entire input shows `cursor: text`,* including the caret icon, which feels weird. (Any icon buttons inside the input, like the clear button, are `cursor: pointer`.)
This PR adds `cursor: default` to the caret icon to approximate the [native browser `input` + `datalist` experience](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist).
> feat(Select): Caret icon always has default cursor icon

- packages/components/src/Menu/MenuItem.test.tsx
- packages/components/src/Menu/useNestedMenu.tsx
When I added the `nestedMenu`, I unintentionally put `aria-haspopup` and `aria-expanded` attributes on `MenuItem`s that didn't have nested menus. This PR removes those.
> fix(MenuItem): Remove unnecessary aria attributes when there is no nested menu

- packages/components/src/List/ListItem.tsx
- packages/components/src/List/ListItemWrapper.tsx
- packages/components/src/Truncate/Truncate.tsx
Previously, the `ListItem` child wrapper and description wrapper followed this composition:
```
<Truncate>
<Text         
color={labelColor}
fontSize={itemDimensions.labelFontSize}
lineHeight={itemDimensions.labelLineHeight}
>
{children}
</Text>
</Truncate>
```
I had mistakenly thought that `Truncate` would only work if its immediate parent wasn't an inline element 🤦  Because of this old composition, the `Truncate` element wasn't receiving the density-respecting styles (i.e. font size and line height) and required a `line-height: 1` style override to get the right heights for each density.
Moving `Truncate` within the `Text` element means that `Truncate` just "absorbs" the density-respecting styles on the `Text` element.
Please check the following items are addressed in your pull request …
> refactor(ListItem): Moved Truncate within Text for proper styling

- packages/components/src/Accordion/AccordionDisclosure.tsx
- packages/components/src/List/ListItemWrapper.tsx
- packages/components/src/Menu/MenuHeading.tsx
Per a conversation earlier today I realized that the strategy I used to display `focus-visible` on `ListItem` to prevent conflicts with `MenuHeading` was probably going to cause issues (either now or in the future). T
his change alters the strategy to `box-shadow` (per @jhardy's suggestion) and removes the problematic usage of `position: relative` abdicating the need for `z-index` on `MenuHeading`
While surveying our other strategies for displaying the "focus ring" I noticed that we were using `outline` on `AccordionDisclosure` and went ahead and pulled it into the same approach used for `Listitem` to reduce the number of strategies in use.
> fix(Listitem): Improved strategy for :focus-visible CSS (remove z-index from MenuHeading)

- packages/components/src/Button/ButtonItem.tsx
- packages/components/src/Button/IconButton.tsx
- packages/components/src/Button/__snapshots__/ButtonGroup.test.tsx.snap
- packages/components/src/Button/__snapshots__/ButtonToggle.test.tsx.snap
- packages/components/src/List/ListItem.tsx
- packages/components/src/Tabs/Tab.tsx
- packages/components/src/Tabs/__snapshots__/Tabs.test.tsx.snap
Updates the following components to explicitly include `type="button"` to prevent accidentally triggering form submission:
- ButtonItem
- IconButton
- ListItem (MenuItem & TreeItem come along for the ride here)
- Tab
> fix: Correct issue where components that output DOM button w/o type="button" inadvetedly submit HTML forms

- packages/components/src/List/ListItem.test.tsx
- packages/components/src/List/ListItemWrapper.tsx
Prevent props such as `detail` and `description` from being spuriously emitted into DOM output.
> fix(ListItem): Prevent props from being spuriously emitted to DOM output

- packages/components/src/Form/Inputs/InputSearch/InputSearch.test.tsx
- packages/components/src/Form/Inputs/Select/SelectOptions.tsx
> fix(SelectOptions): Render an option, not a header, when value is an empty string

- packages/components/src/Truncate/Truncate.tsx
In some cases scroll bars may be displayed on `Truncate` components
- If users have checked the "always visible" scrollbar option on MacOS
- Firefox on Windows _sometimes_ triggers (not sure of exact setting)
- Chrome on Linux _sometimes_
> fix(Truncate): Prevent spurious scrollbar presentation due to browser settings

- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.story.tsx
- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.test.tsx
- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.tsx
This `RangeSlider` issue was uncovered in the core product Filter component when an intermediate re-render occurs _after_ the user drags a slider thumb but _before_ the prop reflects the change. Because the `value` prop is an array, newly instantiated on each render, the shallow diffing on the `[valueProp]` dependency array in a `useEffect` in `RangeSlider` caused the state value to be reverted to the stale prop value.
This PR removes the `[]` around `valueProp` in the dependency array to allow comparison of the min & max values themselves.
The use of the `RerenderRepro` story in the unit test is a newish pattern for us (used once in `Drawer.test.tsx`), an idea from @lukelooker a while back that I thought was great.
> fix(RangeSlider): Value state reverting if re-rendered before prop is updated

- packages/components/src/Dialog/Layout/DialogLayout.tsx
- packages/components/src/Dialog/stories/Dialog.story.tsx
- packages/components/src/Popover/stories/Popover.story.tsx
- packages/components/src/Portal/Portal.tsx
- `Portal` initially renders its contents into an unattached `div` which it then appends to `div#modal-root` in a `useEffect` hook
- `MultiFunctionButton` contains a `useEffect` hook that measures the height & width of the button & alternate
- When `MultiFunctionButton` is inside a `Portal` (e.g. in a `Dialog` or `Popover`), its measurement `useEffect` occurs before the `Portal`'s dom-attachment `useEffect`, so the measurements return 0
- Changing `Portal`'s `useEffect` to `useLayoutEffect` moves it before the `useEffect`s of any children, so `MultiFunctionButton`'s measurements will happen after the elements have been inserted and return appropriate values
> fix(Portal): Insert element earlier to support measured components

- www/src/documentation/components/content/data-table.mdx
> docs(DataTable): Update examples with deprecated widthPercent prop (size is correct)

- config/i18nIgnoredProps.js
- packages/components/src/List/List.story.tsx
- packages/components/src/List/List.test.tsx
- packages/components/src/List/List.tsx
- packages/components/src/Menu/Menu.tsx
- packages/components/src/Menu/MenuList.tsx
- packages/components/src/Tree/Tree.tsx
The `height: 100%` style on `List` is necessary for windowing to work, but it can be problematic for non-scrolling, non-windowed lists when the container's height is defined (say 100% of the window height) but `List` is not the only child and is not intended to take up the full height of the container. For example, this page shouldn't need to scroll: https://codesandbox.io/s/stupefied-sanne-9vsm1
This PR removes `height: 100%` when `windowing` is `none`.
> fix(List): Only define height when windowing

- www/src/Layout/Layout.tsx
- www/src/components/HeaderContent/AppLogo.tsx
- www/src/components/HeaderContent/HeaderContent.tsx
- www/src/components/Navigation/Page.tsx
- www/src/components/Navigation/Section.tsx
- www/src/components/Status.tsx
Minor corrects to documentation site styling due to refactor of @looker/components CSS reset removal.
> docs: Correct assumption of global CSS reset

- .github/workflows/ci.yml
Github Actions have been really slow today (sitting in queue for a looong time) - I realized that one thing we could do to save resources is to cancel runs when a developer does another push to the same Pull Request before the previous run has not yet finished.
This PR leverages a Github Action to do so: https://github.com/marketplace/actions/cancel-workflow-action
> chore(ci): Cancel CI runs from previous pushes to branch

- package.json
- yarn.lock
Generally we use package.json resolutions to REQUIRE a newer version of a transient dependency to prevent the usage of transient dependencies with known vulnerabilities.
This PR loostens that requirement to require the fixed version or NEWER instead of explicitly locking to the fix version specifically
> chore(deps): Loosen package.json resolutions

- packages/components/src/Menu/Menu.story.tsx
- packages/components/src/utils/useHovered.test.tsx
- packages/components/src/utils/useHovered.ts
`useHovered` was typecasting `as Node` on arguments that might be `null` in order to call `compareDocumentPosition` and detect if a child of the hover element was currently focused. This caused an `Invalid argument` error in IE11 (though no other breakage, as far as I could tell).
This PR adds a check before calling `compareDocumentPosition` and removes the typecasting.
I also added a test suite.
> fix(useHovered): Invalid argument error

- packages/components-providers/src/StyleDefender.test.tsx
- packages/components-providers/src/StyleDefender.tsx
Also remove `height: 100%` behavior
> fix(StyleDefender): Should not override base font-size

- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.story.tsx
- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.test.tsx
- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.tsx
BACKPORT
Reverts change in https://github.com/looker-open-source/components/commit/6b1ae1945f9c3951ceede4bb980ba778c95955cd to fix an issue where changing the min/max doesn't update the value to stay within bounds.
Repro here: https://codesandbox.io/s/determined-breeze-jwi25
> fix(RangeSlider): Value stays within bounds when min/max changes

- .github/workflows/canary.yml
- config/website.sh
After the [icon refactor](https://github.com/looker-open-source/components/pull/1925), `yarn prebuild` has been required in order to use `@looker/icons`.
Currently, the CI canary action is failing to build gatsby because it's not running `yarn prebuild`: https://github.com/looker-open-source/components/runs/2477449739?check_suite_focus=true#step:5:44
This PR adds the command right after `yarn install`.
> chore: Run yarn prebuild in canary

- packages/components/src/Accordion/Accordion.tsx
- packages/components/src/Accordion/AccordionDisclosure.tsx
- packages/components/src/Tree/Tree.tsx
- packages/components/src/Tree/types.ts
_Preliminary work for focus visible refactor._
As I was pulling out the focus visible logic in here to replace with the upcoming `useFocusVisible` hook, I realized `AccordionDisclosure` is actually a great use case for `useClickable`. This hook is aimed at accessibility for non-buttons that are being used in a button-y way. It adds keyup handlers for enter and spacebar keys, and it has focus visible behavior built-in. The enter key was already triggering the accordion toggle, so the only change from `useClickable` is toggling on the spacebar key.
Doing this change in a separate PR helps make the focus visible refactor more sane.
> feat(Accordion): Toggle on spacebar key

- packages/components/src/Menu/Menu.story.tsx
- packages/components/src/Menu/MenuHeading.hooks.test.tsx
- packages/components/src/Menu/MenuHeading.hooks.ts
- packages/components/src/Menu/MenuHeading.tsx
This change to the `useElementVisibility` hook that determines with the `MenuHeading` shadow should show: https://github.com/looker-open-source/components/commit/bf598b7c21faa6dc826cc8b22419b4ffdb3cfacd#diff-58aa7dbeb326c11658b303bd6740b2e7c2427758de4acf7da03c3bbda38ef71d
...caused the `useEffect` to NOT run repeatedly, exposing an issue where the shadow (wrongly) shows initially and then hides after scrolling.
> fix(MenuHeading): Hide shadow initially

- www/src/documentation/components/content/icon.mdx
> docs(Icon): Correct documentation link to Styled Icons (bad markdown formatting)

- packages/components/src/List/ListItem.test.tsx
- packages/components/src/Tree/Tree.test.tsx
- packages/components/src/Tree/TreeItem.test.tsx
- packages/components/src/utils/HoverDisclosure/HoverDisclosure.tsx
> fix(HoverDisclosure): Use CSS visibility instead of de-rendering

- packages/design-tokens/src/color/blendPoints.ts
- packages/design-tokens/src/color/utils/generateBlendColors.test.tsx
- packages/design-tokens/src/color/utils/mixColors.test.ts
- packages/design-tokens/src/color/utils/mixColors.ts
- packages/design-tokens/src/theme/utils/generateTheme.test.ts
> fix(design-tokens): text5 color is now identical to text (blend=100%)

- packages/components/src/List/ListItemLabel.tsx
- packages/components/src/Tree/stories/FieldItem.tsx
- packages/components/src/Tree/stories/FieldPicker.story.tsx
The `HoverDisclosure` component can be used to conditionally hide and show elements in a `ListItem` on hover. However, child elements of `HoverDisclosure` do not have a transition when appearing or disappearing, which makes the background hover appear to "lag" behind. 
Removing the background transition gets both `HoverDisclosure` children and the background color change to happen at around the same time.
> fix(ListItem): Removed background transition

- packages/components/src/Tabs/TabPanel.tsx
- packages/components/src/Tabs/Tabs.test.tsx
- www/src/documentation/components/content/tabs.mdx
In the new Field Picker experience, a keyboard user has to tab from the `Tab` to the `TabPanel` to the first `Tree` in order to focus on the `Tree` items and begin field keyboard traversal. Ideally, I think it'd be cleaner to just tab from the `Tab` directly to the `TreeCollection` since it is the only element in the `TabPanel`.
Adding `tabIndex` as a prop allows devs to pass a non-zero value to `TabPanel`'s `tabIndex` prop and thus remove it from the tab flow.
> feat(TabPanel): Added tabStop boolean prop to TabPanel

- packages/components/src/List/ListItem.test.tsx
- packages/components/src/List/ListItem.tsx
- packages/components/src/Tree/Tree.tsx
Moved aria related props to be passed to label rather than wrapper
**TODO:** Follow-up PR that does the following:
- Extract "aria partitioning" logic into its own function and file (`Tree` can then use this same function to partition out its `aria`-related props and send them to the nested item when `labelToggle === true`)
- Move `ListItemProps` to a separate file (need to do this otherwise we'll have a circular dependency between the "aria partitioning" function file and `ListItem.tsx`)
> fix(ListItem): Properly disperse ARIA props onto ListItem's label container

- packages/components/src/List/ListItem.tsx
- packages/components/src/List/utils/getAriaProps.ts
- Changed name to `partitionAriaProps` (after lodash's partition method)
- Updated props parameter type to use generic type that extends `React.AriaAttributes` type
> refactor(ListItem): Refactor getAriaProps

- packages/design-tokens/src/index.ts
- packages/design-tokens/src/legacy/index.ts
- packages/design-tokens/src/legacy/palette.ts
- www/src/MDX/Pre/prismTheme.ts
Palette can be deep-imported during 2.x series but may be removed entirely in 3.x
```import { palette} from '@looker/design-tokens/lib/legacy'```
BREAKING CHANGE: Design-tokens `palette` is no longer exported from root, deprecated for 3.x
> feat(palette): No longer export palette, mark all as deprecated

- babel.config.js
Storybook's Babel got _really_ noisy after `yarn deduplicate` pass because its now consistently using a more modern version of Babel. These configuration tweaks quiet things back down.
> chore: Quiet down babel complaints due to yarn-deduplicate

- packages/components/src/List/ListItem.tsx
- packages/components/src/List/ListItemDetail.tsx
- packages/components/src/List/ListItemLabel.tsx
- packages/components/src/List/ListItemWrapper.tsx
This allows `TreeItem`s that are in `labelBackgroundOnly` mode have `cursor: pointer` when users hover over the indent whitespace (previously the cursor would switch to the default cursor when hovering over the indent whitespace).
**QUESTION:** Not sure if we should only apply `cursor: pointer` if an `onClick` or `onWhitespaceClick` is provided. If we're assuming that `ListItem`s should always be clickable elements like a button / link, I think it makes sense to always apply this style to the wrapper container (rather than conditionally when one of X props is provided).
> fix(ListItem): Moved cursor styling up to ListItemWrapper

- www/src/documentation/components/layout/grid.mdx
Update grid documentation to include a warning for IE11 and link to suggested alternatives.
> fix(Grid): IE11 warning on grid documentation

- packages/components/src/Dialog/Layout/DialogContent/DialogContent.story.tsx
- packages/components/src/Dialog/Layout/DialogContent/DialogContent.test.tsx
- packages/components/src/Dialog/Layout/DialogContent/DialogContent.tsx
- packages/components/src/Dialog/Layout/DialogContent/index.ts
- packages/components/src/Layout/Semantics/Aside/Aside.test.tsx
- packages/components/src/Layout/Semantics/Section/Section.test.tsx
- packages/components/src/Modal/ModalContent/ModalContent.test.tsx
- packages/components/src/Modal/ModalContent/ModalContent.text.tsx
- packages/components/src/Modal/ModalContent/ModalContent.tsx
- packages/components/src/Modal/ModalContent/index.ts
- packages/components/src/Popover/Layout/PopoverContent/PopoverContent.story.tsx
- packages/components/src/Popover/Layout/PopoverContent/PopoverContent.test.tsx
- packages/components/src/Popover/Layout/PopoverContent/PopoverContent.tsx
- packages/components/src/Popover/Layout/PopoverContent/index.ts
- packages/components/src/Popover/Layout/index.ts
- packages/components/src/Popover/index.ts
- packages/components/src/utils/useOverflow.tsx
- packages/components/src/utils/useOverflow/OverflowShadow.tsx
- packages/components/src/utils/useOverflow/index.ts
- packages/components/src/utils/useOverflow/useOverflow.ts
Work done:
- Created `ModalContent` a simplified version of `DialogContent` to be used on `PopoverContent` as well - DRY.
- Simplified the work done on `DialogContent` using now `Modal`.
- PopoverContent` was restructured to use `Modal`
> feat(PopoverContent): new component to enhance Popover layout

- lerna.json
Switch Lerna to independent version mode to allow packages to have versions that reflect their readiness for production usage.
> chore: Move Lerna to independent mode

- packages/components/src/Tree/utils/generateTreeBorder.ts
The alignment on `Tree`'s `border` prop broke when we updated the alignment. Fixing it here!
> fix(Tree): Fix border alignment

- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.tsx
- packages/components/src/utils/useGlobalHotkeys.ts
- packages/components/src/utils/useMeasuredElement.ts
Align on DOMRect over ClientRect, for interoperability with ESLint's `browser` [environment global](https://github.com/sindresorhus/globals/blob/548191a277c1b946bbcba6e34d593e00290baf48/globals.json#L480).
> fix: use DOMRect in lieu of ClientRect

- packages/components/src/Button/IconButton.tsx
- packages/components/src/Tooltip/types.ts
- packages/components/src/Tooltip/useTooltip.tsx
> fix(useTooltip): Don't include `aria-describedby` on target when Tooltip disabled

- packages/components/src/Accordion/Accordion.tsx
- packages/components/src/Avatar/AvatarIcon.tsx
- packages/components/src/Dialog/Layout/DialogLayout.tsx
- packages/components/src/Layout/Semantics/Aside/Aside.tsx
- packages/components/src/List/types.ts
Fixes Storybook docs tab throwing a React error when it sees jsx inside a jsDoc comment:
> chore: Format jsx in jsDoc with backticks

- packages/components/src/Form/Inputs/Combobox/ComboboxContext.ts
- packages/components/src/Form/Inputs/Combobox/ComboboxList.tsx
- packages/components/src/Form/Inputs/Combobox/utils/useAddOptionToContext.ts
- packages/components/src/Form/Inputs/Combobox/utils/useComboboxRefs.ts
- packages/components/src/Form/Inputs/InputSearch/InputSearch.tsx
- packages/components/src/Form/Inputs/Select/Select.tsx
- packages/components/src/Form/Inputs/Select/SelectMulti.tsx
- packages/components/src/Form/Inputs/Select/SelectOptions.tsx
- packages/components/src/Form/Inputs/Select/utils/useWindowedOptions.tsx
- packages/components/src/List/List.test.tsx
- packages/components/src/List/List.tsx
- packages/components/src/Menu/Menu.story.tsx
- packages/components/src/Menu/MenuList.test.tsx
- packages/components/src/Tree/Tree.tsx
- packages/components/src/utils/getWindowedListBoundaries.test.ts
- packages/components/src/utils/getWindowedListBoundaries.ts
- packages/components/src/utils/useWindow.test.tsx
- packages/components/src/utils/useWindow.tsx
- www/src/documentation/components/forms/input-select.mdx
Refactors `useWindow` to support [`Tree` virtualization](https://github.com/looker-open-source/components/pull/2481).
> fix(useWindow): Simplify windowing for long lists

- packages/components/src/Form/Inputs/InputColor/InputColor.story.tsx
- packages/components/src/Form/Inputs/InputColor/InputColor.test.tsx
- packages/components/src/Form/Inputs/InputColor/InputColor.tsx
This PR updates `InputColor` to call `onChange` if the input's new value is an empty string. Before it was only calling it if the value was a valid color, which an empty string is not.
> fix(InputColor): Call onChange if input value is cleared

- packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.story.tsx
- packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.test.tsx
- packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.tsx
During the recent refactor of the `DialogHeader` the behavior was changed so that the content `detail` property is not displayed when specified.
This PR restores the previous behavior and adds test coverage to validate that it is functional again.
> fix(DialogHeader): Restore previous behavior for DialogHeader detail property

- packages/components/package.json
- www/src/documentation/develop/index.mdx
Adds @types/styled-system to `devDependencies` to remove the need for downstream consumers to also install that dependency within their own projects.
> fix: Include @types/styled-system in devDependencies to simplify installation

- packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.test.tsx
- packages/components/src/Dialog/Layout/DialogHeader/DialogHeader.tsx
> fix(DialogHeader): Properly interpret `detail={null}` (still don't show close option)

- packages/components/src/Panel/Panel.story.tsx
- packages/components/src/Panel/Panel.test.tsx
- packages/components/src/Panel/PanelWindow.tsx
- packages/components/src/Panel/Panels.tsx
- packages/components/src/Panel/usePanel.tsx
Get rid of `Portal` in `Panel` because the positioning is buggy. Use `zIndexFloor` to resolve the stacking issue with `Tree`.
> fix(Panel): Render properly in Drawer or Dialog

- packages/components/src/Button/IconButton.test.tsx
- packages/components/src/Button/iconButtonColor.ts
Correct issue where `key` color was used in `:active` pseudo state for `IconButton` with `toggleColor`
> fix(IconButton): Properly use toggleColor for :active psuedo states

- packages/components/src/List/ListItem.test.tsx
- packages/components/src/List/ListItem.tsx
- packages/components/src/List/types.ts
- packages/components/src/List/utils/getDetailOptions.ts
- packages/components/src/Tree/Tree.test.tsx
- packages/components/src/Tree/TreeItem.test.tsx
- packages/components/src/Tree/stories/FieldItem.tsx
- packages/components/src/utils/HoverDisclosure/HoverDisclosure.tsx
Make sure HoverDisclosure behaves within flex containers
BREAKING CHANGE: strategy prop is no longer supported. `width` may be used to workaround.
> fix(HoverDisclosure): Remove strategy prop, add placeholderWidth

- config/website-latest.sh
This PR corrects a documentation web site deploy bug where `lerna.json` `version` key is still leveraged (it's now "independent"). Current each version of the site overwrites into a `vindependent` folder instead of `v1.1.1` 
`latest` which is the publicly visible version still works fine but it'd be ideal to straighten this out so we can keep collecting "historic" versions of the documentation site for easy reference.
> fix: Correct web site publishing to work with lerna independent versioning

- packages/components/src/Card/CardContent.tsx
- packages/design-tokens/src/utils/index.ts
- packages/design-tokens/src/utils/paddingDefaultsHelper.test.ts
- packages/design-tokens/src/utils/paddingDefaultsHelper.ts
This PR introduces a helper to make sure that padding values specified on the CardContent component are properly interleaved with the default values (`p: medium`)
This doesn't feel like the most efficient solution to the problem but it does get the rest results. 
Would love thoughts on a more clever / efficient ways to solve this
> fix(CardContent): Properly absorb padding (pN) values

- packages/components/src/Dialog/Layout/DialogLayout.story.tsx
- packages/components/src/Dialog/Layout/DialogLayout.test.tsx
- packages/components/src/Dialog/Layout/DialogLayout.tsx
> fix(DialogLayout): `footerSecondary` is only valid if `footer` is also specified

- config/i18nIgnoredProps.js
- packages/components/src/Accordion/Accordion.tsx
- packages/components/src/Accordion/types.ts
- packages/components/src/List/List.tsx
- packages/components/src/List/types.ts
- packages/components/src/Tree/Tree.tsx
- packages/components/src/Tree/TreeCollection.tsx
- packages/components/src/Tree/TreeCollectionContext.ts
- packages/components/src/Tree/TreeContext.tsx
- packages/components/src/Tree/WindowedTreeCollection.test.tsx
- packages/components/src/Tree/WindowedTreeCollection.tsx
- packages/components/src/Tree/WindowedTreeNode.tsx
- packages/components/src/Tree/stories/FieldItem.tsx
- packages/components/src/Tree/stories/Tree.story.tsx
- packages/components/src/Tree/stories/Windowing.story.tsx
- packages/components/src/Tree/types.ts
- packages/components/src/Tree/utils/getWindowedTreeNodeFilterer.ts
- packages/components/src/Tree/utils/useWindowedTree.tsx
- packages/components/src/Tree/utils/windowedTreeReducer.ts
- packages/components/src/utils/useArrowKeyNav.ts
- packages/design-tokens/src/system/index.ts
- playground/src/index.tsx
- www/src/MDX/Pre/allComponents.ts
- www/src/documentation/components/content/tree.mdx
1. Add `WindowedTreeCollection` – so much needs to be different in order to support virtualization (`trees` prop vs children, no internal state allowed, including the toggle state, and density needs to be defined at the top level) that I think a separate component will be less confusing.
2. Add internal-only `useWindowedTree` and `WindowedTreeNode` to make windowing work
3. ~~Refactor `useWindow` to support `useWindowedTree` and remove support for variable windowing, since it's not being used and it would've complicated the refactor.~~ Moving this to a separate PR: https://github.com/looker-open-source/components/pull/2485
**NOTE:** The Windowing story has some storybook-docs-related bottleneck (I tried disabling docs but it didn't seem to help) so it's pretty slow. Check it out with …
> feat(Tree): Add virtualization support

- packages/components/src/Modal/ModalHeader/ModalHeader.test.tsx
Fixes lint errors in `ModalHeader.test.tsx`. Not sure how these got through but they're causing my filters PR to fail CI.
> fix(ModalHeader): Lint errors in test file

- packages/eslint-config/oss-compat.js
Workaround for discrepancies between the prettier version in this repo (`2.3.1`) and the core product repo (`2.2.1`) that interfere with the OSS sync process.
> chore(lint): Disable prettier in oss-compat

- package.json
- yarn.lock
Upgrade necessary for filters release.
> chore(deps): bump @looker/sdk from 21.6.0 to 21.8.0

- .github/workflows/ci.yml
- jest.config.js
- packages/components/src/VisuallyHidden/VisuallyHidden.test.tsx
The pull request re-enables coverage reporting on our code-base using a Github action and Jest's built-in reporter functionality and adds specific features detailed below.
*NOTE*: I haven't made this a blocking check as of yet and there's no threshold currently with that in mind. I'd like run this in production for a week or two and it seems to behave we can go from there.
Uses [`upload-artifact`](https://github.com/actions/upload-artifact) to upload the entire coverage report for easy review
Automatically annotates coverage gaps and errors.
> fix: Restore CI code coverage reporting

- packages/components-providers/package.json
- packages/components-theme-editor/package.json
- packages/components/package.json
- packages/design-tokens/package.json
- www/src/documentation/develop/index.mdx
I observed that components brings in its own version of lodash whenever it's imported to helltool. Although `packages/components/README.md` [states that lodash should be supplied as a peer dependency](https://github.com/looker-open-source/components/blame/12658bddd81bf4dc1625865de424cc674ea07e1c/packages/components/README.md#L15), this does not actually appear to be the case. This PR moves lodash to `peerDependencies` and `devDependencies` wherever it is found in the `components` tree.
> fix: move lodash to peer dependencies

- packages/components/src/Form/Inputs/Combobox/ComboboxInput.tsx
- packages/components/src/Form/Inputs/InputSearch/InputSearch.test.tsx
Adds `focus()` to the clear button handler in `ComboboxInput`. (`InputSearch` is the most obvious use case but this also affects `Select` and `SelectMulti` if they have `isClearable`).
> fix(InputSearch): Return focus to input after clearing

- packages/components/src/Form/Inputs/InputColor/utils/stringToSimpleHsv.test.ts
- packages/components/src/Form/Inputs/InputColor/utils/stringToSimpleHsv.ts
- Added fallback values to `simpleStringToHsv` function to prevent NaN values from appearing in color state's h and s values
- Added tests to assure that we replace NaN values with default values (i.e. 0)
> fix(InputColor): Incorrect coloring and positioning when hueless or saturationless color is provided

- www/src/documentation/components/forms/radio-group.mdx
> fix(RadioGroup): correct usage of `defaultValue` in documentation

- packages/components/src/DataTable/Column/column.ts
- www/package.json
- www/src/MDX/Headings.tsx
- www/src/documentation/components/content/data-table.mdx
Clarifies behavior of `DataTable` columns when a percentage (numeric) width is used.
> docs(DataTable): Clarify numeric-width (percentage) column behavior

- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.story.tsx
- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.test.tsx
- packages/components/src/Form/Inputs/RangeSlider/RangeSlider.tsx
If `RangeSlider` is rendered inside a component with a "double re-render", e.g. one state variable is set due to the `onChange` being called, then another state variable is set in a `useEffect` as a result of the first state change, or certain implementations of redux can cause this, then it exposes a bug where the value is continually reverted: https://looker-open-source.github.io/components/canary/storybook/?path=/story/rangeslider--rerender-repro&globals=measureEnabled:false
My first attempt to fix this https://github.com/looker-open-source/components/pull/2174 introduced a different bug where the value would not respond to min/max changes.
This time around, my approach was to remove all the `// eslint-disable-next-line react-hooks/exhaustive-deps`, since breaking this rule does lead …
> fix(RangeSlider): Value reset due to intermediate rerender

- packages/components/src/Menu/MenuItem.tsx
Fixes an SVG attribute error message in the console when opening a nested menu:
> fix(MenuItem): SVG error when opening a nested menu

- packages/components/src/Menu/Menu.story.tsx
- packages/components/src/Menu/Menu.test.tsx
- packages/components/src/Menu/MenuItem.tsx
- packages/components/src/Menu/MenuList.tsx
- packages/components/src/Menu/NestedMenuProvider.tsx
- packages/components/src/Menu/useNestedMenu.tsx
Clicking a nested menu item now closes the parent menu (unless `preventDefault()` has been called on the event).
I added a `closeParentMenu` callback to `NestedMenuContext` and call that, if present, from the `MenuItem` click handler.
> fix(Menu): Close the parent menu after clicking a nested menu item

- packages/components/src/DataTable/DataTable.test.tsx
- packages/components/src/DataTable/DataTable.tsx
- packages/components/src/DataTable/stories/Interaction.tsx
- packages/components/src/DataTable/utils/allItemsSelected.ts
> fix(DataTable): Corrects issue where "All Selected" checkbox is checked when `selectedItems=0` and `pageItems=0` (easily triggered by loading state)

- packages/components/src/DataTable/Table.tsx
Additional context available in: https://b.corp.google.com/issues/194313414
> fix(DataTable): Stop explicitly removing scrollbar from DataTable overflow behavior

- packages/components/src/Button/iconButtonTypes.ts
IconButton's label element is used to propagate a tooltip applied to the `IconButton`. With that in mind they should share the same typing
Bug: https://buganizer.corp.google.com/issues/194341079
> fix(IconButton): IconButton label should support same typing as Tooltip content

- packages/components/src/Form/Fields/Field.tsx
- packages/components/src/Form/Fields/FieldInline.tsx
- packages/components/src/Form/Fields/FieldToggleSwitch/FieldToggleSwitch.story.tsx
- packages/components/src/Form/Fields/FieldToggleSwitch/FieldToggleSwitch.test.tsx
Grid layout allows for an easy refactor here to improve tab stop order of `Field` & `FieldInline`
Related ticket: https://buganizer.corp.google.com/issues/194388659
> fix(Field): Correct tab-stop order of `Field` & `FieldInline`

- packages/design-tokens/src/theme/ThemeCustomizations.ts
- packages/design-tokens/src/theme/utils/generateTheme.test.ts
- packages/design-tokens/src/theme/utils/generateTheme.ts
Currently `ThemeCustomizations` supports overloading `fontFamilies` but not `fontSources`. Both would be needed to successfully use a font-face that's not available on locally.
> feat(ComponentsProvider): ThemeCustomizations should support overloading fontSources

- babel.config.js
- package.json
* Files in the filter packages `./src/locales` folder were not getting built since they were `.js` file format – added `.js` to the build commands.
* `.spec` files were getting built unnecessarily – added them to the ignore section of `babel.config.js`
> chore(Filter Packages): Build .js files and ignore .spec files

- packages/components/src/Tree/TreeItemContent.tsx
When built, `TreeItemContent` did not properly call the `generateIndent` function which led to `Tree / TreeItem`s from indenting properly. Calling the function explicitly in a wrapper arrow function resolves this behavior.
> fix(Tree): Fixed Tree indent bug

- packages/components/src/Tree/Tree.test.tsx
- packages/components/src/Tree/Tree.tsx
- packages/components/src/Tree/stories/Tree.story.tsx
Check `isOpen` for being defined rather than truthy to get correct accordion props.
Add story and update controlled test to catch this failure.
> fix(Tree): Controlled isOpen

- packages/components/src/Badge/Badge.test.tsx
This PR adds a test for the Badge component using default props and creates a new describe() suite for both tests
> test(Badge): testing prop defaults

- packages/components-providers/src/I18n/useI18n.test.tsx
Improves coverage for the `useI18n` hook (which gets called from `ComponentsProvider`).
> test(useI18n): improve coverage

- packages/components/src/DataTable/DataTable.test.tsx
- packages/components/src/DataTable/Item/DataTableItem.tsx
- packages/components/src/DataTable/Item/DataTableRow.tsx
- packages/components/src/DataTable/utils/__snapshots__/sort_utils.test.ts.snap
- packages/components/src/DataTable/utils/allItemsSelected.ts
- packages/components/src/DataTable/utils/sort_utils.test.ts
- packages/components/src/DataTable/utils/useSelectManager.test.tsx
- packages/components/src/DataTable/utils/useSelectManager.tsx
- yarn.lock
Increases test coverage for DataTable utilities and child components. This is accomplished by both adding tests but also refactoring instances where branches of code were functionally unreachable.
https://buganizer.corp.google.com/issues/194403850
I'll create a new branch for DataTable/getNextFocus tests, which is a separate buganizer ticket and will be a decent chunk of work on its own.
> test(DataTable): Utilities Test Coverage

- packages/components/src/Accordion/Accordion.test.tsx
- packages/components/src/Accordion/Accordion.tsx
- Added a test to check `console.warn` when `Accordion` is only partially controlled (i.e. only receives one of two controlled open state props)
- Added a test to check legacy composition
> test(Accordion): Add coverage

- packages/components/src/Modal/modal.test.tsx
-[ ] 🤥  tests update
This will complement the other PR that has some update on test coverage related to the other `Modal` files.
removing `CloseHeaderButton.tsx` seems to stop the trigger for extra test for Modal. This file has been modified a little bit and renamed as `ModalHeaderCloseButton.tsx`. Everything is working as expected with this change
> test(Modal): updated for better test coverage

- packages/components/src/Form/Inputs/InputFilters/InputFilters.test.tsx
- packages/components/src/Form/Inputs/InputFilters/InputFilters.tsx
- packages/components/src/Form/Inputs/InputFilters/types.ts
`InputFilters` should support user-specification of `placeholder`
> fix(InputFilters): Should support placeholder attribute

- packages/components/src/Layout/Semantics/Layout/Layout.story.tsx
- packages/components/src/VisuallyHidden/VisuallyHidden.test.tsx
- packages/components/src/VisuallyHidden/VisuallyHidden.tsx
Somehow Chrome and only Chrome decided to interpret the lack of `left` and `top` in `VisuallyHidden` as `bottom: [a negative number proportional to the height of the page]` when `<Page fixed>`, (i.e. an element with `height: 100vh`) is an ancestor. Explicitly adding `left: 0` and `top: 0` fixes it.
This issue is currently happening on our docs site: https://looker-open-source.github.io/components/latest/components/actions/button
I added a repro story in `Layout.story.tsx` and also made a sandbox repro here: https://codesandbox.io/s/gallant-franklin-wyn7i
> fix(VisuallyHidden): Position causing whitespace issue with Page in Chrome

- packages/components/src/Button/ButtonItem.tsx
- packages/components/src/Button/ButtonSet.tsx
- packages/components/src/Button/ButtonToggle.story.tsx
When a user opens a button toggle filter via click inside a popover, the first item is focused (via the "initial focus" logic of the popover's focus trap) and the `neutralSubtle` override used in the core product is a dark enough grey as to make it look disabled (see screen recording below).
If the user opens the popover via keyboard, the focus ring is shown, which is a more obvious indicator. Activating the "click only" focus style is actually rare and pretty much only happens with the initial focus of the popover. Short of our preferred solution of adding a Done button to the popover that would instead receive initial focus, removing the background color for click-only focus will reduce confusion.
https://user-images.githubusercontent.com/53451193/128808419-9ff7d0ed-b0a0-48a9-bf1f-f62071 …
> fix(ButtonToggle): Remove background color for focus via click

- packages/components/src/Accordion/Accordion.tsx
- packages/components/src/Accordion2/Accordion2.tsx
- packages/components/src/List/List.tsx
- packages/components/src/ListItem/ListItemIcon.tsx
- packages/components/src/ListItem/ListItemLabel.tsx
- packages/components/src/ListItem/utils/createListItemPartitions.tsx
- packages/components/src/ListItem/utils/listItemDimensions.ts
- packages/components/src/Menu/MenuHeading.tsx
- packages/components/src/Menu/MenuItem.tsx
- packages/components/src/NavTree/NavTree.tsx
- packages/components/src/NavTree/NavTreeItem.tsx
- packages/components/src/Tree/utils/generateIndent.ts
- packages/design-tokens/src/theme/theme.ts
Refactors all locations that initialize `density` as `0` to instead leverage `theme.defaults.density`
This refactor will allow for easy theme-based override of density in applications.
> refactor(density): Consolidate default density in theme

- www/src/documentation/components/text/span.mdx
> docs: typo `componentn` in Span documentation

- packages/components/src/Ripple/Ripple.story.tsx
- packages/components/src/Ripple/rippleStyle.ts
- packages/components/src/Ripple/types.ts
- packages/components/src/Ripple/useRipple.test.tsx
- packages/components/src/Ripple/useRipple.tsx
Adjust the hook & style functions so they can both be applied to the same component instead of the style needing to be applied to a child component.
> refactor: Ripple effect

- packages/components/src/Ripple/Ripple.story.tsx
- packages/components/src/Ripple/index.ts
- packages/components/src/Ripple/rippleStyle.ts
- packages/components/src/Ripple/types.ts
- packages/components/src/Ripple/useRipple.test.tsx
- packages/components/src/Ripple/useRipple.tsx
- packages/components/src/Ripple/useRippleHandlers.test.tsx
- packages/components/src/Ripple/useRippleHandlers.ts
- packages/components/src/Ripple/useRippleState.ts
- packages/components/src/Ripple/useRippleStateBG.ts
Adds hooks and style helpers to support the ripple effect, and a story file to demo it.
This PR adds it to `IconButton`: https://github.com/looker-open-source/components/pull/2721
**Question: should the ripple functions be exported or for internal use only? If the latter, I guess this would be a "chore" PR instead of a "feat".**
> feat: Ripple effect

- apps/filter-demo/src/DashboardEmbed.tsx
- apps/filter-demo/src/DashboardList.tsx
- apps/filter-demo/src/FilterDemo.tsx
- Remove `parseInt` for dashboard id – it's no longer necessary (better typing on the embed sdk) and breaks for lookml dashboards
- Take the 1st 100 dashboards instead of the 1st 10 (I was trying to view lookml dashboards on the lenslatest instance but there weren't any in the 1st 10)
- Add filtering in the dashboard `Select`
- For testing purposes, these changes are deployed on the lenslatest instance "Filter Demo" extension (not "Filter Demo Dev")
- Select the "Testing Filters Dash" dashboard to verify that lookml dashboards are now working
> chore(Filter Demo): support lookml dashboards, longer dashboard list

- packages/components/src/Form/Inputs/Combobox/ComboboxMultiInput.tsx
- packages/components/src/Form/Inputs/InputChips/InputChips.spec.tsx
- packages/components/src/Form/Inputs/InputChips/InputChips.story.tsx
- packages/components/src/Form/Inputs/InputChips/InputChips.tsx
- packages/components/src/Form/Inputs/Select/SelectMulti.spec.tsx
- packages/components/src/Form/Inputs/Select/SelectMulti.tsx
- packages/components/src/Form/Inputs/Select/stories/SelectMulti.story.tsx
- www/src/documentation/components/forms/input-chips.mdx
- www/src/documentation/components/forms/select-multi.mdx
Adds a `formatInputValues` prop to `InputChips` and `SelectMulti` (which contains `InputChips`). 
The default is `value.trim()`, to match the current behavior, which trims whitespace from inputted values before validating them – `false` will leave the whitespace intact.
> feat(SelectMulti & InputChips): Support value formatting

- packages/components/src/Dialog/Layout/DialogContent/DialogContent.spec.tsx
- packages/components/src/Dialog/Layout/DialogContent/DialogContent.tsx
- packages/components/src/Popover/Layout/PopoverContent/PopoverContent.spec.tsx
- packages/components/src/Popover/Layout/PopoverContent/PopoverContent.tsx
Fixes the way `p` is absorbed into the `PopoverContent` and `DialogContent` so that it overrides any default values properly.
Before the fix: `<PopoverContent p="xxlarge">` the `xxlarge` padding wouldn't be applied at all because the component internally had more specific selectors/properties `px` & `py`. 
This changes alter the implementation of `PopoverContent` & `DialogContent` to consistent ingest padding values so that externally specified properties act in a predictable manner.
> fix(PopoverContent): Properly absorb `p` value (also `DialogContent`)

- packages/components-date/src/InputTime/InputTime.tsx
- packages/components/src/Button/ButtonItem.tsx
- packages/components/src/Button/ButtonTransparent.tsx
- packages/components/src/Chip/Chip.tsx
- packages/components/src/DataTable/BulkActions/BulkActions.tsx
- packages/components/src/DataTable/Header/DataTableHeaderCell.tsx
- packages/components/src/DataTable/Item/DataTableRow.tsx
- packages/components/src/Form/Inputs/InlineInputText/InlineInputText.tsx
- packages/components/src/Form/Inputs/InlineTextArea/InlineTextArea.tsx
- packages/components/src/Form/Inputs/InputColor/Swatch/Swatch.tsx
- packages/components/src/Form/Inputs/InputText/InputText.tsx
- packages/components/src/Form/Inputs/Radio/Radio.tsx
- packages/components/src/Form/Inputs/TextArea/TextArea.tsx
- packages/components/src/Form/Inputs/innerInputStyle.ts
- packages/components/src/Form/ValidationMessage/ValidationMessage.tsx
- packages/components/src/ProgressCircular/DeterminateProgress.tsx
- packages/components/src/ProgressCircular/ProgressSvg.tsx
- packages/components/src/Spinner/Spinner.tsx
- packages/components/src/Table/TableCell/tableCell.ts
- packages/components/src/Tabs2/TabList2.tsx
- packages/components/src/utils/useFocusVisible.ts
- packages/design-tokens/src/elevation/index.ts
- www/src/MDX/Link.tsx
- www/src/components/DocTable.tsx
- www/src/documentation/components/layout/demos/BoxSpacingRecipeTable.tsx
- www/src/documentation/develop/theme.mdx
- www/src/documentation/foundations/breakpoints.mdx
- www/src/documentation/foundations/demos/ColorBlendsGrid.tsx
- www/src/documentation/foundations/demos/ElevationList.tsx
Makes our use of destructring within Styled Components interpolated strings (CSS blocks) consistent - primarily replacing `${(props) => props.theme` with `${({ theme }) => theme`
> refactor: Consistent structure properties in styled-components interpolation blocks

- packages/components/src/Accordion2/Accordion2.spec.tsx
- packages/components/src/Accordion2/useAccordion2.tsx
Currently `useAccordion2` (and by proxy `Accordion2` & `Accordion`) responds to mutations of the `defaultOpen` property. Instead it should be a one-and-done property – changes should be ignored.
> fix(useAccordion2): Ignore changes to defaultOpen

- packages/components/src/ListItem/ListItem.spec.tsx
- packages/components/src/ListItem/ListItemContent.tsx
- packages/components/src/Tabs/Tab.tsx
- packages/components/src/Tabs/Tabs.spec.tsx
Addresses a similar issue with `ListItemContent` as well.
> fix(Tab2): `Tabs` should be output with `type="button"` to prevent accidental form submission

- packages/components/src/Form/Inputs/Checkbox/Checkbox.tsx
I took at look at the cases where we've had to disable `react/display-name` – in the case of `Checkbox` it appears to be working properly without disabling the rule.
> test: Remove unneeded eslint-disable react/display-name

- packages/design-tokens/src/color/types/specifiable.ts
- packages/design-tokens/src/color/utils/colorBreakdown.ts
- packages/design-tokens/src/color/utils/pickSpecifiableColors.spec.ts
Correct's the "shape" of the color breakdown output.
Follow-up at b/199927358 to address documenting `pageBackground` publicly.
> docs: Correct color documentation presentation

- packages/components/src/Button/MultiFunctionButton.stories.tsx
- packages/components/src/Button/MultiFunctionButton.tsx
- packages/components/src/DataTable/utils/useDataTable.tsx
- packages/components/src/DataTable/utils/useDataTableSortManager.tsx
- packages/components/src/Dialog/Layout/DialogLayout.stories.tsx
- packages/components/src/Layout/Box/Box.stories.tsx
- packages/components/src/Layout/Semantics/Semantics.stories.tsx
- packages/components/src/LkFieldTree/LkFieldGroupTree.tsx
- packages/components/src/LkFieldTree/LkFieldViewTree.tsx
- packages/components/src/Menu/Menu.stories.tsx
- packages/components/src/Menu/MenuList.stories.tsx
- packages/components/src/NavTree/NavTree.stories.tsx
- packages/components/src/OrderedList/OrderedList.stories.tsx
- packages/components/src/PageSize/PageSize.stories.tsx
- packages/components/src/UnorderedList/UnorderedList.stories.tsx
CodeSandbox does not seem to like the `'.'` import path used in `LkFieldGroupTree.tsx`.
It thinks `LkFieldTree` is undefined when `styled` gets to it on [this line](https://github.com/looker-open-source/components/blob/main/packages/components/src/LkFieldTree/LkFieldGroupTree.tsx#L37), and I can't think of any other explanation besides it not liking the import path.
> fix(LkFieldGroupTree): Import path issue for CodeSandbox

- packages/design-tokens/src/defaults/generateDefaults.spec.ts
- packages/design-tokens/src/defaults/generateDefaults.ts
- packages/design-tokens/src/defaults/index.ts
- packages/design-tokens/src/defaults/types.ts
- packages/design-tokens/src/theme/ThemeCustomizations.spec.ts
- packages/design-tokens/src/theme/ThemeCustomizations.ts
- packages/design-tokens/src/theme/theme.ts
Introduce support for `themeDefaults` to be specified via `themeCustomizations` so that consumers have a consistent interface to use for overriding these settings going forward.
> feat: Support specification of `brandAnimation` and `density` via `themeCustomizations`

- .github/workflows/canary.yml
- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/release-pull-request.yml
- .github/workflows/release.yml
- package.json
- yarn.lock
- Corrects caching for `node_nodules` in CI accelerating each job (30s - 1m savings)
- Moves Jest artifact upload to non-blocking `coverage` task (~2m savings)
- Removes Jest coverage check for core run - now run on separate coverage job (~4m savings)
- `image-snapshots` no longer re-runs on failure (~3m)
> test: Improve CI job time

- packages/components/src/Popover/Popover.spec.tsx
- packages/components/src/Popover/usePopoverToggle.tsx
`Popover` applies an `onClick` to its child that opens the popover and also calls `e.preventDefault` to avoid unintended actions, like a button submitting a form.
The "closing" click is  more complicated. Once open, a click listener is added to the document,  so that a click anywhere will close the popover. If that click happens to be on the trigger element, `event.stopPropagation` is called and then `return`, which avoids calling the original "opener" `onClick` and re-opening the popover, so `e.preventDefault` doesn't get called. This PR fixes that.
> fix(Popover): preventDefault on closing click

- .eslintrc.js
- apps/storybook/src/stories.shots.ts
- packages/components-date/.prettierrc.json
- packages/components-date/package.json
- packages/components-providers/.prettierrc.json
- packages/components-providers/package.json
- packages/components-providers/src/FontFaceLoader/FontFaceLoader.spec.tsx
- packages/components-test-utils/.prettierrc.json
- packages/components-test-utils/package.json
- packages/components-test-utils/src/create_with_theme.tsx
- packages/components-theme-editor/.prettierrc.json
- packages/components-theme-editor/package.json
- packages/components/.eslintrc.js
- packages/components/.prettierrc.json
- packages/components/package.json
- packages/demos/.prettierrc.json
- packages/demos/package.json
- packages/design-tokens/package.json
- packages/eslint-config-oss/src/index.js
- packages/icons/.prettierrc.json
- packages/icons/package.json
- packages/stylelint-config/.prettierrc.json
- www/package.json
To support parity with core-product monorepo move to using `eslintConfig` key in each `package.json` and move package-specific to those blocks as well.
Move 1 set of rules to core `eslint-config-oss` since it's broadly applied.
> refactor: Move ESLint configuration to a per-package key

- packages/components/src/Dialog/Backdrop.tsx
- packages/components/src/Dialog/DialogSurface.tsx
- packages/components/src/Drawer/DrawerSurface.tsx
Previously, `DialogSurface`, `DrawerSurface`, and `Backlog` were using CSS transition to animate in and out. The problem with this is that the transition _starts_ when the className changes from `'entering'` to `'entered'` which is 300ms after the click to open. The dialog renders immediately on click, then sits hidden for 300ms before animating in.
We want the animation to begin immediately on render, so we have to use CSS animation instead. `PanelSurface` was already doing this.
> fix(Dialog): Animation delay on open

- packages/components/src/Menu/Menu.spec.tsx
- packages/components/src/Menu/Menu.stories.tsx
- packages/components/src/Menu/NestedMenuProvider.tsx
- packages/components/src/Menu/useNestedMenu.tsx
Though it wasn't specifically designed for it, nesting menus 3 levels deep mostly works, except for these issues when clicking on an item in the 3rd level menu:
1. There's an error from focus trap
2. Only the 2nd and 3rd menus close, not the 1st
This PR addresses both by addressing issue 2. 
Issue 1 is due to a complicated collision between how React bubbles events up through a portal, how we handle focus & blur events in `useArrowKeyNav`, and focus trap. Calling `stopPropagation` could fix this but might also have unforeseen consequences. So closing all the menus is the simpler solution.
> fix(Menu): Error when nesting 3 levels deep

- jest.setup.js
- packages/components/src/Button/IconButton.spec.tsx
- packages/components/src/DataTable/DataTable.spec.tsx
- packages/components/src/Form/Inputs/InputChips/InputChips.spec.tsx
- packages/components/src/Tooltip/Tooltip.spec.tsx
- packages/components/src/Truncate/Truncate.spec.tsx
- packages/components/src/utils/useHovered.spec.tsx
- packages/components/src/utils/useScrollLock.spec.tsx
1. Match the `requestAnimationFrame` mock in jest setup with that in the core product.
2. Fix `paddingSpy` in `useScrollLock.spec.tsx` – not sure why it was working before but the core product wasn't having it.
I removed all existing instances of `jest.spyOn(window, 'requestAnimationFrame')`, since they are now redundant, except for two in `Combobox.spec` and `Select.spec`. Those will take some time to unwind so I want to save them for a follow-up (I created a ticket). In most cases an additional `runTimers()` call was necessary since the `requestAnimationFrame` mock uses a `setTimeout`.
> chore: Jest mock consistency

- packages/design-tokens/src/color/types/index.ts
Core product uses deep-import to pull in `SpecifiableTextColors` type currently. This will be problematic once code is shifted to core monorepo (and there's not really a good argument _not_ to go ahead and export it anyway) :)
> fix: Export type for SpecifiableTextColors

- bin/publish-package-json.js
Copy the README into the lib folder after building so that it appears on the NPM page.
> chore: Update postbuild script to copy readme
